"""Quick Tests for Reason Tools"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../71_micro_tests.ipynb.

# %% auto 0
__all__ = ['simple_jsonld', 'mock_output', 'afs', 'hits']

# %% ../../71_micro_tests.ipynb 2
simple_jsonld = """
{
 "@context":{"@vocab":"https://ex.org/"},
 "@id":"ex:e1",
 "@type":"Event"
}
"""

# %% ../../71_micro_tests.ipynb 3
# Mock a "no-op" string to simulate reason_tool output
mock_output = "No-op. No changes made to the graph."

# Test with mock output
test_eq("no-op" in mock_output.lower(), True)

# Affordance detection
afs = AffordanceScanner()
hits = afs.scan(simple_jsonld)
test_eq(len(hits), 0)

# %% ../../71_micro_tests.ipynb 4
# Create a mock output
mock_output = "No-op. No changes made to the graph."
test_eq("no-op" in mock_output.lower(), True)

# Affordance detection
afs = AffordanceScanner()
hits = afs.scan(simple_jsonld)
test_eq(len(hits), 0)
