"""Exposes `reason_over` as a single OpenAIâ€‘style function descriptor."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../70_tool_reason.ipynb.

# %% auto 0
__all__ = ['log', 'gm', 'FUNCTION_SPEC', 'reason_tool']

# %% ../../70_tool_reason.ipynb 2
import json
from typing import Dict, Tuple
from rdflib import Graph, ConjunctiveGraph
from ..core.debug import get_logger
from ..reason.sandbox import reason_over
from ..core.graph import GraphManager
from ..reason.prov import wrap_patch_with_prov
from pyshacl import validate

# %% ../../70_tool_reason.ipynb 3
log=get_logger("tool.reason")
gm = GraphManager(use_rdflib=True)   # shared, memoryâ€‘safe

# %% ../../70_tool_reason.ipynb 4
FUNCTION_SPEC:Dict = {
  "name":"reason_over",
  "description":"Run SHACL rules or SPARQL CONSTRUCT on JSONâ€‘LD and update memory",
  "parameters":{
    "type":"object",
    "properties":{
      "jsonld":{"type":"string","description":"Primary JSON-LD input"},
      "shapes_turtle":{"type":"string","description":"Optional SHACL shapes in turtle"},
      "query":{"type":"string","description":"Optional SPARQL CONSTRUCT query"}
    },
    "required":["jsonld"]
  }
}

# %% ../../70_tool_reason.ipynb 5
def reason_tool(jsonld:str,
                shapes_turtle:str|None=None,
                query:str|None=None) -> str:
    patch, summary = reason_over(jsonld=jsonld,
                                 shapes_turtle=shapes_turtle,
                                 query=query)
    # Convert JSON-LD to nquads format for ingestion
    from rdflib import Graph
    temp_g = Graph()
    temp_g.parse(data=patch, format="json-ld")
    nquads = temp_g.serialize(format="nquads")
    gm.ingest_nquads(nquads, graph_id="patch")
    return summary
