"""Utilities for expanding, compacting, and canonicalising JSON-LD using **pyld** while delegating all network fetches to our registry-aware, cache-memoised loader."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../05_context.ipynb.

# %% ../../05_context.ipynb 3
from __future__ import annotations

import json, hashlib
from functools import lru_cache
from typing import Any, Dict, List

from pyld import jsonld

from .debug import get_logger
from .cache import InMemoryCache
from ..vocab.registry import registry
from ..vocab.composer import composer

log = get_logger("context")
_cache = InMemoryCache(maxsize=512)

# %% auto 0
__all__ = ['log', 'get_document_loader', 'ContextProcessor']

# %% ../../05_context.ipynb 5
@_cache.memoize("jsonld-doc")
def _http_get(url: str) -> Dict[str, Any]:
    import httpx, json as _json
    log.debug(f"doc-loader GET {url}")
    r = httpx.get(url, follow_redirects=True, timeout=10)
    r.raise_for_status()
    return dict(contextUrl=None, documentUrl=url, document=r.text)

def get_document_loader():
    "Return a pyld-compatible loader that understands registry *prefixes and URIs*."
    _mem: Dict[str, Dict[str, Any]] = {}

    def loader(url: str):
        # 1️⃣  Try registry (prefix **or** alias URL)
        try:
            entry = registry.resolve(url)
            ctx   = entry.context_payload()
            return dict(contextUrl=None, documentUrl=url, document=json.dumps(ctx))
        except KeyError:
            pass  # not a known vocab – proceed

        # 2️⃣  Memoised HTTP fetch (sandboxed envs may still block; caller must catch)
        if url not in _mem:
            _mem[url] = _http_get(url)
        return _mem[url]

    return loader

# Register globally so every pyld call uses it
jsonld.set_document_loader(get_document_loader())

# %% ../../05_context.ipynb 7
class ContextProcessor:
    "Thin wrapper around pyld with sensible defaults."

    def expand(self, doc: Dict[str, Any] | List[Any]) -> List[Dict[str, Any]]:
        "Return expanded JSON-LD array."
        return jsonld.expand(doc, options=dict(base=None))

    def compact(self, doc: Dict[str, Any] | List[Any],
                ctx: Dict[str, Any] | List[Any]) -> Dict[str, Any]:
        "Compact against a given `@context`."
        return jsonld.compact(doc, ctx, options=dict(base=None))

    def normalize(self, doc: Dict[str, Any] | List[Any]) -> str:
        """
        Canonicalise using URDNA2015 and return **N-Quads** string.
        Useful for later signing.
        """
        return jsonld.normalize(
            doc,
            options=dict(algorithm="URDNA2015", format="application/n-quads")
        )

    # convenience ------------------------------------------------------
    def expand_with(self, prefixes: List[str], doc: Dict[str, Any]) -> List[Dict[str, Any]]:
        "Inject composed context, then expand."
        ctx = composer.compose(prefixes)
        merged = dict(doc, **ctx)
        return self.expand(merged)
