"""A lightweight, _immutable_ wrapper around a JSON-LD dict."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../06_entity.ipynb.

# %% ../../06_entity.ipynb 2
from __future__ import annotations

import hashlib, json
from datetime import datetime
from functools import cached_property
from typing import Any, Dict, List, Optional
from copy import deepcopy  # Add this import!

from pydantic import BaseModel, Field, model_validator

from .debug import get_logger
from .context import ContextProcessor
from ..vocab.composer import composer

log = get_logger("entity")
_proc = ContextProcessor()

# %% auto 0
__all__ = ['log', 'Entity']

# %% ../../06_entity.ipynb 4
def _deep_hash(d: Dict[str, Any]) -> str:
    "SHA-256 over canonical JSON (sort keys, no spaces)."
    return hashlib.sha256(
        json.dumps(d, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()

# %% ../../06_entity.ipynb 6
class Entity(BaseModel):
    """
    Immutable view of a JSON-LD resource with fixes for the identified issues.
    
    Parameters
    ----------
    id      : Optional IRI (string).  If omitted a blank node is used.
    vocab   : list of registry prefixes that define the entity's context.
              The order matters: first prefix is considered primary.
    content : dict with user-supplied properties (e.g. {"name":"Ada"}).
    meta    : optional metadata (timestamps, provenance).
    """

    id:      Optional[str]          = Field(default=None, alias="@id")
    vocab:   List[str]              = Field(min_items=1)
    content: Dict[str, Any]         = Field(default_factory=dict)
    meta:    Dict[str, Any] | None  = None
    created: datetime               = Field(default_factory=datetime.utcnow)

    model_config = dict(frozen=True, populate_by_name=True)
    
    # ------------------------------------------------------------------
    # validators
    # ------------------------------------------------------------------
    @model_validator(mode="after")
    def _attach_context(cls, v):
        # Compose once and store in private attr _ctx
        ctx = composer.compose(v.vocab)["@context"]
        object.__setattr__(v, "_ctx", ctx)
        # Make a deep copy of content to ensure immutability
        immutable_content = deepcopy(v.content)
        object.__setattr__(v, "content", immutable_content)
        return v

    # ------------------------------------------------------------------
    # public helpers
    # ------------------------------------------------------------------
    @property
    def as_json(self) -> Dict[str, Any]:
        "Full JSON-LD dict with `@context`"
        base = {"@context": self._ctx}
        if self.id:
            base["@id"] = self.id
        base.update(self.content)
        return base  # Return the constructed JSON-LD object

    # ------------------------------------------------------------------
    # expensive calculation cached per-instance
    # ------------------------------------------------------------------
    @cached_property
    def normalized(self) -> str:
        "URDNA2015 N-Quads representation."
        return _proc.normalize(self.as_json)

    # convenience ------------------------------------------------------
    @property
    def sha256(self) -> str:
        "Digest over `normalized` property."
        return hashlib.sha256(self.normalized.encode()).hexdigest()

    # Override __getattribute__ to return copies of mutable objects
    def __getattribute__(self, name):
        attr = super().__getattribute__(name)
        if name == 'content' and isinstance(attr, dict):
            return deepcopy(attr)
        return attr
