"""Tools and infrastructure for building agentic systems leveraging Cogitarelink's vocabulary management"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../09_cli.ipynb.

# %% auto 0
__all__ = ['log', 'ToolRegistry', 'AgentContext', 'Agent', 'cli_main']

# %% ../../09_cli.ipynb 3
__all__ = ['Agent', 'AgentContext', 'ToolRegistry', 'cli_main']

# %% ../../09_cli.ipynb 5
from ..core.debug import get_logger
from ..core.cache import InMemoryCache, DiskCache

log = get_logger("cli")
_tool_cache = InMemoryCache(maxsize=128)

# %% ../../09_cli.ipynb 7
class ToolRegistry:
    """Registry for agent tools with metadata and validation."""
    
    def __init__(self):
        self.tools: Dict[str, Dict[str, Any]] = {}
        
    def register(self, name: str = None, description: str = None):
        """Decorator to register a function as a tool."""
        def decorator(func):
            tool_name = name or func.__name__
            tool_desc = description or func.__doc__
            
            self.tools[tool_name] = {
                "name": tool_name,
                "description": tool_desc,
                "function": func,
                "signature": getattr(func, "__annotations__", {})
            }
            return func
        return decorator
    
    def get(self, name: str) -> Dict[str, Any]:
        """Get a tool by name."""
        if name not in self.tools:
            raise ValueError(f"Tool '{name}' not found in registry")
        return self.tools[name]
    
    def list_tools(self) -> List[Dict[str, Any]]:
        """List all available tools with metadata."""
        return [
            {
                "name": name,
                "description": tool["description"],
                "signature": {k: str(v) for k, v in tool["signature"].items() if k != "return"}
            }
            for name, tool in self.tools.items()
        ]
    
    def execute(self, name: str, **kwargs) -> Any:
        """Execute a tool by name with the given arguments."""
        tool = self.get(name)
        func = tool["function"]
        return func(**kwargs)

# %% ../../09_cli.ipynb 12
class AgentContext:
    """Context for agent execution with state management."""
    
    def __init__(self, agent, disk_cache: bool = True):
        self.agent = agent
        self.memory: Dict[str, Any] = {}
        self.history: List[Dict[str, Any]] = []
        
        # Set up caching
        if disk_cache:
            cache_dir = Path.home() / ".cogitarelink" / "agent_cache"
            cache_dir.mkdir(parents=True, exist_ok=True)
            self.cache = DiskCache(str(cache_dir))
        else:
            self.cache = InMemoryCache(maxsize=256)
    
    def remember(self, key: str, value: Any):
        """Store a value in agent memory."""
        self.memory[key] = value
        return value
    
    def recall(self, key: str, default: Any = None) -> Any:
        """Retrieve a value from agent memory."""
        return self.memory.get(key, default)
    
    def log_action(self, tool: str, inputs: Dict[str, Any], result: Any):
        """Log an action to the history."""
        entry = {
            "timestamp": __import__("time").time(),
            "tool": tool,
            "inputs": inputs,
            "success": result is not None and not isinstance(result, Exception),
            "result_type": type(result).__name__
        }
        self.history.append(entry)
        return entry
    
    @_tool_cache.memoize("agent")
    def cached_execute(self, tool: str, **kwargs) -> Any:
        """Execute a tool with caching."""
        return self.agent.tools.execute(tool, **kwargs)

# %% ../../09_cli.ipynb 14
class Agent:
    """Base agent class for CogitareLink."""
    
    def __init__(self, name: str = "cogitarelink-agent"):
        self.name = name
        self.tools = ToolRegistry()
        self.context = AgentContext(self)
        self._register_core_tools()
    
    def _register_core_tools(self):
        """Register core tools available to all agents."""
        
        @self.tools.register(name="get_version", 
                           description="Get the CogitareLink version")
        def get_version() -> str:
            try:
                return importlib.metadata.version("cogitarelink")
            except importlib.metadata.PackageNotFoundError:
                return "development"
        
        @self.tools.register(name="list_tools",
                           description="List all available tools")
        def list_tools() -> List[Dict[str, Any]]:
            return self.tools.list_tools()
        
        @self.tools.register(name="get_agent_memory",
                           description="Get all items in agent memory")
        def get_agent_memory() -> Dict[str, Any]:
            return self.context.memory.copy()
    
    def register_tool(self, func: Callable, name: str = None, description: str = None):
        """Register a new tool with the agent."""
        return self.tools.register(name, description)(func)
    
    def run_tool(self, name: str, **kwargs) -> Any:
        """Run a tool and log the action."""
        try:
            result = self.tools.execute(name, **kwargs)
            self.context.log_action(name, kwargs, result)
            return result
        except Exception as e:
            self.context.log_action(name, kwargs, e)
            raise
    
    def run_cached_tool(self, name: str, **kwargs) -> Any:
        """Run a tool with caching and log the action."""
        try:
            result = self.context.cached_execute(name, **kwargs)
            self.context.log_action(name, kwargs, result)
            return result
        except Exception as e:
            self.context.log_action(name, kwargs, e)
            raise

# %% ../../09_cli.ipynb 20
def cli_main():
    """Main entry point for the CLI."""
    # Skip argument parsing when run inside a notebook
    in_notebook = 'ipykernel' in sys.modules
    
    if in_notebook:
        # Default behavior for notebook - create an agent and return it
        return Agent()
    
    # Normal CLI operation with argument parsing
    parser = argparse.ArgumentParser(description="CogitareLink CLI")
    parser.add_argument('--version', action='store_true', help='Show version and exit')
    parser.add_argument('--list-tools', action='store_true', help='List available tools')
    parser.add_argument('--run-tool', metavar='TOOL', help='Run a specific tool')
    parser.add_argument('--args', metavar='JSON', help='JSON arguments for tool')
    
    args = parser.parse_args()
    
    # Create default agent
    agent = Agent()
    
    if args.version:
        print(f"CogitareLink version: {agent.run_tool('get_version')}")
        return 0
        
    if args.list_tools:
        tools = agent.run_tool('list_tools')
        print(json.dumps(tools, indent=2))
        return 0
        
    if args.run_tool:
        tool_name = args.run_tool
        tool_args = {}
        
        if args.args:
            try:
                tool_args = json.loads(args.args)
            except json.JSONDecodeError as e:
                print(f"Error parsing arguments: {e}", file=sys.stderr)
                return 1
        
        try:
            result = agent.run_tool(tool_name, **tool_args)
            print(json.dumps(result, indent=2, default=str))
            return 0
        except Exception as e:
            print(f"Error running tool {tool_name}: {e}", file=sys.stderr)
            return 1
    
    # Default behavior - show help
    parser.print_help()
    return 0

# %% ../../09_cli.ipynb 21
# Entry point if script is run directly
if __name__ == "__main__":
    sys.exit(cli_main())
