In [ ]:
# Uninstall the ccogitarelink package
# ! pip uninstall cogitarelink -y

In [ ]:
## Install fresh from the GitHub Package
# ! pip install --no-cache-dir -U git+https://github.com/la3d/cogitarelink.git

In [ ]:
from cogitarelink.core import *
from cogitarelink.vocabulary import *
from cogitarelink.navigation import *
from cogitarelink.dataset import *
from cogitarelink.utils import *
import json

**AI Prompt**

Hi solveit! I am Chuck, and I am working with you today! I'm an experienced Python coder, experienced with semantic web technologies like OWL,RDF and SPARQL, and I enjoy learning new things. When writing code for me, please follow fast.ai coding style: avoid comments; place single line if/loop/etc constructs on the same line; use concise variable names where appropriate. Follow the style you will see in my messages, as we work on this dialogue together. I am developing this cogitarelink in nbdev notebooks following an exploratory and literate programming style using step-by-step testing. I am the developer of cogitarelink and have installed the package from GitHub. I implimented the core functions you see in your context in another dialog and now want to test and extend the framework. Are you ready?

**AI Response**

Hi Chuck! Great to meet you. I'm ready to help you test and extend the cogitarelink framework. I see you're working with semantic web technologies and using a literate programming approach with nbdev.

I'll follow the fast.ai coding style you prefer - concise variable names, single-line constructs where appropriate, and minimal comments. I notice you've already imported the core modules from cogitarelink and other supporting libraries.

Before we dive in, would you like to start by testing some of the existing functionality, or do you have specific extensions in mind that you'd like to implement first?

In [ ]:
core_py = load_module_source("core")

Loaded core from /app/data/.local/lib/python3.11/site-packages/cogitarelink/core.py (53729 characters)


In [ ]:
vocab_py = load_module_source("vocabulary")

Loaded vocabulary from /app/data/.local/lib/python3.11/site-packages/cogitarelink/vocabulary.py (69997 characters)


**AI Prompt**

Ok. Here is the source code to $`core_py` and $`vocab_py`

**AI Response**

I see you've loaded the source code for both the `core.py` and `vocabulary.py` modules from the cogitarelink package. These modules form the foundation of the framework's ability to work with linked data in JSON-LD format.

The `core.py` module provides the core `LinkedDataKnowledge` class which handles:
- Storage and organization of JSON-LD data
- Entity finding and retrieval
- Named graph management
- Structured data representation
- Knowledge visualization

The `vocabulary.py` module extends this with capabilities for:
- Fetching external vocabularies from various sources
- Handling Wikidata entities
- Working with Schema.org
- Managing JSON-LD contexts
- Processing external references

Would you like to start testing some specific functionality, build some extensions, or would you like me to explain any particular part of the codebase in more detail?

The structure of cogitarelink is built to be "LLM-navigable" where you can:

1. First examine an index/overview of what's in the knowledge base
2. Check if any of those items are relevant to the current question
3. If not, perform a reflective process to identify knowledge gaps
4. Retrieve additional entities to fill those gaps

This creates a workflow similar to how humans navigate information:
- "What do I already know about this topic?"
- "Is what I know sufficient to answer this question?"
- "If not, what additional information should I look for?"

The prefixed properties (wdt:) and simplified labels make it easier for you to understand the semantics without needing to resolve full URIs, while the graph structure maintains all the rich connections between entities.

Would it be helpful to create a function that generates this kind of "knowledge index" from the current state of the knowledge base? This could provide you with a quick overview of available entities, their types, and key relationships to help you decide what to explore further.

Based on what we've learned about working with linked data and JSON-LD, here's how an LLM-based agent should build its memory while exploring the linked data cloud:

## Building an LLM Agent's Memory in the Linked Data Cloud

### 1. Layered Memory Structure

The agent should maintain a multi-layered memory structure:

- **Working Memory**: The current focus entities and their immediate relationships
- **Episodic Memory**: The path of exploration and discoveries made
- **Semantic Memory**: Structured knowledge organized by domain and concept

This mirrors how the `LinkedDataKnowledge` class uses named graphs, the main graph, and included entities.

### 2. Knowledge Acquisition Process

When exploring linked data, the agent should:

1. **Start with an Entry Point**: Begin with a known entity or concept URI
2. **Fetch and Simplify**: Retrieve the entity data and convert it to a simplified representation
3. **Extract Key Information**: Use the `extract_value` function to get essential properties
4. **Organize by Domain**: Group related properties using scoped contexts
5. **Discover Connections**: Identify links to related entities
6. **Follow Selectively**: Choose which links to follow based on relevance to the task

### 3. Memory Organization Techniques

The agent should leverage JSON-LD 1.1 features to organize memory:

- **Use Resource-Centric Views**: Place the main entity of interest at the root with related entities in `@included`
- **Apply Scoped Contexts**: Create domain-specific views of properties
- **Utilize Containers**: Use appropriate containers for different types of multi-valued properties
- **Maintain Named Graphs**: Store different knowledge domains in separate named graphs

### 4. Practical Implementation Steps

1. **Initial Discovery**:
   - When encountering a new URI, fetch its representation
   - Add it to the knowledge base using `fetch_vocabulary`
   - Generate a knowledge index to understand what's available

2. **Strategic Exploration**:
   - Use `find_entity_across_graphs` to locate related entities
   - Use `get_entity_description(simplified=True)` to get concise representations
   - Apply `extract_value` to access specific property values

3. **Memory Consolidation**:
   - Periodically organize knowledge using `structure_with_containers`
   - Create domain-specific views with `create_scoped_context`
   - Use `use_included` to create entity-centric views of related information

4. **Reference Management**:
   - When encountering external references, use `fetch_external_reference`
   - Connect references back to source entities
   - Maintain provenance information about where knowledge came from

### 5. Navigation Strategies

The agent should employ these strategies for effective navigation:

- **Breadth vs. Depth**: Balance between exploring many related entities superficially or following specific paths deeply
- **Interest-Based Prioritization**: Prioritize following links related to the current task or question
- **Vocabulary Discovery**: When encountering new vocabularies, fetch their definitions first
- **Property Understanding**: Look up the meaning of unfamiliar properties before interpreting their values

### 6. Real-World Example

For instance, if exploring AI research:

1. Start with `http://www.wikidata.org/entity/Q11660` (Artificial Intelligence)
2. Discover it has a Getty AAT ID (`wdt:P1014` property)
3. Fetch that external reference to get cultural/historical context
4. Find related concepts like Machine Learning (`Q2539`)
5. Organize these in a "Computer Science" named graph
6. Create a scoped context for AI-related properties
7. Use containers to organize different AI applications by domain

This approach allows the agent to build a rich, interconnected knowledge structure that preserves the semantic relationships of the linked data while making it accessible for LLM reasoning.

Would you like me to elaborate on any specific aspect of this memory-building process?

**AI Prompt**

I would like to explore the use of GS1 vocabularies in addition to Schema.org. We've got some tests in vocabulary.py that show how to access and navigate to schema.org. I don't know if this will work for GS1, so I'd like to explore this agentive approach to exploring GS1 vocabularies, make sure we can load them, and then use Claude chat to maybe understand how an LLM might interpret these vocabularies.

**AI Response**

That's a great direction to explore! GS1 vocabularies are important for supply chain and product identification standards, which would be a valuable addition to the framework alongside Schema.org.

Let's start by exploring how we might access and work with GS1 vocabularies. GS1 provides several vocabularies and standards, including:

1. The GS1 Web Vocabulary
2. GDSN (Global Data Synchronization Network) standards
3. EPCIS (Electronic Product Code Information Services)

First, let's check if we can access the GS1 Web Vocabulary using our existing vocabulary fetching mechanism. Let's try loading the main GS1 vocabulary:

```python
# Create a knowledge base instance
kb = LinkedDataKnowledge()

# Try to fetch the GS1 Web Vocabulary
# Let's enable debug to see what's happening
try:
    kb.fetch_vocabulary("https://www.gs1.org/voc/", debug=True)
except Exception as e:
    print(f"Error: {e}")
```

Would you like to run this code to see if our existing mechanisms can handle GS1 vocabularies? Then we can analyze the results and determine next steps.

In [ ]:
# Create a knowledge base instance
kb = LinkedDataKnowledge()

# Try to fetch the GS1 Web Vocabulary
# Let's enable debug to see what's happening
try:
    kb.fetch_vocabulary("https://www.gs1.org/voc/", debug=True)
except Exception as e:
    print(f"Error: {e}")

Processing as standard vocabulary: https://www.gs1.org/voc/
Fetching standard vocabulary: https://www.gs1.org/voc/
Response status: 200
Response headers: {'date': 'Mon, 17 Mar 2025 15:53:48 GMT', 'content-type': 'text/html; charset=utf-8', 'content-length': '16072', 'connection': 'keep-alive', 'last-modified': 'Thu, 13 Mar 2025 12:24:51 GMT', 'etag': '"3ec8-6303868928ac0"', 'access-control-allow-origin': '*', 'x-location': '/', 'x-azure-ref': '20250317T155348Z-1686cc569bcndhmphC1DFWbh1c00000007200000000065ns', 'x-cache': 'CONFIG_NOCACHE', 'accept-ranges': 'bytes'}
Response is HTML - checking for embedded structured data
Error parsing RDFa: No plugin registered for (rdfa, <class 'rdflib.parser.Parser'>)
Could not determine format for https://www.gs1.org/voc/


**AI Prompt**

Looking for the machine-interpretable data for this URI, I went in and browsed it via HTTP. Could you have a look at the HTTP version of this and see what you think?

**AI Response**

I see that our initial attempt to fetch the GS1 vocabulary encountered some issues. The response was HTML content, and we had trouble parsing any embedded RDFa. Let's investigate the HTTP version of the GS1 vocabulary to better understand what's available.

Let's make a simple HTTP request to examine the headers and content:

```python
import httpx

# Make a GET request to the GS1 vocabulary URI
response = httpx.get("https://www.gs1.org/voc/", headers={"Accept": "text/turtle,application/rdf+xml,application/ld+json"})

# Print response info
print(f"Status code: {response.status_code}")
print(f"Content type: {response.headers.get('Content-Type')}")
print(f"Available headers: {dict(response.headers)}")

# Preview the content
print("\nContent preview (first 500 chars):")
print(response.text[:500])
```

This will help us determine what format the GS1 vocabulary is available in and if there are any content negotiation options we should be using. After seeing this, we can decide on the best approach to access the machine-readable version of the vocabulary.

In [ ]:
import httpx

# Make a GET request to the GS1 vocabulary URI
response = httpx.get("https://www.gs1.org/voc/", headers={"Accept": "text/turtle,application/rdf+xml,application/ld+json"})

# Print response info
print(f"Status code: {response.status_code}")
print(f"Content type: {response.headers.get('Content-Type')}")
print(f"Available headers: {dict(response.headers)}")

# Preview the content
print("\nContent preview (first 500 chars):")
print(response.text[:500])

Status code: 301
Content type: text/html
Available headers: {'date': 'Mon, 17 Mar 2025 16:02:30 GMT', 'content-type': 'text/html', 'content-length': '0', 'connection': 'keep-alive', 'location': 'https://ref.gs1.org/voc/', 'x-azure-ref': '20250317T160230Z-1686cc569bcqhvt2hC1DFWzym4000000016g00000000gx9h', 'x-cache': 'CONFIG_NOCACHE'}

Content preview (first 500 chars):



**AI Prompt**

So the response text was empty. Is this correct?

**AI Response**

Yes, you're right. The response text is empty because we received a 301 (Moved Permanently) status code. The server is redirecting us from `https://www.gs1.org/voc/` to `https://ref.gs1.org/voc/` as indicated by the `location` header in the response.

Let's follow this redirect and try again with the new URL:

```python
import httpx

# Make a GET request to the redirected GS1 vocabulary URI
response = httpx.get("https://ref.gs1.org/voc/", 
                    headers={"Accept": "text/turtle,application/rdf+xml,application/ld+json"},
                    follow_redirects=True)  # Automatically follow redirects

# Print response info
print(f"Status code: {response.status_code}")
print(f"Content type: {response.headers.get('Content-Type')}")
print(f"Available headers: {dict(response.headers)}")

# Preview the content
print("\nContent preview (first 500 chars):")
print(response.text[:500])
```

This should give us the actual content from the redirected URL, which should help us understand what format the GS1 vocabulary is available in.

In [ ]:
import httpx

# Make a GET request to the redirected GS1 vocabulary URI
response = httpx.get("https://ref.gs1.org/voc/", 
                    headers={"Accept": "text/turtle,application/rdf+xml,application/ld+json"},
                    follow_redirects=True)  # Automatically follow redirects

# Print response info
print(f"Status code: {response.status_code}")
print(f"Content type: {response.headers.get('Content-Type')}")
print(f"Available headers: {dict(response.headers)}")

# Preview the content
print("\nContent preview (first 500 chars):")
print(response.text[:500])

Status code: 200
Content type: text/html; charset=utf-8
Available headers: {'date': 'Mon, 17 Mar 2025 16:03:37 GMT', 'content-type': 'text/html; charset=utf-8', 'content-length': '16072', 'connection': 'keep-alive', 'last-modified': 'Thu, 13 Mar 2025 12:24:51 GMT', 'etag': '"3ec8-6303868928ac0"', 'access-control-allow-origin': '*', 'x-location': '/', 'x-azure-ref': '20250317T160337Z-185d6f64ccblm4fqhC1DFW9e0n000000094g000000001ccu', 'x-cache': 'CONFIG_NOCACHE', 'accept-ranges': 'bytes'}

Content preview (first 500 chars):
<!DOCTYPE html>
<html lang="en">
	<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script>
			const ontologyJSONLDcompact = "data/gs1Voc-compact.jsonld"
			const ontologyJSONLD = "data/gs1Voc.jsonld"
			const ontologyTurtle = "data/gs1Voc.ttl"
			const changeLogJSON = "data/changeLog.json"
			const prefLang = "en"
		</script>
      <link href="https://ref.gs1.org/styles/base.css" rel="stylesheet">
    

**AI Prompt**

Okay, so our issue is not following the redirects.

**AI Response**

You're right! We've found a key issue. The response is HTML, but interestingly, I notice something important in the HTML content - there are references to the actual machine-readable vocabulary files:

```javascript
const ontologyJSONLDcompact = "data/gs1Voc-compact.jsonld"
const ontologyJSONLD = "data/gs1Voc.jsonld"
const ontologyTurtle = "data/gs1Voc.ttl"
```

This suggests that the GS1 vocabulary is available in both JSON-LD and Turtle formats, but they're not directly accessible through content negotiation at the base URL. Instead, they're served as static files.

Let's try to access one of these files directly:

```python
import httpx

# Try to access the JSON-LD version
jsonld_url = "https://ref.gs1.org/voc/data/gs1Voc.jsonld"
response = httpx.get(jsonld_url, follow_redirects=True)

# Print response info
print(f"Status code: {response.status_code}")
print(f"Content type: {response.headers.get('Content-Type')}")

# Preview the content
print("\nContent preview (first 500 chars):")
print(response.text[:500] if response.status_code == 200 else "No content")
```

Let's see if we can directly access the machine-readable vocabulary files.

**AI Prompt**

Have a look through the examples for Wikidata, which has a unique set of patterns in that we have to get the Turtle format, not the JSON-LD, because we want to build our own JSON-LD structure rather than use a wiki-based data dump. Have a look through that code just so you can see what's going on there. Don't write any code yet. Just analyze what the issues might be with the code you created.

**AI Response**

Looking at the Wikidata handling in the vocabulary.py code, I can see several interesting patterns:

The `_fetch_wikidata_entity` method has some distinctive approaches:

1. It specifically requests Turtle format (`entity_id.ttl`) rather than JSON-LD
2. It uses a "flavor" parameter to control the data completeness (simple, full, dump)
3. It parses the Turtle into an RDF graph and then serializes to JSON-LD
4. It performs post-processing on the JSON-LD to make it more usable:
   - Simplifies labels and descriptions
   - Prefixes Wikidata properties (wdt:, wdtn:)
   - Ensures the canonical entity ID

The `_process_wikidata_entity` method does significant transformation:
- It extracts English labels/descriptions when available
- It creates simplified property names with prefixes
- It handles cases where the main entity might not be found by URI

Analyzing potential issues with my proposed agentic approach:

1. **Format-Specific Processing**: My approach doesn't account for cases where we specifically want one format (Turtle) but need to convert it to another (JSON-LD) with custom processing.

2. **Domain-Specific Knowledge**: The Wikidata code has embedded knowledge about Wikidata's structure (property patterns, label formats) that would be hard for a generic system to discover.

3. **Prioritization Logic**: My prioritization might choose JSON-LD over Turtle, which would be wrong for Wikidata where we specifically want Turtle for better control.

4. **Post-Processing Needs**: My approach doesn't account for the significant post-processing needed for some vocabularies (like extracting English labels or prefixing properties).

5. **URL Construction**: For Wikidata, the URL is constructed in a specific way (adding .ttl and flavor parameters) that a generic system might not discover.

6. **Entity Identification**: The Wikidata code has specific logic for finding the main entity, which might be missed in a generic approach.

7. **Semantic Understanding**: The code shows a deep understanding of Wikidata's semantics (distinguishing properties vs entities, understanding label patterns) that would be challenging for a generic system.

This suggests that while an agentic approach is valuable, we might still need some domain-specific handlers for well-known vocabulary sources like Wikidata, or a way to encode this domain knowledge into the system.

## Software 2.0 Approach for LOD Cloud Surfer

### 1. Resource Discovery via LLM Analysis

Instead of hardcoding patterns for resource extraction, we could use an LLM to analyze HTML and identify potential resources:

```python
def discover_resources_via_llm(html, base_url):
    """Use an LLM to discover resources in HTML content"""
    system_prompt = """
    You are an expert in semantic web technologies. Analyze the HTML content and identify:
    1. Links to machine-readable data formats (JSON-LD, Turtle, RDF/XML)
    2. Embedded structured data
    3. JavaScript variables containing references to data files
    
    Return ONLY a JSON object with the following structure:
    {
      "resources": [
        {"type": "jsonld_file", "url": "full_url", "confidence": 0.9},
        {"type": "turtle_file", "url": "full_url", "confidence": 0.8}
      ]
    }
    """
    
    user_prompt = f"HTML from {base_url}:\n\n{html[:5000]}"
    
    # Call LLM and parse response
    resources = call_llm(system_prompt, user_prompt)
    return resources
```

### 2. Prompt Chaining for Resource Processing

We can use prompt chaining to handle the processing flow:

```python
def process_resource_chain(url):
    """Process a resource using a chain of prompts"""
    # Step 1: Initial analysis
    analysis_prompt = f"""
    Analyze the resource at {url} and determine:
    1. What type of resource is this?
    2. What format is it in?
    3. What is the best way to process it?
    
    Return your analysis as JSON.
    """
    analysis = call_llm(analysis_prompt)
    
    # Step 2: Processing strategy
    strategy_prompt = f"""
    Based on this analysis: {analysis}
    
    Outline a step-by-step strategy to extract structured data from this resource.
    Return your strategy as JSON.
    """
    strategy = call_llm(strategy_prompt)
    
    # Step 3: Execute strategy (this could involve code execution or further LLM calls)
    # ...
    
    return result
```

### 3. Multi-Agent Approach

We could implement a multi-agent system where different agents handle different aspects:

1. **Scout Agent**: Discovers resources from a starting URL
2. **Format Agent**: Determines the best format and processing approach
3. **Extraction Agent**: Extracts structured data from the resource
4. **Transformation Agent**: Converts to unified JSON-LD format
5. **Coordinator Agent**: Orchestrates the workflow and makes decisions

### 4. Hybrid Approach for Domain-Specific Processing

For domain-specific processing (like Wikidata), we could use a hybrid approach:

```python
def process_entity(entity_id, domain):
    """Process an entity using domain-specific knowledge"""
    # Get domain-specific knowledge via LLM
    domain_knowledge = get_domain_knowledge(domain)
    
    # Ask LLM how to process this entity based on domain knowledge
    processing_instructions = call_llm(f"""
    Given this domain knowledge about {domain}:
    {domain_knowledge}
    
    How should I process entity {entity_id}? 
    Provide specific instructions including:
    1. What URL format to use
    2. What HTTP headers to include
    3. How to process the response
    4. What post-processing steps to apply
    
    Return your instructions as a JSON object.
    """)
    
    # Execute the instructions (could be code or further LLM calls)
    # ...
    
    return processed_entity
```

### 5. Knowledge Accumulation

The system could learn from experience:

```python
class PatternMemory:
    """Stores successful patterns for different domains"""
    def __init__(self):
        self.patterns = {}
        
    def remember_pattern(self, domain, pattern, success_rate):
        """Remember a successful pattern"""
        if domain not in self.patterns:
            self.patterns[domain] = []
        
        self.patterns[domain].append({
            "pattern": pattern,
            "success_rate": success_rate,
            "timestamp": datetime.datetime.now().isoformat()
        })
        
    def suggest_patterns(self, domain):
        """Suggest patterns for a domain"""
        # Direct match
        if domain in self.patterns:
            return sorted(self.patterns[domain], 
                         key=lambda x: x['success_rate'], 
                         reverse=True)
        
        # Ask LLM to suggest patterns based on similar domains
        return call_llm(f"""
        Based on these known patterns:
        {self.patterns}
        
        What patterns might work for domain: {domain}?
        Return your suggestions as a JSON array.
        """)
```

### 6. Reflective Processing

The system could reflect on its own performance:

```python
def reflect_on_process(url, steps_taken, result):
    """Reflect on the processing steps and improve"""
    reflection = call_llm(f"""
    I attempted to process {url} with these steps:
    {steps_taken}
    
    The result was: {result}
    
    Please analyze what went well, what could be improved, and suggest 
    specific changes to make the process more robust for similar URLs in the future.
    """)
    
    # Update the system based on reflection
    update_system_from_reflection(reflection)
    
    return reflection
```

## What Should Stay as Software 1.0

Some parts are better kept as explicit code:

1. **Core HTTP Requests**: The actual network requests
2. **RDF Parsing**: Using established libraries for parsing RDF formats
3. **JSON-LD Manipulation**: Low-level JSON-LD operations
4. **Data Storage**: Storing and retrieving the processed data

## Practical Implementation

A practical implementation would likely use:

1. **LangChain or similar**: For building the agent workflows
2. **Function Calling**: Having the LLM generate structured outputs
3. **Tool Use**: Letting the LLM call specific tools as needed
4. **Memory Systems**: Storing intermediate results and learned patterns

Would you like me to expand on any particular aspect of this Software 2.0 approach?

In [ ]:
models

['claude-3-opus-20240229',
 'claude-3-7-sonnet-20250219',
 'claude-3-5-sonnet-20241022',
 'claude-3-haiku-20240307',
 'claude-3-5-haiku-20241022']

In [ ]:
from claudette import Chat, models

# Define a very simple tool that just adds two numbers
def add_numbers(a: int, b: int) -> str:
    """Add two numbers together.
    
    Args:
        a: First number
        b: Second number
        
    Returns:
        A string containing the result
    """
    result = a + b
    return f"The sum of {a} and {b} is {result}"

# Define another simple tool that processes text
def count_words(text: str) -> str:
    """Count words in a text.
    
    Args:
        text: The text to analyze
        
    Returns:
        A string with word count information
    """
    words = text.split()
    return f"The text contains {len(words)} words"

# Set up a Claude chat with our simple tools
model = models[2]  # Use Claude 3.5 Sonnet
chat = Chat(model, tools=[add_numbers, count_words])

# Test the tools
result = chat.toolloop("""
I need to add two numbers: 42 and 17.
Then I need to count the words in this sentence: "The quick brown fox jumps over the lazy dog."
""")

print(result)

Message(id='msg_01Gb26pp5ByHioEcy72SV1FZ', content=[TextBlock(citations=None, text='I\'ve completed both tasks:\n1. The sum of 42 and 17 is 59\n2. The sentence "The quick brown fox jumps over the lazy dog." contains 9 words', type='text')], model='claude-3-5-sonnet-20241022', role='assistant', stop_reason='end_turn', stop_sequence=None, type='message', usage=In: 811; Out: 48; Cache create: 0; Cache read: 0; Total: 859)


In [ ]:
#| export
def fetch_url(url: str, follow_redirects: bool = True, accept_header: str = None) -> str:
    """Fetch content from a URL with optional content negotiation.
    
    Args:
        url: The URL to fetch
        follow_redirects: Whether to follow redirects
        accept_header: Content type to request, or None for default
        
    Returns:
        A string with information about the fetched content
    """
    headers = {}
    if accept_header:
        headers["Accept"] = accept_header
    
    try:
        response = httpx.get(url, headers=headers, follow_redirects=follow_redirects)
        
        # Format as a string response
        result = [
            f"# Fetched content from {url}",
            f"",
            f"- **Status code**: {response.status_code}",
            f"- **Content type**: {response.headers.get('Content-Type', '')}",
            f"- **Content length**: {len(response.text)} characters",
            f"",
            f"## Content preview (first 500 chars):",
            f"```",
            response.text[:500] + ("..." if len(response.text) > 500 else ""),
            f"```"
        ]
        
        # Store the full content in a global variable that can be accessed by other functions
        global last_fetched_content
        last_fetched_content = response.text
        global last_fetched_url
        last_fetched_url = url
        
        return "\n".join(result)
    except Exception as e:
        return f"Error fetching URL: {e}"

In [ ]:
#| export
def parse_html(base_url: str = None, html: str = None) -> str:
    """Parse HTML and extract potential semantic web resources.
    
    Args:
        base_url: Base URL for resolving relative links, or None to use last fetched URL
        html: HTML content to parse, or None to use last fetched content
        
    Returns:
        A string describing the extracted resources
    """
    # Use global variables if parameters are not provided
    global last_fetched_content, last_fetched_url
    
    if html is None:
        if 'last_fetched_content' not in globals():
            return "Error: No HTML content provided and no previous content available"
        html = last_fetched_content
    
    if base_url is None:
        if 'last_fetched_url' not in globals():
            return "Error: No base URL provided and no previous URL available"
        base_url = last_fetched_url
    
    soup = bs(html, 'html.parser')
    
    # Store extracted resources for other functions to use
    global extracted_resources
    extracted_resources = {
        "links": [],
        "embedded_jsonld": [],
        "script_references": []
    }
    
    # Extract link tags
    for link in soup.find_all('link'):
        href = link.get('href')
        rel = link.get('rel', [])
        if isinstance(rel, list):
            rel = ' '.join(rel)
        type_attr = link.get('type', '')
        
        if href:
            extracted_resources["links"].append({
                "href": urljoin(base_url, href),
                "rel": rel,
                "type": type_attr
            })
    
    # Extract JSON-LD script tags
    jsonld_count = 0
    for script in soup.select('script[type="application/ld+json"]'):
        try:
            if script.string:
                extracted_resources["embedded_jsonld"].append(json.loads(script.string))
                jsonld_count += 1
        except:
            pass
    
    # Extract script references to data files
    for script in soup.find_all('script'):
        if script.string:
            # Look for patterns like const ontologyJSONLD = "data/gs1Voc.jsonld"
            jsonld_matches = re.findall(r'const\s+(\w+)\s*=\s*"([^"]+\.jsonld)"', script.string)
            turtle_matches = re.findall(r'const\s+(\w+)\s*=\s*"([^"]+\.ttl)"', script.string)
            
            for name, path in jsonld_matches + turtle_matches:
                extracted_resources["script_references"].append({
                    "name": name,
                    "path": path,
                    "full_url": urljoin(base_url, path)
                })
    
    # Format as a string
    result = [f"# Resources extracted from {base_url}"]
    
    # Link tags
    result.append(f"\n## Link Tags ({len(extracted_resources['links'])})")
    for link in extracted_resources['links'][:5]:  # Show first 5
        result.append(f"- {link['href']} (rel: {link['rel']}, type: {link['type']})")
    if len(extracted_resources['links']) > 5:
        result.append(f"- ... and {len(extracted_resources['links']) - 5} more links")
    
    # JSON-LD
    result.append(f"\n## Embedded JSON-LD ({jsonld_count} blocks)")
    if jsonld_count > 0:
        result.append("- Found embedded JSON-LD data")
    
    # Script references
    result.append(f"\n## Script References ({len(extracted_resources['script_references'])})")
    for ref in extracted_resources['script_references']:
        result.append(f"- {ref['name']}: {ref['full_url']}")
    
    return "\n".join(result)

In [ ]:
#| export
def fetch_resource(url: str, resource_type: str = None) -> str:
    """Fetch a specific resource identified during HTML parsing.
    
    Args:
        url: URL of the resource to fetch
        resource_type: Type of resource (jsonld, turtle, etc.), or None to auto-detect
        
    Returns:
        A string with information about the fetched resource
    """
    accept_headers = {
        "jsonld": "application/ld+json",
        "turtle": "text/turtle",
        "rdf": "application/rdf+xml",
        "n3": "text/n3",
        "ntriples": "application/n-triples"
    }
    
    headers = {}
    if resource_type and resource_type in accept_headers:
        headers["Accept"] = accept_headers[resource_type]
    
    try:
        response = httpx.get(url, headers=headers, follow_redirects=True)
        
        # Store the content for other functions to use
        global resource_content, resource_url, resource_content_type
        resource_content = response.text
        resource_url = url
        resource_content_type = response.headers.get('Content-Type', '')
        
        # Determine the likely format based on URL and content type
        format_guess = "unknown"
        if url.endswith('.jsonld') or 'json' in resource_content_type:
            format_guess = "jsonld"
        elif url.endswith('.ttl') or 'turtle' in resource_content_type:
            format_guess = "turtle"
        elif url.endswith('.rdf') or 'rdf+xml' in resource_content_type:
            format_guess = "rdf"
        
        # Format as a string response
        result = [
            f"# Fetched resource from {url}",
            f"",
            f"- **Status code**: {response.status_code}",
            f"- **Content type**: {resource_content_type}",
            f"- **Content length**: {len(resource_content)} characters",
            f"- **Likely format**: {format_guess}",
            f"",
            f"## Content preview (first 500 chars):",
            f"```",
            resource_content[:500] + ("..." if len(resource_content) > 500 else ""),
            f"```"
        ]
        
        return "\n".join(result)
    except Exception as e:
        return f"Error fetching resource: {e}"

In [ ]:
#| export
def convert_rdf_to_jsonld(format: str) -> str:
    """Convert RDF content to JSON-LD.
    
    Args:
        format: Format of the RDF content ('turtle', 'xml', 'n3', etc.)
        
    Returns:
        A string with the JSON-LD conversion result
    """
    global resource_content
    
    if 'resource_content' not in globals():
        return "Error: No resource content available to convert"
    
    try:
        g = Graph()
        g.parse(data=resource_content, format=format)
        jsonld_str = g.serialize(format='json-ld')
        
        # Store the JSON-LD for other functions
        global jsonld_content
        jsonld_content = jsonld_str
        
        # Format the response
        result = [
            f"# Converted RDF to JSON-LD",
            f"",
            f"- **Original format**: {format}",
            f"- **Triples count**: {len(g)}",
            f"- **JSON-LD size**: {len(jsonld_str)} characters",
            f"",
            f"## JSON-LD preview (first 500 chars):",
            f"```json",
            jsonld_str[:500] + ("..." if len(jsonld_str) > 500 else ""),
            f"```"
        ]
        
        return "\n".join(result)
    except Exception as e:
        return f"Error converting RDF to JSON-LD: {e}"

In [ ]:
#| export
def save_to_knowledge_base(source_name: str, graph_id: str = None) -> str:
    """Save data to the knowledge base.
    
    Args:
        source_name: Name of the source (e.g., "GS1", "Schema.org")
        graph_id: Optional graph ID to use
        
    Returns:
        A string describing what was saved to the knowledge base
    """
    # Check if we have JSON-LD content to save
    if 'jsonld_content' not in globals():
        return "Error: No JSON-LD content available to save"
    
    if 'resource_url' not in globals():
        return "Error: No resource URL available"
    
    source_url = resource_url
    
    # Parse the JSON-LD
    try:
        if isinstance(jsonld_content, str):
            data = json.loads(jsonld_content)
        else:
            data = jsonld_content
    except json.JSONDecodeError:
        return "Error: Invalid JSON-LD data"
    
    # Initialize the knowledge base
    kb = LinkedDataKnowledge()
    if not hasattr(kb, 'graphs'):
        kb.initialize_memory_structure()
    
    # Generate graph ID if not provided
    if not graph_id:
        # Try to extract a meaningful ID from the URL
        if 'wikidata.org' in source_url and 'Q' in source_url:
            # Extract Wikidata entity ID
            entity_id = normalize_wikidata_id(source_url)
            graph_id = f"wikidata:entity:{entity_id}"
        elif 'gs1.org' in source_url:
            graph_id = "gs1:vocabulary"
        elif 'schema.org' in source_url:
            graph_id = "schema.org"
        else:
            # Generate from URL
            parsed = urlparse(source_url)
            domain = parsed.netloc
            path = parsed.path.strip('/')
            if path:
                graph_id = f"{domain}:{path.replace('/', ':')}"
            else:
                graph_id = domain
    
    # Prepare metadata
    entity_count = 0
    if isinstance(data, dict):
        if '@graph' in data:
            entity_count = len(data['@graph'])
        elif '@id' in data:
            entity_count = 1
    
    metadata = {
        "title": f"{source_name} Vocabulary",
        "source": source_url,
        "vocabulary": source_url,
        "entityCount": entity_count,
        "lastUpdated": datetime.datetime.now().isoformat()
    }
    
    # Add to knowledge base
    kb.add_named_graph(graph_id, data, metadata)
    
    # Return a string describing what was saved
    full_graph_id = f"did:cogitarelink:graph:{graph_id}"
    
    result = [
        f"# Successfully saved to knowledge base",
        f"",
        f"- **Graph ID**: {graph_id}",
        f"- **Full Graph ID**: {full_graph_id}",
        f"- **Title**: {metadata['title']}",
        f"- **Entity Count**: {entity_count}",
        f"- **Source**: {source_url}",
        f"- **Last Updated**: {metadata['lastUpdated']}"
    ]
    
    return "\n".join(result)

In [ ]:
#| export
def get_knowledge_summary(graph_id: str = None) -> str:
    """Get a summary of the knowledge base or a specific graph.
    
    Args:
        graph_id: Optional graph ID to summarize, or None for the whole KB
        
    Returns:
        A string summary of the knowledge base or graph
    """
    kb = LinkedDataKnowledge()
    
    if not hasattr(kb, 'graphs'):
        return "Knowledge base not initialized"
    
    if graph_id:
        # Try to get the specific graph
        if not graph_id.startswith(('did:', 'http://', 'https://')):
            full_graph_id = f"did:cogitarelink:graph:{graph_id}"
        else:
            full_graph_id = graph_id
            
        if full_graph_id not in kb.graphs:
            return f"Graph not found: {graph_id}"
            
        graph_data = kb.graphs[full_graph_id]['data']
        metadata = kb.graphs[full_graph_id]['metadata']
        
        # Count entity types
        entity_types = {}
        for entity in graph_data.get('@graph', []):
            entity_type = entity.get('@type')
            if isinstance(entity_type, list):
                for t in entity_type:
                    entity_types[t] = entity_types.get(t, 0) + 1
            elif entity_type:
                entity_types[entity_type] = entity_types.get(entity_type, 0) + 1
        
        # Create a text summary
        summary = [f"# Graph Summary: {graph_id}"]
        summary.append(f"\n## Metadata")
        for key, value in metadata.items():
            summary.append(f"- **{key}**: {value}")
        
        summary.append(f"\n## Content")
        summary.append(f"- Entity count: {len(graph_data.get('@graph', []))}")
        summary.append(f"- Context keys: {', '.join(list(graph_data.get('@context', {}).keys())[:10])}")
        
        if entity_types:
            summary.append(f"\n## Entity Types")
            for t, count in sorted(entity_types.items(), key=lambda x: x[1], reverse=True)[:10]:
                summary.append(f"- {t}: {count}")
            if len(entity_types) > 10:
                summary.append(f"- ... and {len(entity_types) - 10} more types")
        
        return "\n".join(summary)
    else:
        # Summarize the whole knowledge base
        summary = ["# Knowledge Base Summary"]
        summary.append(f"\n## Graphs ({len(kb.graphs)} total)")
        
        for gid, graph in kb.graphs.items():
            metadata = graph['metadata']
            summary.append(f"- **{gid}**: {metadata.get('title', 'Untitled')} - {metadata.get('entityCount', 0)} entities")
        
        return "\n".join(summary)

In [ ]:
# Step 1: Fetch the initial URL
url = "https://ref.gs1.org/voc/"
headers = {"Accept": "text/turtle,application/rdf+xml,application/ld+json,text/html"}
response = httpx.get(url, headers=headers, follow_redirects=True)

print(f"Status code: {response.status_code}")
print(f"Content type: {response.headers.get('Content-Type')}")
print(f"Content length: {len(response.text)} characters")
print("\nPreview:")
print(response.text[:500])

Status code: 200
Content type: text/html; charset=utf-8
Content length: 16070 characters

Preview:
<!DOCTYPE html>
<html lang="en">
	<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script>
			const ontologyJSONLDcompact = "data/gs1Voc-compact.jsonld"
			const ontologyJSONLD = "data/gs1Voc.jsonld"
			const ontologyTurtle = "data/gs1Voc.ttl"
			const changeLogJSON = "data/changeLog.json"
			const prefLang = "en"
		</script>
      <link href="https://ref.gs1.org/styles/base.css" rel="stylesheet">
      <link rel="stylesheet" hre


In [ ]:
# Step 2: Parse the HTML to find resources
soup = bs(response.text, 'html.parser')

# Look for script tags with resource references
script_references = []
for script in soup.find_all('script'):
    if script.string:
        # Look for patterns like const ontologyJSONLD = "data/gs1Voc.jsonld"
        jsonld_matches = re.findall(r'const\s+(\w+)\s*=\s*"([^"]+\.jsonld)"', script.string)
        turtle_matches = re.findall(r'const\s+(\w+)\s*=\s*"([^"]+\.ttl)"', script.string)
        
        for name, path in jsonld_matches + turtle_matches:
            full_url = urljoin(url, path)
            script_references.append((name, full_url))

print(f"Found {len(script_references)} resource references:")
for name, full_url in script_references:
    print(f"- {name}: {full_url}")

Found 3 resource references:
- ontologyJSONLDcompact: https://ref.gs1.org/voc/data/gs1Voc-compact.jsonld
- ontologyJSONLD: https://ref.gs1.org/voc/data/gs1Voc.jsonld
- ontologyTurtle: https://ref.gs1.org/voc/data/gs1Voc.ttl


In [ ]:
# Step 3: Fetch the JSON-LD file
jsonld_url = next((url for name, url in script_references if name == "ontologyJSONLD"), None)
if jsonld_url:
    print(f"Fetching JSON-LD from {jsonld_url}")
    jsonld_response = httpx.get(jsonld_url, follow_redirects=True)
    print(f"Status code: {jsonld_response.status_code}")
    print(f"Content type: {jsonld_response.headers.get('Content-Type')}")
    print(f"Content length: {len(jsonld_response.text)} characters")
    
    # Parse the JSON-LD
    try:
        jsonld_data = json.loads(jsonld_response.text)
        print(f"Successfully parsed JSON-LD")
        print(f"Keys: {list(jsonld_data.keys())}")
        if '@graph' in jsonld_data:
            print(f"Graph contains {len(jsonld_data['@graph'])} entities")
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON-LD: {e}")
else:
    print("No JSON-LD URL found")

Fetching JSON-LD from https://ref.gs1.org/voc/data/gs1Voc.jsonld
Status code: 200
Content type: application/ld+json
Content length: 1869858 characters
Successfully parsed JSON-LD
Keys: ['@context', '@graph']
Graph contains 2417 entities


In [ ]:
# Step 4: Save to knowledge base
kb = LinkedDataKnowledge()
if not hasattr(kb, 'graphs'):
    kb.initialize_memory_structure()

graph_id = "gs1:vocabulary"
metadata = {
    "title": "GS1 Vocabulary",
    "source": jsonld_url,
    "vocabulary": url,
    "entityCount": len(jsonld_data.get('@graph', [])),
    "lastUpdated": datetime.datetime.now().isoformat()
}

kb.add_named_graph(graph_id, jsonld_data, metadata)
print(f"Added graph with ID: {graph_id}")

Added graph with ID: gs1:vocabulary


In [ ]:
# Step 5: Examine the knowledge base
full_graph_id = f"did:cogitarelink:graph:{graph_id}"
if full_graph_id in kb.graphs:
    graph_data = kb.graphs[full_graph_id]['data']
    metadata = kb.graphs[full_graph_id]['metadata']
    
    print(f"Graph: {graph_id}")
    print(f"Metadata:")
    for key, value in metadata.items():
        print(f"- {key}: {value}")
    
    print(f"\nContent:")
    print(f"- Entity count: {len(graph_data.get('@graph', []))}")
    print(f"- Context keys: {', '.join(list(graph_data.get('@context', {}).keys())[:10])}")
    
    # Count entity types
    entity_types = {}
    for entity in graph_data.get('@graph', []):
        entity_type = entity.get('@type')
        if isinstance(entity_type, list):
            for t in entity_type:
                entity_types[t] = entity_types.get(t, 0) + 1
        elif entity_type:
            entity_types[entity_type] = entity_types.get(entity_type, 0) + 1
    
    print(f"\nEntity Types:")
    for t, count in sorted(entity_types.items(), key=lambda x: x[1], reverse=True)[:10]:
        print(f"- {t}: {count}")

Graph: gs1:vocabulary
Metadata:
- title: GS1 Vocabulary
- source: https://ref.gs1.org/voc/data/gs1Voc.jsonld
- vocabulary: https://ref.gs1.org/voc/
- entityCount: 2417
- lastUpdated: 2025-03-17T16:49:02.212570
- description: Graph containing 2417 entities

Content:
- Entity count: 2417
- Context keys: cc, cert, dbp, dc, dcterms, doap, exif, fn, foaf, geo

Entity Types:
- rdf:Property: 534
- gs1:AllergenTypeCode: 385
- owl:ObjectProperty: 328
- owl:DatatypeProperty: 206
- gs1:LocationRoleType: 148
- gs1:OrganizationRoleType: 137
- gs1:PackagingMaterialTypeCode: 99
- gs1:ReferencedFileTypeCode: 78
- gs1:MeasurementType: 72
- gs1:PackagingMarkedLabelAccreditationCode: 64


In [ ]:
# Step 6: Set up Claudette to explore the vocabulary
model = models[2]  # Use Claude 3.5 Sonnet

# Create global variables to store state between tool calls
last_fetched_content = None
last_fetched_url = None
extracted_resources = None
resource_content = None
resource_url = None
resource_content_type = None
jsonld_content = None

# Define our tools
def fetch_url(url: str, follow_redirects: bool = True, accept_header: str = None) -> str:
    """Fetch content from a URL with optional content negotiation."""
    global last_fetched_content, last_fetched_url
    
    headers = {}
    if accept_header:
        headers["Accept"] = accept_header
    
    try:
        response = httpx.get(url, headers=headers, follow_redirects=follow_redirects)
        last_fetched_content = response.text
        last_fetched_url = url
        
        return f"# Fetched content from {url}\n\n- Status code: {response.status_code}\n- Content type: {response.headers.get('Content-Type', '')}\n- Content length: {len(response.text)} characters"
    except Exception as e:
        return f"Error fetching URL: {e}"

def explore_vocabulary(entity_type: str = None) -> str:
    """Explore the GS1 vocabulary, optionally filtering by entity type."""
    global kb
    
    if not hasattr(kb, 'graphs') or f"did:cogitarelink:graph:{graph_id}" not in kb.graphs:
        return "GS1 vocabulary not loaded"
    
    graph_data = kb.graphs[f"did:cogitarelink:graph:{graph_id}"]['data']
    
    # Filter entities by type if specified
    entities = []
    for entity in graph_data.get('@graph', []):
        if entity_type:
            entity_types = entity.get('@type', [])
            if not isinstance(entity_types, list):
                entity_types = [entity_types]
            
            if entity_type in entity_types or any(t.endswith(entity_type) for t in entity_types):
                entities.append(entity)
        else:
            entities.append(entity)
    
    # Format results
    result = [f"# GS1 Vocabulary Exploration"]
    
    if entity_type:
        result.append(f"\nFound {len(entities)} entities of type '{entity_type}'")
    else:
        result.append(f"\nFound {len(entities)} total entities")
    
    # Show sample entities
    result.append("\n## Sample Entities")
    for entity in entities[:5]:
        entity_id = entity.get('@id', 'Unknown ID')
        entity_type = entity.get('@type', 'Unknown Type')
        
        # Try to find a label
        label = None
        for key, value in entity.items():
            if 'label' in key.lower():
                if isinstance(value, str):
                    label = value
                    break
                elif isinstance(value, list) and value:
                    if isinstance(value[0], dict) and '@value' in value[0]:
                        label = value[0]['@value']
                    else:
                        label = str(value[0])
                    break
        
        if label:
            result.append(f"- **{entity_id}** ({entity_type}): {label}")
        else:
            result.append(f"- **{entity_id}** ({entity_type})")
    
    if len(entities) > 5:
        result.append(f"\n*...and {len(entities) - 5} more entities*")
    
    return "\n".join(result)

# Set up the chat with our tools
system_prompt = """
You are an expert in semantic web technologies and linked data. Your task is to help explore the GS1 vocabulary that has been loaded into our knowledge base.

The GS1 vocabulary describes standards for supply chain management, product identification, and related domains.

Use the explore_vocabulary tool to investigate the vocabulary structure and content. You can filter by entity type to focus on specific aspects.
"""

chat = Chat(model, sp=system_prompt, tools=[explore_vocabulary])

**AI Prompt**

Okay, so we've done this step by step. What do we think of the outputs?

**AI Response**

Based on the outputs we've seen, our approach to exploring the GS1 vocabulary has been quite successful. Here are my observations:

1. **Resource Discovery**: We successfully identified the available resources from the GS1 website, finding three key files:
   - ontologyJSONLDcompact: A compact JSON-LD version
   - ontologyJSONLD: The full JSON-LD version
   - ontologyTurtle: A Turtle format version

2. **Content Retrieval**: We successfully fetched the JSON-LD file, which was quite large (1.87MB) and contained 2,417 entities.

3. **Knowledge Base Integration**: We stored the vocabulary in our LinkedDataKnowledge system with a meaningful graph ID (gs1:vocabulary) and appropriate metadata.

4. **Vocabulary Analysis**: The entity type breakdown shows a rich vocabulary with:
   - 534 rdf:Property instances
   - 385 gs1:AllergenTypeCode instances
   - 328 owl:ObjectProperty instances
   - 206 owl:DatatypeProperty instances
   - Various domain-specific types like LocationRoleType, OrganizationRoleType, etc.

5. **Tool-Based Exploration**: We set up a Claudette-compatible tool (explore_vocabulary) that allows semantic exploration of the vocabulary.

This approach demonstrates how we can combine traditional code (for the initial fetching and parsing) with an LLM-based approach (for exploration and analysis). The LLM can now explore this rich vocabulary without having to handle the complexities of fetching and parsing the data.

The outputs show that our code works as expected and provides a solid foundation for both programmatic and LLM-based exploration of linked data vocabularies. The combination of traditional code for the heavy lifting (HTTP requests, parsing) with LLM-driven exploration seems like a good balance between Software 1.0 and 2.0 approaches.

Would you like to see how we could extend this approach to other vocabularies or explore specific aspects of the GS1 vocabulary in more depth?

**AI Prompt**

So remember, our goal here is to train an LLM system to systematically think through the LOD access patterns and how to successfully retrieve a URI.

**AI Response**

You're right, and that's an important focus. Our goal is to train an LLM system to systematically reason through Linked Open Data (LOD) access patterns and successfully retrieve resources from URIs.

Based on what we've seen, here's how we could structure the LLM's thinking process for LOD retrieval:

1. **URI Analysis**:
   - Identify the domain (gs1.org, schema.org, wikidata.org, etc.)
   - Recognize patterns in the URI structure (entity IDs, vocabulary paths)
   - Determine if it's a vocabulary, an entity, or a collection

2. **Content Negotiation Strategy**:
   - Select appropriate Accept headers based on domain knowledge
   - Prioritize machine-readable formats (JSON-LD, Turtle, RDF/XML)
   - Always follow redirects

3. **Response Analysis**:
   - For HTML responses:
     - Look for embedded JSON-LD in script tags
     - Check for script variables referencing data files
     - Examine link tags for alternate formats
   - For direct RDF responses:
     - Identify the format (JSON-LD, Turtle, etc.)
     - Parse appropriately

4. **Resource Selection Logic**:
   - Prioritize complete representations over context files
   - Prefer JSON-LD for direct consumption, Turtle for transformation
   - Consider domain-specific preferences (e.g., Wikidata works better with Turtle)

5. **Vocabulary Structure Mapping**:
   - Identify key entity types
   - Recognize property patterns
   - Map to common vocabulary patterns (RDFS, OWL, SKOS)

We could train the LLM by providing examples of different URI patterns and the correct reasoning process for each. For example:

- For vocabulary URIs: "When I see a URI like https://ref.gs1.org/voc/, I should first check if it returns machine-readable data directly. If it returns HTML, I should look for references to data files in script tags or link elements."

- For entity URIs: "When I see a URI like http://www.wikidata.org/entity/Q42, I should request it with the appropriate format extension (.ttl) and parameters (flavor=simple) based on domain knowledge."

The key is to help the LLM develop a systematic thinking process that adapts to different LOD sources while following common patterns and best practices.

Would you like to develop this thinking framework further, or focus on a specific aspect of this process?

**AI Prompt**

Okay, so you've created a logic tree, but we need to implement this as an agentic workflow using LLMS and prompting. How do we do that?

**AI Response**

You're right - we need to translate this logical framework into an agentic workflow using LLMs and prompting. Here's how we could implement this:

## Implementing the LOD Surfer as an Agentic Workflow

### 1. System Prompt Design

We'll start with a base system prompt that establishes the agent's role and core capabilities:

```
You are LODSurfer, an expert agent specialized in navigating and retrieving data from the Linked Open Data cloud. Your goal is to systematically retrieve machine-readable data from any URI.

When presented with a URI, you will:
1. Analyze the URI pattern
2. Determine appropriate retrieval strategies
3. Request information using available tools
4. Process the responses
5. Extract structured data
6. Decide on next steps

Always think step-by-step, explaining your reasoning at each stage.
```

### 2. Tool Definitions

We'll define a set of tools the agent can use:

```python
def http_get(url: str, headers: dict = None) -> dict:
    """Make an HTTP GET request to the specified URL with optional headers.
    Returns the response status, headers, and content."""
    pass

def parse_html(html: str) -> dict:
    """Parse HTML content to extract embedded data, links, and script references."""
    pass

def parse_rdf(content: str, format: str) -> dict:
    """Parse RDF content in the specified format (turtle, rdfxml, etc.) into JSON-LD."""
    pass

def extract_jsonld(content: str) -> dict:
    """Extract and parse JSON-LD content."""
    pass

def resolve_uri(base_uri: str, relative_path: str) -> str:
    """Resolve a relative URI against a base URI."""
    pass
```

### 3. Chain-of-Thought Prompting

We'll use chain-of-thought prompting to guide the agent through the reasoning process:

```
To retrieve data from {uri}, follow these steps:

1. URI Analysis: Examine the URI pattern and classify it.
2. Strategy Selection: Based on the URI type and domain, determine the best retrieval strategy.
3. Initial Request: Make an HTTP request with appropriate headers.
4. Response Analysis: Analyze the response to determine next steps.
5. Data Extraction: Extract structured data from the response.
6. Verification: Verify that you've obtained machine-readable data.
7. Reflection: Consider if additional steps are needed.

Think through each step carefully, explaining your reasoning.
```

### 4. Multi-Step Workflow Implementation

Here's how we can implement this as a multi-step workflow:

```python
class LODSurferAgent:
    def __init__(self, model):
        self.model = model
        self.memory = []
        self.tools = {
            "http_get": http_get,
            "parse_html": parse_html,
            "parse_rdf": parse_rdf,
            "extract_jsonld": extract_jsonld,
            "resolve_uri": resolve_uri
        }
    
    def retrieve_uri(self, uri):
        # Step 1: URI Analysis
        analysis_prompt = f"""
        Analyze this URI: {uri}
        
        Determine:
        1. What type of URI is this? (vocabulary, entity, collection)
        2. What domain/provider does it belong to?
        3. Are there any known patterns for this domain?
        
        Output your analysis as a structured JSON object.
        """
        analysis = self._call_model(analysis_prompt)
        self.memory.append(("analysis", analysis))
        
        # Step 2: Strategy Selection
        strategy_prompt = f"""
        Based on this URI analysis: {analysis}
        
        Determine the best strategy to retrieve machine-readable data:
        1. What HTTP headers should be used?
        2. Should any URI transformations be applied?
        3. What content types should be prioritized?
        
        Output your strategy as a structured JSON object.
        """
        strategy = self._call_model(strategy_prompt)
        self.memory.append(("strategy", strategy))
        
        # Step 3: Initial Request
        request_prompt = f"""
        Execute the following strategy to retrieve data from {uri}:
        {strategy}
        
        Use the http_get tool with appropriate parameters.
        """
        response = self._call_model_with_tools(request_prompt, ["http_get"])
        self.memory.append(("response", response))
        
        # Step 4: Response Analysis
        analysis_prompt = f"""
        Analyze this HTTP response:
        {response}
        
        Determine:
        1. What type of content was returned?
        2. Is it directly usable machine-readable data?
        3. If not, what additional steps are needed?
        
        Output your analysis as a structured JSON object.
        """
        response_analysis = self._call_model(analysis_prompt)
        self.memory.append(("response_analysis", response_analysis))
        
        # Steps 5-7: Continue based on response analysis
        # (Additional steps would follow similar pattern)
        
    def _call_model(self, prompt):
        # Call the LLM with the given prompt
        pass
        
    def _call_model_with_tools(self, prompt, allowed_tools):
        # Call the LLM with the given prompt and allowed tools
        pass
```

### 5. Reflective Prompting

After each major step, we can add reflective prompting to improve the agent's reasoning:

```
Now that you've [completed step X], reflect on your approach:

1. What worked well in your approach?
2. What assumptions did you make?
3. What alternative approaches could you have taken?
4. What would you do differently next time?

This reflection will help improve your URI retrieval capabilities.
```

### 6. Error Handling and Recovery

We can implement specialized prompts for error recovery:

```
You encountered an error while trying to retrieve data from {uri}:
{error}

Consider these recovery strategies:
1. Try different content negotiation headers
2. Look for alternative representations
3. Check for redirect patterns
4. Extract embedded data from HTML
5. Construct alternative URIs

Which recovery strategy would you like to try next, and why?
```

Would you like me to elaborate on any specific part of this implementation approach? For example, I could provide more detailed prompt templates or discuss how to handle specific edge cases.

In [ ]:
# First component: Basic URI analysis and HTTP request

import httpx
import json
from urllib.parse import urlparse

def analyze_uri(uri):
    """Analyze a URI and return basic information about it."""
    parsed = urlparse(uri)
    
    # Extract domain information
    domain = parsed.netloc
    path = parsed.path
    
    # Simple domain classification
    domain_type = "unknown"
    if "wikidata.org" in domain:
        domain_type = "wikidata"
    elif "gs1.org" in domain or "ref.gs1.org" in domain:
        domain_type = "gs1"
    elif "schema.org" in domain:
        domain_type = "schema"
    
    # Simple path analysis
    path_type = "unknown"
    if path.endswith(".jsonld") or path.endswith(".ttl") or path.endswith(".rdf"):
        path_type = "direct_resource"
    elif "/voc/" in path or "/ontology" in path:
        path_type = "vocabulary"
    elif "Q" in path or "P" in path:  # Wikidata-specific
        path_type = "entity"
    
    return {
        "uri": uri,
        "domain": domain,
        "domain_type": domain_type,
        "path": path,
        "path_type": path_type
    }

In [ ]:
def test_analyze_uri():
    """Test the URI analysis with a few examples."""
    test_uris = [
        "https://ref.gs1.org/voc/",
        "https://www.wikidata.org/entity/Q42",
        "https://schema.org/Person"
    ]
    
    for uri in test_uris:
        analysis = analyze_uri(uri)
        print(f"Analysis for {uri}:")
        print(json.dumps(analysis, indent=2))
        print()

In [ ]:
test_analyze_uri()

Analysis for https://ref.gs1.org/voc/:
{
  "uri": "https://ref.gs1.org/voc/",
  "domain": "ref.gs1.org",
  "domain_type": "gs1",
  "path": "/voc/",
  "path_type": "vocabulary"
}

Analysis for https://www.wikidata.org/entity/Q42:
{
  "uri": "https://www.wikidata.org/entity/Q42",
  "domain": "www.wikidata.org",
  "domain_type": "wikidata",
  "path": "/entity/Q42",
  "path_type": "entity"
}

Analysis for https://schema.org/Person:
{
  "uri": "https://schema.org/Person",
  "domain": "schema.org",
  "domain_type": "schema",
  "path": "/Person",
  "path_type": "entity"
}



In [ ]:
def agentic_uri_analysis(uri):
    """Use an LLM to analyze a URI and determine its characteristics."""
    
    system_prompt = """
    You are an expert in Linked Open Data (LOD) and semantic web technologies.
    Your task is to analyze URIs and identify their characteristics to help with data retrieval.
    Provide your analysis as structured JSON.
    """
    
    user_prompt = f"""
    Please analyze this URI: {uri}
    
    Determine:
    1. What domain/provider does it belong to?
    2. What type of resource it likely represents (vocabulary, entity, property, collection)?
    3. Any special patterns or characteristics of this URI that would affect how to retrieve data from it?
    4. What is the standard way to request machine-readable data from this type of URI?
    
    Format your response as a JSON object with these fields:
    - domain_type: The type of domain (e.g., "wikidata", "schema", "gs1", etc.)
    - resource_type: The type of resource (e.g., "vocabulary", "entity", "property")
    - special_patterns: Array of any special patterns or characteristics
    - retrieval_strategy: Object containing recommended approach for retrieving data
    
    Return only the JSON object, no other text.
    """
    
    # Create a chat instance
    chat = Chat(model, sp=system_prompt)
    
    # Get the analysis from Claude
    response = chat(user_prompt)
    
    # In Claudette, we need to access the content correctly
    try:
        import re
        import json
        
        # Extract the text from the Message object properly
        # The Message object in Claudette has a content attribute which is a list of content blocks
        content_text = ""
        for content_item in response.content:
            if hasattr(content_item, 'text'):
                content_text += content_item.text
        
        # Find JSON-like structure in the response
        json_match = re.search(r'```json\s*(.*?)\s*```', content_text, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            # If no JSON code block, try to parse the whole content
            json_str = content_text
        
        # Clean up the string to ensure it's valid JSON
        json_str = re.sub(r'```.*?```', '', json_str, flags=re.DOTALL)
        json_str = json_str.strip()
        
        # Parse the JSON
        analysis = json.loads(json_str)
        return analysis
    except Exception as e:
        print(f"Error parsing LLM response: {e}")
        print(f"Raw response: {str(response)[:500]}")  # Print first 500 chars of response
        # Return a basic analysis as fallback
        return {
            "domain_type": "unknown",
            "resource_type": "unknown",
            "special_patterns": [],
            "retrieval_strategy": {"note": "Failed to parse LLM response"}
        }

In [ ]:
def test_agentic_uri_analysis():
    """Test the agentic URI analysis with a few examples."""
    test_uris = [
        "https://ref.gs1.org/voc/",
        "https://www.wikidata.org/entity/Q42",
        "https://schema.org/Person"
    ]
    
    for uri in test_uris:
        print(f"\nAnalyzing: {uri}")
        analysis = agentic_uri_analysis(uri)
        print(json.dumps(analysis, indent=2))

In [ ]:
test_agentic_uri_analysis()


Analyzing: https://ref.gs1.org/voc/
{
  "domain_type": "gs1",
  "resource_type": "vocabulary",
  "special_patterns": [
    "ref.gs1.org domain indicates official GS1 reference data",
    "voc/ path suggests a vocabulary or ontology endpoint",
    "follows standard LOD vocabulary publishing patterns"
  ],
  "retrieval_strategy": {
    "primary_method": "HTTP GET with content negotiation",
    "accept_headers": [
      "application/rdf+xml",
      "text/turtle",
      "application/ld+json"
    ],
    "expected_response": "RDF vocabulary definition",
    "fallback_method": "Check for vocabulary documentation at HTML representation"
  }
}

Analyzing: https://www.wikidata.org/entity/Q42
{
  "domain_type": "wikidata",
  "resource_type": "entity",
  "special_patterns": [
    "Q prefix indicates an entity/item in Wikidata",
    "Numeric ID after Q represents unique identifier",
    "entity in URL path indicates resource type"
  ],
  "retrieval_strategy": {
    "primary_method": "content negot

**AI Prompt**

What do you think of this output?

**AI Response**

The output from the agentic URI analysis looks excellent! It demonstrates several key advantages of the Software 2.0 approach:

1. **Rich Domain Knowledge**: Claude has provided detailed analysis that includes domain-specific knowledge about GS1, Wikidata, and Schema.org without us having to explicitly encode these rules.

2. **Nuanced Understanding**: The model recognized subtle distinctions between different resource types and their retrieval patterns. For example, it correctly identified that:
   - GS1 follows standard LOD vocabulary publishing patterns
   - Wikidata Q-prefixed IDs represent entities with specific retrieval patterns
   - Schema.org terms typically return HTML documentation by default

3. **Comprehensive Strategies**: The suggested retrieval strategies are quite sophisticated, including:
   - Primary and fallback methods
   - Appropriate content negotiation headers
   - Alternative endpoints (like Wikidata's SPARQL endpoint)
   - Special API patterns

4. **Extensibility**: This approach would naturally extend to URIs from domains we haven't explicitly coded for, as the model can apply its general knowledge of semantic web practices.

The output also demonstrates how Claude can provide structured, machine-readable responses (JSON) while still incorporating nuanced reasoning about LOD access patterns.

This is exactly what we want in a Software 2.0 approach - letting the LLM apply its broad knowledge to handle cases that would be tedious to encode as explicit rules, while still providing structured output that our system can act upon.

Would you like to proceed to the next step of implementing the actual retrieval process based on this analysis?

In [ ]:
def agentic_retrieve_data(uri, analysis):
    """Retrieve data from a URI based on LLM analysis."""
    import httpx
    import json
    from bs4 import BeautifulSoup
    from urllib.parse import urljoin
    
    # Extract retrieval strategy from analysis
    strategy = analysis.get("retrieval_strategy", {})
    
    # Set up headers based on analysis
    headers = {}
    accept_headers = strategy.get("accept_headers", [])
    if accept_headers:
        headers["Accept"] = ", ".join(accept_headers)
    
    # Determine the URL to request
    request_url = uri
    if "alternative_endpoint" in strategy and strategy.get("primary_method") != "content negotiation":
        request_url = strategy["alternative_endpoint"]
    elif "api_pattern" in strategy:
        request_url = strategy["api_pattern"]
    
    print(f"Requesting {request_url} with headers: {headers}")
    
    # Make the request
    try:
        response = httpx.get(request_url, headers=headers, follow_redirects=True)
        
        # Basic response info
        result = {
            "status_code": response.status_code,
            "content_type": response.headers.get("Content-Type", ""),
            "url": str(response.url),
            "success": response.status_code == 200,
            "data_format": "unknown",
            "content_preview": response.text[:500] + ("..." if len(response.text) > 500 else ""),
            "full_content": response.text  # Store the full content
        }
        
        # Determine the format of the response
        content_type = response.headers.get("Content-Type", "").lower()
        if "json" in content_type:
            result["data_format"] = "json"
            try:
                result["parsed_data"] = response.json()
            except:
                result["parsing_error"] = "Failed to parse JSON"
        
        elif "turtle" in content_type or "text/ttl" in content_type:
            result["data_format"] = "turtle"
        
        elif "rdf+xml" in content_type or "application/rdf" in content_type:
            result["data_format"] = "rdf+xml"
        
        elif "html" in content_type:
            result["data_format"] = "html"
            
            # For HTML, check for embedded data or resource references
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Look for JSON-LD script tags
            jsonld_scripts = soup.select('script[type="application/ld+json"]')
            if jsonld_scripts:
                result["embedded_jsonld_count"] = len(jsonld_scripts)
                result["embedded_data"] = True
            
            # Look for resource references in scripts
            resource_refs = []
            for script in soup.find_all('script'):
                if script.string:
                    import re
                    # Look for patterns like const ontologyJSONLD = "data/gs1Voc.jsonld"
                    jsonld_matches = re.findall(r'const\s+(\w+)\s*=\s*"([^"]+\.jsonld)"', script.string)
                    turtle_matches = re.findall(r'const\s+(\w+)\s*=\s*"([^"]+\.ttl)"', script.string)
                    
                    for name, path in jsonld_matches + turtle_matches:
                        full_url = urljoin(str(response.url), path)
                        resource_refs.append({"name": name, "path": path, "url": full_url})
            
            if resource_refs:
                result["resource_references"] = resource_refs
        
        return result
        
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "url": request_url
        }

def agentic_process_response(uri, initial_analysis, initial_result):
    """Process the initial response and take appropriate follow-up actions."""
    import httpx
    import json
    from bs4 import BeautifulSoup
    import re
    from rdflib import Graph
    
    domain_type = initial_analysis.get("domain_type", "unknown")
    resource_type = initial_analysis.get("resource_type", "unknown")
    data_format = initial_result.get("data_format", "unknown")
    
    print(f"Processing response for {uri} ({domain_type}/{resource_type}, format: {data_format})")
    
    # Initialize the result structure
    result = {
        "uri": uri,
        "domain_type": domain_type,
        "resource_type": resource_type,
        "initial_format": data_format,
        "success": False,
        "steps_taken": [],
        "final_format": None,
        "structured_data": None
    }
    
    try:
        # Case 1: HTML with resource references (like GS1)
        if data_format == "html" and "resource_references" in initial_result:
            result["steps_taken"].append("found_resource_references")
            
            # Select the best resource to fetch
            best_resource = None
            resource_refs = initial_result["resource_references"]
            
            # Prioritize JSON-LD over Turtle
            jsonld_refs = [r for r in resource_refs if r["path"].endswith(".jsonld")]
            turtle_refs = [r for r in resource_refs if r["path"].endswith(".ttl")]
            
            if jsonld_refs:
                # Prefer non-compact version if available
                non_compact = [r for r in jsonld_refs if "compact" not in r["path"].lower()]
                best_resource = non_compact[0] if non_compact else jsonld_refs[0]
                result["steps_taken"].append("selected_jsonld_resource")
            elif turtle_refs:
                best_resource = turtle_refs[0]
                result["steps_taken"].append("selected_turtle_resource")
            
            if best_resource:
                print(f"Fetching resource: {best_resource['url']}")
                result["steps_taken"].append(f"fetching_{best_resource['name']}")
                
                # Fetch the resource
                response = httpx.get(best_resource["url"], follow_redirects=True)
                if response.status_code == 200:
                    result["success"] = True
                    result["steps_taken"].append("resource_fetch_success")
                    
                    # Process based on format
                    if best_resource["path"].endswith(".jsonld"):
                        result["final_format"] = "jsonld"
                        try:
                            result["structured_data"] = response.json()
                            result["steps_taken"].append("parsed_jsonld")
                        except:
                            result["steps_taken"].append("jsonld_parse_failed")
                            result["success"] = False
                    
                    elif best_resource["path"].endswith(".ttl"):
                        result["final_format"] = "turtle"
                        try:
                            # Parse Turtle to RDF graph
                            g = Graph()
                            g.parse(data=response.text, format="turtle")
                            
                            # Convert to JSON-LD for consistent output
                            jsonld_data = json.loads(g.serialize(format="json-ld"))
                            result["structured_data"] = jsonld_data
                            result["steps_taken"].append("converted_turtle_to_jsonld")
                        except Exception as e:
                            result["steps_taken"].append(f"turtle_conversion_failed: {str(e)}")
                            result["success"] = False
                else:
                    result["steps_taken"].append(f"resource_fetch_failed: {response.status_code}")
            else:
                result["steps_taken"].append("no_suitable_resource_found")
        
        # Case 2: HTML with embedded JSON-LD (like Schema.org)
        elif data_format == "html" and initial_result.get("embedded_jsonld_count", 0) > 0:
            result["steps_taken"].append("found_embedded_jsonld")
            
            # Extract embedded JSON-LD - FIXED: use full_content instead of content_preview
            soup = BeautifulSoup(initial_result["full_content"], "html.parser")
            jsonld_scripts = soup.select("script[type='application/ld+json']")
            
            if jsonld_scripts:
                try:
                    jsonld_data = json.loads(jsonld_scripts[0].string)
                    result["structured_data"] = jsonld_data
                    result["final_format"] = "jsonld"
                    result["success"] = True
                    result["steps_taken"].append("extracted_embedded_jsonld")
                except Exception as e:
                    result["steps_taken"].append(f"jsonld_extraction_failed: {str(e)}")
            else:
                result["steps_taken"].append("no_jsonld_scripts_found")
        
        # Case 3: Direct JSON (like Wikidata API)
        elif data_format == "json" and "parsed_data" in initial_result:
            result["steps_taken"].append("processing_json_response")
            
            # For Wikidata API, extract the entity data
            if domain_type == "wikidata" and "entities" in initial_result["parsed_data"]:
                entity_data = next(iter(initial_result["parsed_data"]["entities"].values()), None)
                if entity_data:
                    result["structured_data"] = entity_data
                    result["final_format"] = "wikidata_json"
                    result["success"] = True
                    result["steps_taken"].append("extracted_wikidata_entity")
                else:
                    result["steps_taken"].append("no_entity_found_in_wikidata_response")
            else:
                # For other JSON responses, use as is
                result["structured_data"] = initial_result["parsed_data"]
                result["final_format"] = "json"
                result["success"] = True
                result["steps_taken"].append("using_direct_json")
        
        # Case 4: Direct RDF/Turtle
        elif data_format in ["turtle", "rdf+xml"]:
            result["steps_taken"].append(f"processing_direct_{data_format}")
            
            try:
                # Parse RDF to graph
                g = Graph()
                g.parse(data=initial_result["full_content"], format=data_format)
                
                # Convert to JSON-LD for consistent output
                jsonld_data = json.loads(g.serialize(format="json-ld"))
                result["structured_data"] = jsonld_data
                result["final_format"] = "jsonld"
                result["success"] = True
                result["steps_taken"].append(f"converted_{data_format}_to_jsonld")
            except Exception as e:
                result["steps_taken"].append(f"{data_format}_conversion_failed: {str(e)}")
        
        # Case 5: Fallback to LLM for guidance
        else:
            result["steps_taken"].append("no_standard_pattern_found")
            # This would be where we'd ask the LLM for guidance on how to proceed
            # For now, we'll just mark it as unsuccessful
            result["steps_taken"].append("would_ask_llm_for_guidance")
    
    except Exception as e:
        result["steps_taken"].append(f"processing_error: {str(e)}")
    
    # Add data stats if we have structured data
    if result["structured_data"]:
        if isinstance(result["structured_data"], dict):
            result["data_stats"] = {
                "keys": list(result["structured_data"].keys()),
                "size": len(json.dumps(result["structured_data"]))
            }
        elif isinstance(result["structured_data"], list):
            result["data_stats"] = {
                "count": len(result["structured_data"]),
                "size": len(json.dumps(result["structured_data"]))
            }
    
    return result

In [ ]:
def test_agentic_retrieval():
    """Test the agentic retrieval process with our example URIs."""
    test_uris = [
        "https://ref.gs1.org/voc/",
        "https://www.wikidata.org/entity/Q42",
        "https://schema.org/Person"
    ]
    
    for uri in test_uris:
        print(f"\n\n=== Testing retrieval for: {uri} ===")
        analysis = agentic_uri_analysis(uri)
        print("Analysis:")
        print(json.dumps(analysis, indent=2))
        
        print("\nRetrieval result:")
        result = agentic_retrieve_data(uri, analysis)
        
        # Print a clean summary of the result
        print(f"Status: {'SUCCESS' if result['success'] else 'FAILED'}")
        print(f"URL: {result['url']}")
        print(f"Content type: {result.get('content_type', 'N/A')}")
        print(f"Data format: {result.get('data_format', 'N/A')}")
        
        if result.get('embedded_data', False):
            print(f"Embedded JSON-LD: {result.get('embedded_jsonld_count', 0)} blocks")
        
        if "resource_references" in result:
            print("\nResource references:")
            for ref in result["resource_references"]:
                print(f"- {ref['name']}: {ref['url']}")
        
        print("\nContent preview:")
        print(result.get("content_preview", "")[:200] + "...")

In [ ]:
test_agentic_retrieval()



=== Testing retrieval for: https://ref.gs1.org/voc/ ===
Analysis:
{
  "domain_type": "gs1",
  "resource_type": "vocabulary",
  "special_patterns": [
    "ref.gs1.org domain indicates official GS1 reference data",
    "voc/ path suggests a vocabulary or ontology endpoint",
    "follows standard LOD vocabulary publishing patterns"
  ],
  "retrieval_strategy": {
    "primary_method": "HTTP GET with content negotiation",
    "accept_headers": [
      "application/rdf+xml",
      "text/turtle",
      "application/ld+json"
    ],
    "expected_response": "RDF vocabulary definition",
    "fallback_method": "Check for vocabulary documentation at HTML representation"
  }
}

Retrieval result:
Requesting https://ref.gs1.org/voc/ with headers: {'Accept': 'application/rdf+xml, text/turtle, application/ld+json'}
Status: SUCCESS
URL: https://ref.gs1.org/voc/
Content type: text/html; charset=utf-8
Data format: html

Resource references:
- ontologyJSONLDcompact: https://ref.gs1.org/voc/data/gs1Voc-co

**AI Prompt**

Ok. What do we think of this response?

**AI Response**

The results look very promising! Our agentic retrieval process is working well, with some interesting observations:

1. For GS1:
   - The LLM correctly recommended content negotiation with appropriate headers
   - Our system successfully retrieved the HTML and found the resource references (JSON-LD and Turtle files)
   - This matches exactly what we discovered manually earlier

2. For Wikidata:
   - The LLM suggested both content negotiation and an API pattern
   - Our system used the API pattern and successfully retrieved JSON data
   - This demonstrates the value of domain-specific knowledge encoded in the LLM's analysis

3. For Schema.org:
   - The LLM correctly identified it as a vocabulary term with human-readable documentation by default
   - Our system found embedded JSON-LD in the HTML response
   - This shows the system handling mixed content types appropriately

What's particularly impressive is that the LLM provided tailored strategies for each domain without us having to hardcode them. For example:

- For Wikidata, it knew about the API endpoint pattern
- For GS1, it anticipated we might need to look for resource references in HTML
- For Schema.org, it correctly identified that embedded JSON-LD would be present

This demonstrates the power of the Software 2.0 approach - we're leveraging the LLM's knowledge of LOD patterns rather than having to encode all these rules ourselves.

The next step would be to implement a follow-up process that takes appropriate action based on the retrieval results:

1. For GS1, fetch one of the discovered resource references
2. For Schema.org, extract the embedded JSON-LD
3. For Wikidata, parse the JSON response

Would you like to implement this next step to complete the retrieval workflow?

In [ ]:
def agentic_process_response(uri, initial_analysis, initial_result):
    """Process the initial response and take appropriate follow-up actions."""
    import httpx
    import json
    from bs4 import BeautifulSoup
    import re
    from rdflib import Graph
    
    domain_type = initial_analysis.get("domain_type", "unknown")
    resource_type = initial_analysis.get("resource_type", "unknown")
    data_format = initial_result.get("data_format", "unknown")
    
    print(f"Processing response for {uri} ({domain_type}/{resource_type}, format: {data_format})")
    
    # Initialize the result structure
    result = {
        "uri": uri,
        "domain_type": domain_type,
        "resource_type": resource_type,
        "initial_format": data_format,
        "success": False,
        "steps_taken": [],
        "final_format": None,
        "structured_data": None
    }
    
    try:
        # Case 1: HTML with resource references (like GS1)
        if data_format == "html" and "resource_references" in initial_result:
            result["steps_taken"].append("found_resource_references")
            
            # Select the best resource to fetch
            best_resource = None
            resource_refs = initial_result["resource_references"]
            
            # Prioritize JSON-LD over Turtle
            jsonld_refs = [r for r in resource_refs if r["path"].endswith(".jsonld")]
            turtle_refs = [r for r in resource_refs if r["path"].endswith(".ttl")]
            
            if jsonld_refs:
                # Prefer non-compact version if available
                non_compact = [r for r in jsonld_refs if "compact" not in r["path"].lower()]
                best_resource = non_compact[0] if non_compact else jsonld_refs[0]
                result["steps_taken"].append("selected_jsonld_resource")
            elif turtle_refs:
                best_resource = turtle_refs[0]
                result["steps_taken"].append("selected_turtle_resource")
            
            if best_resource:
                print(f"Fetching resource: {best_resource['url']}")
                result["steps_taken"].append(f"fetching_{best_resource['name']}")
                
                # Fetch the resource
                response = httpx.get(best_resource["url"], follow_redirects=True)
                if response.status_code == 200:
                    result["success"] = True
                    result["steps_taken"].append("resource_fetch_success")
                    
                    # Process based on format
                    if best_resource["path"].endswith(".jsonld"):
                        result["final_format"] = "jsonld"
                        try:
                            result["structured_data"] = response.json()
                            result["steps_taken"].append("parsed_jsonld")
                        except:
                            result["steps_taken"].append("jsonld_parse_failed")
                            result["success"] = False
                    
                    elif best_resource["path"].endswith(".ttl"):
                        result["final_format"] = "turtle"
                        try:
                            # Parse Turtle to RDF graph
                            g = Graph()
                            g.parse(data=response.text, format="turtle")
                            
                            # Convert to JSON-LD for consistent output
                            jsonld_data = json.loads(g.serialize(format="json-ld"))
                            result["structured_data"] = jsonld_data
                            result["steps_taken"].append("converted_turtle_to_jsonld")
                        except Exception as e:
                            result["steps_taken"].append(f"turtle_conversion_failed: {str(e)}")
                            result["success"] = False
                else:
                    result["steps_taken"].append(f"resource_fetch_failed: {response.status_code}")
            else:
                result["steps_taken"].append("no_suitable_resource_found")
        
        # Case 2: HTML with embedded JSON-LD (like Schema.org)
        elif data_format == "html" and initial_result.get("embedded_jsonld_count", 0) > 0:
            result["steps_taken"].append("found_embedded_jsonld")
            
            # Extract embedded JSON-LD - FIXED: use full_content instead of content_preview
            soup = BeautifulSoup(initial_result["full_content"], "html.parser")
            jsonld_scripts = soup.select("script[type='application/ld+json']")
            
            if jsonld_scripts:
                try:
                    jsonld_data = json.loads(jsonld_scripts[0].string)
                    result["structured_data"] = jsonld_data
                    result["final_format"] = "jsonld"
                    result["success"] = True
                    result["steps_taken"].append("extracted_embedded_jsonld")
                except Exception as e:
                    result["steps_taken"].append(f"jsonld_extraction_failed: {str(e)}")
            else:
                result["steps_taken"].append("no_jsonld_scripts_found")
        
        # Case 3: Direct JSON (like Wikidata API)
        elif data_format == "json" and "parsed_data" in initial_result:
            result["steps_taken"].append("processing_json_response")
            
            # For Wikidata API, extract the entity data
            if domain_type == "wikidata" and "entities" in initial_result["parsed_data"]:
                entity_data = next(iter(initial_result["parsed_data"]["entities"].values()), None)
                if entity_data:
                    result["structured_data"] = entity_data
                    result["final_format"] = "wikidata_json"
                    result["success"] = True
                    result["steps_taken"].append("extracted_wikidata_entity")
                else:
                    result["steps_taken"].append("no_entity_found_in_wikidata_response")
            else:
                # For other JSON responses, use as is
                result["structured_data"] = initial_result["parsed_data"]
                result["final_format"] = "json"
                result["success"] = True
                result["steps_taken"].append("using_direct_json")
        
        # Case 4: Direct RDF/Turtle
        elif data_format in ["turtle", "rdf+xml"]:
            result["steps_taken"].append(f"processing_direct_{data_format}")
            
            try:
                # Parse RDF to graph
                g = Graph()
                g.parse(data=initial_result["full_content"], format=data_format)
                
                # Convert to JSON-LD for consistent output
                jsonld_data = json.loads(g.serialize(format="json-ld"))
                result["structured_data"] = jsonld_data
                result["final_format"] = "jsonld"
                result["success"] = True
                result["steps_taken"].append(f"converted_{data_format}_to_jsonld")
            except Exception as e:
                result["steps_taken"].append(f"{data_format}_conversion_failed: {str(e)}")
        
        # Case 5: Fallback to LLM for guidance
        else:
            result["steps_taken"].append("no_standard_pattern_found")
            # This would be where we'd ask the LLM for guidance on how to proceed
            # For now, we'll just mark it as unsuccessful
            result["steps_taken"].append("would_ask_llm_for_guidance")
    
    except Exception as e:
        result["steps_taken"].append(f"processing_error: {str(e)}")
    
    # Add data stats if we have structured data
    if result["structured_data"]:
        if isinstance(result["structured_data"], dict):
            result["data_stats"] = {
                "keys": list(result["structured_data"].keys()),
                "size": len(json.dumps(result["structured_data"]))
            }
        elif isinstance(result["structured_data"], list):
            result["data_stats"] = {
                "count": len(result["structured_data"]),
                "size": len(json.dumps(result["structured_data"]))
            }
    
    return result

In [ ]:
def test_complete_workflow():
    """Test the complete workflow from URI to structured data."""
    test_uris = [
        "https://ref.gs1.org/voc/",
        "https://www.wikidata.org/entity/Q42",
        "https://schema.org/Person"
    ]
    
    for uri in test_uris:
        print(f"\n\n{'='*50}")
        print(f"TESTING COMPLETE WORKFLOW FOR: {uri}")
        print(f"{'='*50}")
        
        # Step 1: Analyze URI
        analysis = agentic_uri_analysis(uri)
        print("\nSTEP 1: URI ANALYSIS")
        print(json.dumps(analysis, indent=2))
        
        # Step 2: Initial retrieval
        initial_result = agentic_retrieve_data(uri, analysis)
        print("\nSTEP 2: INITIAL RETRIEVAL")
        print(f"Status: {'SUCCESS' if initial_result['success'] else 'FAILED'}")
        print(f"Format: {initial_result.get('data_format', 'unknown')}")
        
        # Step 3: Process response
        final_result = agentic_process_response(uri, analysis, initial_result)
        print("\nSTEP 3: RESPONSE PROCESSING")
        print(f"Success: {final_result['success']}")
        print(f"Steps taken: {', '.join(final_result['steps_taken'])}")
        print(f"Final format: {final_result['final_format']}")
        
        if final_result["success"] and "data_stats" in final_result:
            print("\nData stats:")
            for key, value in final_result["data_stats"].items():
                if key == "keys":
                    print(f"- Keys: {', '.join(value[:5])}{'...' if len(value) > 5 else ''}")
                else:
                    print(f"- {key}: {value}")

In [ ]:
test_complete_workflow()



TESTING COMPLETE WORKFLOW FOR: https://ref.gs1.org/voc/

STEP 1: URI ANALYSIS
{
  "domain_type": "gs1",
  "resource_type": "vocabulary",
  "special_patterns": [
    "ref.gs1.org domain indicates official GS1 reference data",
    "voc/ path suggests a vocabulary or ontology endpoint",
    "follows standard LOD vocabulary publishing patterns"
  ],
  "retrieval_strategy": {
    "primary_method": "HTTP GET with content negotiation",
    "accept_headers": [
      "application/rdf+xml",
      "text/turtle",
      "application/ld+json"
    ],
    "expected_response": "RDF vocabulary definition",
    "fallback_method": "Check for vocabulary documentation at HTML representation"
  }
}
Requesting https://ref.gs1.org/voc/ with headers: {'Accept': 'application/rdf+xml, text/turtle, application/ld+json'}

STEP 2: INITIAL RETRIEVAL
Status: SUCCESS
Format: html
Processing response for https://ref.gs1.org/voc/ (gs1/vocabulary, format: html)
Fetching resource: https://ref.gs1.org/voc/data/gs1Voc.json

**AI Prompt**

Ok. What do we think of our result?

**AI Response**

The results are excellent! Our complete workflow successfully handled all three test URIs, demonstrating a robust approach to accessing linked data from different sources.

Key achievements in our implementation:

1. **Complete End-to-End Process**: We've created a full workflow from URI analysis to structured data retrieval, with each step building on the previous one.

2. **Domain-Specific Handling**: The system correctly identified and applied different strategies for each domain:
   - For GS1: It found resource references in HTML and fetched the full JSON-LD file
   - For Wikidata: It used the API pattern and extracted the entity data
   - For Schema.org: It found and extracted embedded JSON-LD from the HTML

3. **Consistent Output Format**: All three sources were successfully converted to JSON-LD or compatible JSON, providing a uniform interface for downstream processing.

4. **Detailed Tracing**: The steps_taken array provides visibility into the decision-making process, which is valuable for debugging and improving the system.

5. **Adaptive Strategy**: Rather than hardcoding rules for each domain, the system adapted based on the LLM's analysis and the response content.

6. **Robust Error Handling**: The code includes fallbacks and error handling to deal with various scenarios.

What makes this approach particularly powerful is that it combines:

- The broad knowledge of the LLM about linked data patterns
- Domain-specific expertise encoded in the LLM's responses
- Procedural code to handle the technical aspects of retrieval and parsing
- A consistent workflow that can be extended to new domains

This demonstrates the value of the Software 2.0 approach - the LLM provides the domain knowledge and strategy, while traditional code handles the execution. This separation allows us to leverage the strengths of both paradigms.

To further improve this system, we could:

1. Add LLM-based fallback strategies when standard patterns fail
2. Implement a learning component that remembers successful patterns for similar URIs
3. Extend the approach to handle more complex scenarios like authentication or pagination

What aspects of this implementation do you find most interesting or valuable?

**AI Prompt**

Okay, so you have created a whole bunch of software 1.0. Remember, this is a self-discovering agent system. What we should do is pass the link headers to the agent to make sure that if it sees a redirect in the link header, it does the right thing, correct?

**AI Response**

You're absolutely right! I've fallen into the trap of creating traditional Software 1.0 code rather than leveraging the agent's capabilities. Let's refocus on the Software 2.0 approach where the agent discovers and handles the link headers.

Instead of hardcoding the logic for handling link headers, we should:

1. Include the link headers in the information passed to the LLM agent
2. Let the agent analyze those headers and determine the appropriate action
3. Have the agent guide the next steps based on its understanding of linked data patterns

Here's how we could modify our approach:

```python
def agentic_analyze_response(uri, response_data):
    """Have the agent analyze an HTTP response and determine next steps."""
    
    system_prompt = """
    You are an expert in Linked Open Data (LOD) and semantic web technologies.
    Your task is to analyze HTTP responses and determine how to extract or locate 
    machine-readable data. Pay special attention to Link headers, which often point 
    to alternate representations.
    """
    
    user_prompt = f"""
    I've received a response from {uri} with the following information:

    Status code: {response_data['status_code']}
    Content type: {response_data['content_type']}
    
    Headers:
    {json.dumps(dict(response_data['headers']), indent=2)}
    
    Based on this response, please:
    
    1. Analyze if there's machine-readable data directly available in this response
    2. Check if there are Link headers pointing to alternate representations
    3. Determine if there are other indicators of where to find structured data
    4. Recommend the next action to take to retrieve machine-readable data
    
    Return your analysis as a JSON object with these fields:
    - has_data: Boolean indicating if machine-readable data is directly available
    - data_location: Where to find the data ("direct", "link_header", "embedded", etc.)
    - next_action: Object describing what to do next (URL to fetch, content to parse, etc.)
    - reasoning: Brief explanation of your recommendation
    
    Return only the JSON object, no other text.
    """
    
    # Create a chat instance
    chat = Chat(model, sp=system_prompt)
    
    # Get the analysis from Claude
    response = chat(user_prompt)
    
    # Extract and parse the JSON response
    try:
        import re
        import json
        
        # Extract the text from the Message object
        content_text = ""
        for content_item in response.content:
            if hasattr(content_item, 'text'):
                content_text += content_item.text
        
        # Find JSON-like structure in the response
        json_match = re.search(r'```json\s*(.*?)\s*```', content_text, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            json_str = content_text
        
        # Clean up the string to ensure it's valid JSON
        json_str = re.sub(r'```.*?```', '', json_str, flags=re.DOTALL)
        json_str = json_str.strip()
        
        # Parse the JSON
        analysis = json.loads(json_str)
        return analysis
    except Exception as e:
        print(f"Error parsing LLM response: {e}")
        print(f"Raw response: {str(response)[:500]}")  # Print first 500 chars
        return {
            "has_data": False,
            "data_location": "unknown",
            "next_action": {"type": "error", "message": "Failed to parse LLM response"},
            "reasoning": "Error in processing response"
        }
```

Then we could integrate this into our workflow:

```python
def test_agentic_link_header_handling():
    """Test agent's ability to discover and follow link headers."""
    uri = "https://schema.org/"
    
    print(f"\n\nTesting agent's handling of: {uri}")
    
    # Step 1: Initial request
    response = httpx.get(uri, headers={"Accept": "application/ld+json"}, follow_redirects=True)
    
    # Step 2: Prepare response data for agent analysis
    response_data = {
        "status_code": response.status_code,
        "content_type": response.headers.get('Content-Type', ''),
        "headers": dict(response.headers),
        "url": str(response.url),
        "content_preview": response.text[:500]
    }
    
    # Step 3: Let the agent analyze the response
    analysis = agentic_analyze_response(uri, response_data)
    print("\nAgent's analysis:")
    print(json.dumps(analysis, indent=2))
    
    # Step 4: Follow the agent's recommendation
    if analysis.get("next_action", {}).get("type") == "fetch":
        next_url = analysis["next_action"].get("url")
        if next_url:
            print(f"\nFollowing agent's recommendation to fetch: {next_url}")
            follow_up = httpx.get(next_url, follow_redirects=True)
            print(f"Status: {follow_up.status_code}")
            print(f"Content type: {follow_up.headers.get('Content-Type', '')}")
            
            try:
                data = follow_up.json()
                print(f"Successfully retrieved JSON data with keys: {list(data.keys())}")
            except:
                print("Response was not valid JSON")
    else:
        print(f"\nAgent recommended action: {analysis.get('next_action', {}).get('type')}")
```

This approach lets the agent discover the link headers and decide how to handle them, rather than us hardcoding the logic. It's a much better example of the Software 2.0 approach we're aiming for.

What do you think? Should we implement this and test it with Schema.org?

In [ ]:
def agentic_analyze_response(uri, response_data):
    """Have the agent analyze an HTTP response and determine next steps."""
    import json  # Explicitly import inside the function to ensure availability
    import re    # Also import re since we use it later
    
    system_prompt = """
    You are an expert in Linked Open Data (LOD) and semantic web technologies.
    Your task is to analyze HTTP responses and determine how to extract or locate 
    machine-readable data. Pay special attention to Link headers, which often point 
    to alternate representations.
    """
    
    user_prompt = f"""
    I've received a response from {uri} with the following information:

    Status code: {response_data['status_code']}
    Content type: {response_data['content_type']}
    
    Headers:
    {json.dumps(dict(response_data['headers']), indent=2)}
    
    Based on this response, please:
    
    1. Analyze if there's machine-readable data directly available in this response
    2. Check if there are Link headers pointing to alternate representations
    3. Determine if there are other indicators of where to find structured data
    4. Recommend the next action to take to retrieve machine-readable data
    
    Return your analysis as a JSON object with these fields:
    - has_data: Boolean indicating if machine-readable data is directly available
    - data_location: Where to find the data ("direct", "link_header", "embedded", etc.)
    - next_action: Object describing what to do next (URL to fetch, content to parse, etc.)
    - reasoning: Brief explanation of your recommendation
    
    Return only the JSON object, no other text.
    """
    
    # Create a chat instance
    chat = Chat(model, sp=system_prompt)
    
    # Get the analysis from Claude
    response = chat(user_prompt)
    
    # Extract and parse the JSON response
    try:
        # Extract the text from the Message object
        content_text = ""
        for content_item in response.content:
            if hasattr(content_item, 'text'):
                content_text += content_item.text
        
        # Find JSON-like structure in the response
        json_match = re.search(r'```json\s*(.*?)\s*```', content_text, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            json_str = content_text
        
        # Clean up the string to ensure it's valid JSON
        json_str = re.sub(r'```.*?```', '', json_str, flags=re.DOTALL)
        json_str = json_str.strip()
        
        # Parse the JSON
        analysis = json.loads(json_str)
        return analysis
    except Exception as e:
        print(f"Error parsing LLM response: {e}")
        print(f"Raw response: {str(response)[:500]}")  # Print first 500 chars
        return {
            "has_data": False,
            "data_location": "unknown",
            "next_action": {"type": "error", "message": "Failed to parse LLM response"},
            "reasoning": "Error in processing response"
        }

In [ ]:
def test_agentic_link_header_handling():
    """Test agent's ability to discover and follow link headers."""
    uri = "https://schema.org/"
    
    print(f"\n\nTesting agent's handling of: {uri}")
    
    # Step 1: Initial request
    response = httpx.get(uri, headers={"Accept": "application/ld+json"}, follow_redirects=True)
    
    # Step 2: Prepare response data for agent analysis
    response_data = {
        "status_code": response.status_code,
        "content_type": response.headers.get('Content-Type', ''),
        "headers": dict(response.headers),
        "url": str(response.url),
        "content_preview": response.text[:500]
    }
    
    # Step 3: Let the agent analyze the response
    analysis = agentic_analyze_response(uri, response_data)
    print("\nAgent's analysis:")
    print(json.dumps(analysis, indent=2))
    
    # Step 4: Follow the agent's recommendation
    if analysis.get("next_action", {}).get("type") == "fetch":
        next_url = analysis["next_action"].get("url")
        if next_url:
            print(f"\nFollowing agent's recommendation to fetch: {next_url}")
            follow_up = httpx.get(next_url, follow_redirects=True)
            print(f"Status: {follow_up.status_code}")
            print(f"Content type: {follow_up.headers.get('Content-Type', '')}")
            
            try:
                data = follow_up.json()
                print(f"Successfully retrieved JSON data with keys: {list(data.keys())}")
            except:
                print("Response was not valid JSON")
    else:
        print(f"\nAgent recommended action: {analysis.get('next_action', {}).get('type')}")

In [ ]:
test_agentic_link_header_handling()



Testing agent's handling of: https://schema.org/

Agent's analysis:
{
  "has_data": false,
  "data_location": "link_header",
  "next_action": {
    "action": "fetch",
    "url": "https://schema.org/docs/jsonldcontext.jsonld",
    "expected_type": "application/ld+json"
  },
  "reasoning": "The response is HTML but includes a Link header pointing to a JSON-LD context document. The Link header specifies an alternate representation in application/ld+json format, which is machine-readable. Following this link will provide structured data in JSON-LD format."
}

Agent recommended action: None


**AI Prompt**

Ok. What do we think of our response?

**AI Response**

This is much better! Now we're properly implementing a Software 2.0 approach where the agent is doing the reasoning about how to handle the response.

The agent correctly:

1. Identified that the Schema.org response doesn't contain machine-readable data directly
2. Discovered the Link header pointing to the JSON-LD context document
3. Recommended fetching that alternate representation
4. Provided clear reasoning about why this is the right approach

This is exactly the kind of intelligent processing we want from our agent. Instead of hardcoding rules about how to handle different domains, the agent is analyzing the actual HTTP response and making informed decisions based on web standards.

There's a small issue in our implementation - the next_action field has "action" instead of "type" as we expected in our code, which is why the follow-up request wasn't executed. This highlights an important consideration in agent-based systems: we need to either standardize the output format more strictly or make our processing code more flexible to handle variations in the agent's responses.

The agent-based approach has several advantages over our previous implementation:

1. **Adaptability**: It can handle new link relation types or headers without code changes
2. **Explainability**: It provides reasoning for its decisions
3. **Flexibility**: It can adapt to variations in how different servers implement content negotiation
4. **Learning**: As LLM capabilities improve, the agent will naturally handle more complex cases

This approach is much more aligned with the vision of an agent that can navigate the Linked Open Data cloud autonomously, discovering and following connections between resources.

Would you like to fix the small issue with the action/type field mismatch and see the complete workflow in action?