"""Signs a canonical N-Quads string (URDNA2015) with **Ed25519** and verifies it."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../90_signer.ipynb.

# %% auto 0
__all__ = ['log', 'generate_keypair', 'sign', 'verify']

# %% ../../90_signer.ipynb 3
import base64
from typing import Tuple

from ..core.debug import get_logger
log = get_logger("signer")

try:
    from nacl.signing import SigningKey, VerifyKey           # type: ignore
    from nacl.encoding import RawEncoder
    _HAS_NACL = True
except ModuleNotFoundError:
    _HAS_NACL = False
    log.warning("PyNaCl not installed → signer disabled")

# %% ../../90_signer.ipynb 5
def _b64(b: bytes) -> str: return base64.b64encode(b).decode()
def _unb64(s: str) -> bytes: return base64.b64decode(s.encode())

# %% ../../90_signer.ipynb 7
def generate_keypair() -> Tuple[str, str]:
    """
    Returns `(public_b64, private_b64)`.

    Raises RuntimeError if PyNaCl missing.
    """
    if not _HAS_NACL:
        raise RuntimeError("sign/verify require PyNaCl (pip install pynacl)")
    sk = SigningKey.generate()
    return _b64(sk.verify_key.encode()), _b64(sk.encode())

def sign(normalized_nquads: str, private_key_b64: str) -> str:
    if not _HAS_NACL:
        raise RuntimeError("PyNaCl missing")
    sk = SigningKey(_unb64(private_key_b64), encoder=RawEncoder)
    sig = sk.sign(normalized_nquads.encode()).signature
    return _b64(sig)

def verify(normalized_nquads: str, signature_b64: str, public_key_b64: str) -> bool:
    if not _HAS_NACL:
        raise RuntimeError("PyNaCl missing")
    vk = VerifyKey(_unb64(public_key_b64), encoder=RawEncoder)
    try:
        vk.verify(normalized_nquads.encode(), _unb64(signature_b64))
        return True
    except Exception:
        return False
