"""Validate an Entity (or any N-Quads graph) against SHACL shapes using **pySHACL**."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../91_validator.ipynb.

# %% auto 0
__all__ = ['log', 'validate_entity']

# %% ../../91_validator.ipynb 3
from typing import Union

from ..core.debug import get_logger
from ..core.entity import Entity
from ..core.graph import GraphManager

log = get_logger("validator")

try:
    from pyshacl import validate          # type: ignore
    _HAS_SHACL = True
except ModuleNotFoundError:
    _HAS_SHACL = False
    log.warning("pySHACL not installed → validator disabled")

# %% ../../91_validator.ipynb 5
def validate_entity(target: Union[Entity, str],
                    shapes_graph: str,
                    graph_manager: GraphManager | None = None) -> bool:
    """
    Parameters
    ----------
    target : Entity **or** serialized RDF string (ttl, nt, etc).
    shapes_graph : SHACL shapes as Turtle.
    graph_manager : optional GraphManager if you've already ingested the data.

    Returns True on conformant; False otherwise.
    Raises RuntimeError if pySHACL is unavailable.
    """
    if not _HAS_SHACL:
        raise RuntimeError("pySHACL not installed")

    if isinstance(target, Entity):
        data = target.normalized
    else:
        data = target  # assume serialized RDF

    conforms, _r, _msg = validate(
        data_graph=data,
        shacl_graph=shapes_graph,
        data_graph_format="turtle",  # Use turtle instead of nquads
        shacl_graph_format="turtle",
        inference="rdfs",
        advanced=True,
    )
    return bool(conforms)
