"""The core module provides the foundation for working with linked data in JSON-LD format. It serves as the memory system for LLM agents, enabling them to store, organize, and retrieve knowledge effectively."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['MEMORY_CONTEXT', 'LinkedDataKnowledge', 'summarize_markdown']

# %% ../00_core.ipynb 5
from fastcore.basics import *
from fastcore.meta import *
from fastcore.test import *
import json
from rdflib import Graph
from pyld import jsonld
from typing import List, Dict, Any, Optional, Union
import datetime

# %% ../00_core.ipynb 7
# Add this after the imports
MEMORY_CONTEXT = {
    "@context": {
        "schema": "https://schema.org/",
        "dcat": "http://www.w3.org/ns/dcat#",
        "dcterms": "http://purl.org/dc/terms/",
        "prov": "http://www.w3.org/ns/prov#",
        "void": "http://rdfs.org/ns/void#",
        "did": "https://www.w3.org/ns/did/v1#",
        
        "KnowledgeBase": "schema:Dataset",
        "graphs": {
            "@id": "void:subset",
            "@container": "@id"
        },
        "source": {
            "@id": "dcterms:source",
            "@type": "@id"
        },
        "controller": {
            "@id": "did:controller",
            "@type": "@id"
        },
        "description": "dcterms:description",
        "entityCount": "void:entities",
        "lastUpdated": {
            "@id": "dcterms:modified",
            "@type": "xsd:dateTime"
        },
        "title": "dcterms:title",
        "vocabulary": {
            "@id": "void:vocabulary",
            "@type": "@id"
        }
    }
}

# %% ../00_core.ipynb 11
class LinkedDataKnowledge:
    "Represents a knowledge base of linked data in JSON-LD format"
    def __init__(self, 
                 data:Dict=None, # Initial knowledge data
                ):
        self.data = data or {"@context": {}, "@graph": []}
        
    def __repr__(self): return f"LinkedDataKnowledge with {len(self.data.get('@graph', []))} entities"

# %% ../00_core.ipynb 13
@patch
def _repr_markdown_(self:LinkedDataKnowledge) -> str:
    "Rich markdown representation for notebook display"
    md = [f"## LinkedDataKnowledge"]
    
    # Context summary
    context = self.data.get('@context', {})
    md.append(f"### Context ({len(context)} prefixes)")
    
    # Show the first few context entries
    if context:
        md.append("```json")
        context_preview = dict(list(context.items())[:5])
        if len(context) > 5:
            md.append(json.dumps(context_preview, indent=2) + "\n... and more")
        else:
            md.append(json.dumps(context, indent=2))
        md.append("```")
    
    # Graph summary
    graph = self.data.get('@graph', [])
    md.append(f"### Graph ({len(graph)} entities)")
    
    # Show types of entities in the graph
    if graph:
        types = {}
        for entity in graph:
            entity_type = entity.get('@type')
            if isinstance(entity_type, list):
                for t in entity_type:
                    types[t] = types.get(t, 0) + 1
            elif entity_type:
                types[entity_type] = types.get(entity_type, 0) + 1
        
        if types:
            md.append("**Entity types:**")
            for t, count in sorted(types.items(), key=lambda x: x[1], reverse=True):
                md.append(f"- {t}: {count}")
    
    # Show a sample entity if available
    if graph:
        md.append("\n**Sample entity:**")
        md.append("```json")
        md.append(json.dumps(graph[0], indent=2))
        md.append("```")
    
    # If using @included, show that too
    if '@included' in self.data:
        included = self.data['@included']
        md.append(f"\n### Included ({len(included)} entities)")
        md.append("**Types of included entities:**")
        
        # Count types of included entities
        included_types = {}
        for entity in included:
            entity_type = entity.get('@type')
            if isinstance(entity_type, list):
                for t in entity_type:
                    included_types[t] = included_types.get(t, 0) + 1
            elif entity_type:
                included_types[entity_type] = included_types.get(entity_type, 0) + 1
        
        for t, count in sorted(included_types.items(), key=lambda x: x[1], reverse=True):
            md.append(f"- {t}: {count}")
    
    return "\n".join(md)


# %% ../00_core.ipynb 14
# Fix the _format_entity_markdown function (as a standalone function, not patched)
def _format_entity_markdown(entity:Dict) -> str:
    "Format a single entity as markdown with proper string handling"
    md = []
    
    # Entity ID and type
    entity_id = entity.get('@id', 'No ID')
    entity_type = entity.get('@type', ['Unknown'])
    if isinstance(entity_type, list):
        entity_type = ', '.join(entity_type)
    
    md.append(f"### {entity_type}: {entity_id}")
    
    # Properties
    for prop, values in entity.items():
        if prop in ['@id', '@type']: continue
            
        # Format the property name
        prop_name = prop.split('/')[-1] if '/' in prop else prop
        md.append(f"**{prop_name}**:")
        
        # Handle different value types properly
        if isinstance(values, str):
            md.append(f"- {values}")
        elif isinstance(values, list):
            for val in values:
                if isinstance(val, dict):
                    if '@value' in val:
                        value_text = val['@value']
                        if '@language' in val:
                            value_text += f" @{val['@language']}"
                        md.append(f"- {value_text}")
                    elif '@id' in val:
                        md.append(f"- [{val['@id']}]({val['@id']})")
                    else:
                        md.append(f"- {val}")
                else:
                    md.append(f"- {val}")
        else:
            md.append(f"- {values}")
    
    return "\n".join(md)

# %% ../00_core.ipynb 15
@patch
def query_markdown(self:LinkedDataKnowledge,
                  query_type:str, # Type of query: "property", "type", "value" 
                  query_value:str, # Value to search for
                  ) -> str:
    "Query the knowledge base and return results as markdown"
    results = self.query(query_type, query_value)
    
    if not results:
        return f"*No results found for {query_type}='{query_value}'*"
    
    md = [f"# Query Results: {query_type}='{query_value}'", 
          f"Found {len(results)} matching entities"]
    
    # Format each result entity
    for i, entity in enumerate(results[:5]):  # Limit to first 5 for readability
        md.append(f"\n## Result {i+1}")
        md.append(_format_entity_markdown(entity))
    
    if len(results) > 5:
        md.append(f"\n*...and {len(results)-5} more results*")
    
    return "\n".join(md)

# %% ../00_core.ipynb 16
@patch
def initialize_memory_structure(self:LinkedDataKnowledge) -> 'LinkedDataKnowledge':
    "Initialize the knowledge base with a standard memory structure"
    if not hasattr(self, 'graphs'):
        self.graphs = {}
    
    self.data = {
        "@context": MEMORY_CONTEXT["@context"],
        "@id": "did:cogitarelink:kb",
        "@type": "KnowledgeBase",
        "title": "Cogitarelink Knowledge Base",
        "description": "A decentralized knowledge system for AI agent reasoning",
        "controller": "did:cogitarelink:agent:primary",
        "graphs": {}
    }
    
    return self

# %% ../00_core.ipynb 18
@patch
def add_named_graph(self:LinkedDataKnowledge, 
                   graph_id:str, # DID or URI for the graph
                   graph_data:dict, # JSON-LD data for the graph
                   metadata:dict=None # Optional metadata about the graph
                  ) -> 'LinkedDataKnowledge':
    "Add a named graph to the knowledge base"
    if not hasattr(self, 'graphs'):
        self.initialize_memory_structure()
    
    if not graph_id.startswith(('did:', 'http://', 'https://')):
        graph_id = f"did:cogitarelink:graph:{graph_id}"
    
    if metadata is None:
        metadata = {}
    
    entity_count = len(graph_data.get('@graph', []))
    
    if 'title' not in metadata:
        metadata['title'] = f"Graph {graph_id.split(':')[-1]}"
    if 'description' not in metadata:
        metadata['description'] = f"Graph containing {entity_count} entities"
    if 'entityCount' not in metadata:
        metadata['entityCount'] = entity_count
    if 'lastUpdated' not in metadata:
        metadata['lastUpdated'] = datetime.datetime.now().isoformat()
    
    self.graphs[graph_id] = {
        'data': graph_data,
        'metadata': metadata
    }
    
    self.data['graphs'][graph_id] = {
        "@id": graph_id,
        "@type": "void:Dataset",
        **metadata
    }
    
    return self

# %% ../00_core.ipynb 19
@patch
def get_named_graph(self:LinkedDataKnowledge, 
                   graph_id:str # DID or URI for the graph
                  ) -> dict:
    "Retrieve a named graph from the knowledge base"
    if not hasattr(self, 'graphs'):
        return None
    
    if not graph_id.startswith(('did:', 'http://', 'https://')):
        graph_id = f"did:cogitarelink:graph:{graph_id}"
    
    if graph_id in self.graphs:
        return self.graphs[graph_id]['data']
    
    return None


# %% ../00_core.ipynb 22
@patch
def use_included(self:LinkedDataKnowledge,
                main_entity:Dict, # Main entity to focus on
                related_entities:List[Dict], # Related entities to include
                preserve_structure:bool=False # Whether to preserve existing structure
                ) -> 'LinkedDataKnowledge':
    "Structure knowledge using @included for related entities"
    if preserve_structure:
        new_data = {k: v for k, v in self.data.items() if k not in ['@included']}
        new_data['@included'] = related_entities
        
        if '@graph' in new_data:
            main_id = main_entity.get('@id')
            if main_id:
                existing_entities = [e for e in new_data['@graph'] if e.get('@id') == main_id]
                if existing_entities:
                    for entity in new_data['@graph']:
                        if entity.get('@id') == main_id:
                            for k, v in main_entity.items():
                                entity[k] = v
                else:
                    new_data['@graph'].append(main_entity)
            else:
                new_data['@graph'].append(main_entity)
        else:
            new_data['@graph'] = [main_entity]
    else:
        new_data = {
            "@context": self.data.get("@context", {}),
            **main_entity,
            "@included": related_entities
        }
    
    self.data = new_data
    return self

# %% ../00_core.ipynb 24
@patch
def structure_with_containers(self:LinkedDataKnowledge,
                             property_name:str, # Property to structure
                             container_type:str, # Type: "set", "list", "language", "id", "type"
                             items:List=None, # Items to include, or None to use existing
                             base_uri:str="https://example.org/" # Base URI for properties
                             ) -> 'LinkedDataKnowledge':
    "Structure a property using JSON-LD 1.1 container features"
    container_mapping = {
        "set": "@set",
        "list": "@list",
        "language": "@language",
        "id": "@id",
        "type": "@type"
    }
    
    container = container_mapping.get(container_type)
    if not container:
        raise ValueError(f"Unknown container type: {container_type}")
    
    container_context = {
        "@version": 1.1,
        property_name: {
            "@id": f"{base_uri}{property_name}",
            "@container": container
        }
    }
    
    if '@context' not in self.data:
        self.data['@context'] = {}
    self.data['@context'].update(container_context)
    
    if items is not None:
        if container_type in ["set", "list"]:
            self.data[property_name] = items
        elif container_type == "language":
            self.data[property_name] = {item["lang"]: item["value"] for item in items}
        elif container_type == "id":
            self.data[property_name] = {item["id"]: item["value"] for item in items}
        elif container_type == "type":
            self.data[property_name] = {item["type"]: item["value"] for item in items}
    
    return self


# %% ../00_core.ipynb 28
# # Test find_entity_across_graphs
# kb_search = LinkedDataKnowledge()
# kb_search.initialize_memory_structure()

# # Add entities to main graph
# kb_search.data["@graph"] = [
#     {"@id": "ex:main1", "@type": "ex:MainEntity", "rdfs:label": "Main Entity 1"},
#     {"@id": "ex:main2", "@type": "ex:MainEntity", "rdfs:label": "Main Entity 2"}
# ]

# # Add a named graph with more entities
# graph1_data = {
#     "@graph": [
#         {"@id": "ex:graph1_entity1", "@type": "ex:GraphEntity", "rdfs:label": "Graph 1 Entity 1"},
#         {"@id": "ex:graph1_entity2", "@type": "ex:GraphEntity", "rdfs:label": "Graph 1 Entity 2"}
#     ]
# }
# kb_search.add_named_graph("graph1", graph1_data)

# # Add another named graph
# graph2_data = {
#     "@graph": [
#         {"@id": "ex:graph2_entity1", "@type": "ex:GraphEntity", "rdfs:label": "Graph 2 Entity 1"},
#         {"@id": "ex:main1", "@type": "ex:DuplicateEntity", "rdfs:label": "Duplicate Main Entity"}
#     ]
# }
# kb_search.add_named_graph("graph2", graph2_data)

# # Test search across all graphs
# all_entities = kb_search.find_entity_across_graphs(term_type="ex:GraphEntity")
# test_eq(len(all_entities), 3)  # Should find all 3 GraphEntity instances

# # Test search in specific graph
# graph1_entities = kb_search.find_entity_across_graphs(
#     term_type="ex:GraphEntity",
#     graph_id="did:cogitarelink:graph:graph1",
#     include_main_graph=False
# )
# test_eq(len(graph1_entities), 2)  # Should find only the 2 in graph1

# # Test finding by ID across graphs
# main_entities = kb_search.find_entity_across_graphs(entity_id="ex:main1")
# test_eq(len(main_entities), 2)  # Should find in both main graph and graph2

# # Test finding by label
# label_entities = kb_search.find_entity_across_graphs(label="Main Entity")
# test_eq(len(label_entities), 3)  # Updated: finds 3 entities with "Main Entity" in the label


# %% ../00_core.ipynb 30
@patch
def _has_type(self:LinkedDataKnowledge, entity:dict, type_str:str) -> bool:
    """Check if entity has the specified type, handling various type formats."""
    if not entity or not type_str:
        return False
        
    entity_types = entity.get('@type', [])
    if not isinstance(entity_types, list):
        entity_types = [entity_types]
    
    # Handle empty types
    if not entity_types:
        return False
    
    # Try exact match first (most efficient)
    if type_str in entity_types:
        return True
    
    # For prefixed names like "rdfs:Class" or "rdf:Property", try direct string matching
    # This handles cases where the prefix isn't in the context but is used in entity types
    if ':' in type_str and any(t.endswith(type_str.split(':')[1]) for t in entity_types):
        return True
    
    # Prepare for URI and prefixed name handling
    context = self.data.get('@context', {})
    
    # Standard RDF prefixes that might not be in the context
    standard_prefixes = {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "owl": "http://www.w3.org/2002/07/owl#",
        "xsd": "http://www.w3.org/2001/XMLSchema#"
    }
    
    # Add standard prefixes to context if not already present
    for prefix, uri in standard_prefixes.items():
        if prefix not in context:
            context[prefix] = uri
    
    # Convert type_str to expanded URI if it's a prefixed name
    expanded_type_str = None
    if ':' in type_str and not type_str.startswith(('http://', 'https://')):
        prefix, local = type_str.split(':', 1)
        if prefix in context:
            prefix_uri = context[prefix]
            if isinstance(prefix_uri, str):
                if prefix_uri.endswith('/') or prefix_uri.endswith('#'):
                    expanded_type_str = f"{prefix_uri}{local}"
                else:
                    expanded_type_str = f"{prefix_uri}/{local}"
    
    # Convert entity_types to expanded URIs and prefixed names for comparison
    for entity_type in entity_types:
        # Check if expanded type_str matches entity_type
        if expanded_type_str and (expanded_type_str == entity_type or expanded_type_str in entity_type):
            return True
            
        # If entity_type is a full URI and type_str is a prefixed name
        if entity_type.startswith(('http://', 'https://')) and ':' in type_str and not type_str.startswith(('http://', 'https://')):
            # Extract the local name from the URI to match against prefixed name
            for prefix, uri in context.items():
                if isinstance(uri, str) and entity_type.startswith(uri):
                    local_part = entity_type[len(uri):]
                    if local_part.startswith('/') or local_part.startswith('#'):
                        local_part = local_part[1:]
                    prefixed = f"{prefix}:{local_part}"
                    if prefixed == type_str:
                        return True
                        
        # If type_str is a full URI and entity_type is a prefixed name
        if type_str.startswith(('http://', 'https://')) and ':' in entity_type and not entity_type.startswith(('http://', 'https://')):
            prefix, local = entity_type.split(':', 1)
            if prefix in context:
                prefix_uri = context[prefix]
                if isinstance(prefix_uri, str):
                    if prefix_uri.endswith('/') or prefix_uri.endswith('#'):
                        expanded = f"{prefix_uri}{local}"
                    else:
                        expanded = f"{prefix_uri}/{local}"
                    if expanded == type_str or expanded in type_str:
                        return True
    
    # Check for local name match (e.g., "Class" matches "rdfs:Class" or "http://.../Class")
    if not type_str.startswith(('http://', 'https://')) and not ':' in type_str:
        # Check if any type ends with the local name
        if any(t.split('/')[-1] == type_str or 
               t.split('#')[-1] == type_str or
               ((':' in t) and t.split(':')[-1] == type_str)
               for t in entity_types):
            return True
    
    # Finally, try substring match as a fallback
    # This is less reliable but catches some edge cases
    return any(type_str in t for t in entity_types)


# %% ../00_core.ipynb 31
@patch
def display_entity(self:LinkedDataKnowledge, entity_id:str) -> str:
    "Display a specific entity by ID as markdown"
    
    # First try in @graph
    for entity in self.data.get('@graph', []):
        if entity.get('@id') == entity_id:
            return _format_entity_markdown(entity)
    
    # Then try in @included if present
    for entity in self.data.get('@included', []):
        if entity.get('@id') == entity_id:
            return _format_entity_markdown(entity)
    
    # If it's the main entity in a resource-centric view
    if self.data.get('@id') == entity_id:
        return _format_entity_markdown(self.data)
    
    return f"*Entity with ID '{entity_id}' not found*"

# %% ../00_core.ipynb 32
def summarize_markdown(self:LinkedDataKnowledge) -> str:
    "Provide a concise markdown summary of the knowledge base"
    
    md = ["# Knowledge Base Summary"]
    
    # Count contexts, entities, and included entities
    context_count = len(self.data.get('@context', {}))
    graph_count = len(self.data.get('@graph', []))
    included_count = len(self.data.get('@included', [])) if '@included' in self.data else 0
    
    md.append(f"- **Contexts:** {context_count}")
    md.append(f"- **Graph Entities:** {graph_count}")
    if included_count:
        md.append(f"- **Included Entities:** {included_count}")
    
    # Summarize entity types
    all_types = {}
    
    # Check @graph
    for entity in self.data.get('@graph', []):
        entity_type = entity.get('@type')
        if isinstance(entity_type, list):
            for t in entity_type:
                all_types[t] = all_types.get(t, 0) + 1
        elif entity_type:
            all_types[entity_type] = all_types.get(entity_type, 0) + 1
    
    # Check @included
    for entity in self.data.get('@included', []):
        entity_type = entity.get('@type')
        if isinstance(entity_type, list):
            for t in entity_type:
                all_types[t] = all_types.get(t, 0) + 1
        elif entity_type:
            all_types[entity_type] = all_types.get(entity_type, 0) + 1
    
    # Check main entity if resource-centric
    if '@id' in self.data and '@type' in self.data:
        entity_type = self.data.get('@type')
        if isinstance(entity_type, list):
            for t in entity_type:
                all_types[t] = all_types.get(t, 0) + 1
        elif entity_type:
            all_types[entity_type] = all_types.get(entity_type, 0) + 1
    
    if all_types:
        md.append("\n## Entity Types")
        for t, count in sorted(all_types.items(), key=lambda x: x[1], reverse=True)[:10]:
            md.append(f"- **{t}**: {count}")
        if len(all_types) > 10:
            md.append(f"- *...and {len(all_types)-10} more types*")
    
    return "\n".join(md)


# %% ../00_core.ipynb 34
@patch
def find_entity_by_id(self:LinkedDataKnowledge, 
                     entity_id:str, # Entity ID to find (full URI or segment)
                     term_type:str=None, # Optional type filter
                     case_sensitive:bool=False, # Whether to use case-sensitive matching
                     debug:bool=False # Enable debug output
                    ) -> list: # Matching entities
    "Find entities by ID only (exact URI or final path segment)"
    results = []
    graph = self.data.get('@graph', [])
    
    if debug: print(f"ID lookup: '{entity_id}', type='{term_type}'")
    
    if not case_sensitive: entity_id = entity_id.lower()
    
    for entity in graph:
        if debug: print(f"\nChecking entity: {entity.get('@id')}")
        
        if term_type and not self._has_type(entity, term_type): 
            if debug: print(f"  ✗ Type mismatch: not a {term_type}")
            continue
        
        if isinstance(entity.get('@id'), str):
            entity_uri = entity.get('@id')
            
            if not case_sensitive: compare_uri = entity_uri.lower()
            else: compare_uri = entity_uri
            
            if debug: print(f"  Checking ID: '{entity_id}' against '{compare_uri}'")
            
            # Exact match for full URI
            if entity_id == compare_uri:
                if debug: print(f"  ✓ Full URI match")
                results.append(entity)
            # Match exact final segment after / 
            elif '/' in compare_uri and compare_uri.split('/')[-1] == entity_id:
                if debug: print(f"  ✓ Path segment match: '{compare_uri.split('/')[-1]}'")
                results.append(entity)
            # Match exact final segment after #
            elif '#' in compare_uri and compare_uri.split('#')[-1] == entity_id:
                if debug: print(f"  ✓ Fragment match: '{compare_uri.split('#')[-1]}'")
                results.append(entity)
            # Match exact CURIE local name
            elif ':' in compare_uri:
                local_part = compare_uri.split(':')[-1]
                if debug: print(f"  Checking CURIE local part: '{local_part}'")
                if local_part == entity_id:
                    if debug: print(f"  ✓ CURIE match")
                    results.append(entity)
                else:
                    if debug: print(f"  ✗ CURIE mismatch")
            else:
                if debug: print(f"  ✗ No ID match")
    
    if debug: print(f"\nFound {len(results)} entities by ID")
    return results


# %% ../00_core.ipynb 36
@patch
def find_entity_by_label(self:LinkedDataKnowledge, 
                        label:str, # Label text to search for
                        term_type:str=None, # Optional type filter
                        case_sensitive:bool=False, # Whether to use case-sensitive matching
                        exact_match:bool=False, # Require exact label match (not substring)
                        debug:bool=False # Enable debug output
                       ) -> list: # Matching entities
    "Find entities by label (supports substring or exact matching)"
    results = []
    graph = self.data.get('@graph', [])
    
    if debug: print(f"Label search: '{label}', type='{term_type}', exact={exact_match}")
    
    if not case_sensitive: label = label.lower()
    
    for entity in graph:
        if debug: print(f"\nChecking entity: {entity.get('@id')}")
        
        if term_type and not self._has_type(entity, term_type): 
            if debug: print(f"  ✗ Type mismatch: not a {term_type}")
            continue
        
        matched = False
        
        if debug: print(f"  Checking labels for: '{label}'")
        
        for key, value in entity.items():
            if 'label' in key.lower():
                if isinstance(value, list):
                    for item in value:
                        if isinstance(item, dict) and '@value' in item:
                            item_value = str(item.get('@value', ''))
                            if not case_sensitive: item_value = item_value.lower()
                            
                            if (exact_match and item_value == label) or (not exact_match and label in item_value):
                                if debug: print(f"  ✓ Label match in @value: '{item_value}'")
                                results.append(entity)
                                matched = True
                                break
                        else:
                            item_str = str(item)
                            if not case_sensitive: item_str = item_str.lower()
                                
                            if (exact_match and item_str == label) or (not exact_match and label in item_str):
                                if debug: print(f"  ✓ Label match in list item: '{item_str}'")
                                results.append(entity)
                                matched = True
                                break
                elif isinstance(value, str):
                    if not case_sensitive: compare_value = value.lower()
                    else: compare_value = value
                        
                    if (exact_match and compare_value == label) or (not exact_match and label in compare_value):
                        if debug: print(f"  ✓ Label match: '{compare_value}'")
                        results.append(entity)
                        matched = True
                        break
        
        if not matched and debug: print(f"  ✗ No label match")
    
    if debug: print(f"\nFound {len(results)} entities by label")
    return results


# %% ../00_core.ipynb 37
@patch
def find_entity(self:LinkedDataKnowledge, 
               entity_id:str=None, # Entity ID to find
               term_type:str=None, # Type filter
               label:str=None, # Label text to search for
               match_both:bool=False, # Require both ID and label to match (if both provided)
               case_sensitive:bool=False, # Use case-sensitive matching
               debug:bool=False # Enable debug output
              ) -> list: # Matching entities
    "Find entities by ID, label, or both with clear matching logic"
    if debug: print(f"Combined search: ID='{entity_id}', label='{label}', type='{term_type}', match_both={match_both}")
    
    # Handle the case where only one parameter is provided
    if entity_id and not label:
        return self.find_entity_by_id(entity_id, term_type, case_sensitive, debug)
    
    if label and not entity_id:
        return self.find_entity_by_label(label, term_type, case_sensitive, False, debug)
    
    # Handle the case where both ID and label are provided
    if entity_id and label:
        id_results = self.find_entity_by_id(entity_id, term_type, case_sensitive, debug)
        label_results = self.find_entity_by_label(label, term_type, case_sensitive, False, debug)
        
        if match_both:
            # Find intersection of results (entities that match both criteria)
            id_set = {entity.get('@id') for entity in id_results}
            combined = [entity for entity in label_results if entity.get('@id') in id_set]
            if debug: print(f"\nFound {len(combined)} entities matching both ID and label")
            return combined
        else:
            # Find union of results (entities that match either criteria)
            seen = set()
            combined = []
            for entity in id_results + label_results:
                entity_id = entity.get('@id')
                if entity_id not in seen:
                    seen.add(entity_id)
                    combined.append(entity)
            if debug: print(f"\nFound {len(combined)} entities matching either ID or label")
            return combined
    
    # Handle the case where only term_type is provided
    if term_type and not entity_id and not label:
        results = []
        for entity in self.data.get('@graph', []):
            if self._has_type(entity, term_type):
                results.append(entity)
        if debug: print(f"\nFound {len(results)} entities of type {term_type}")
        return results
    
    return []


# %% ../00_core.ipynb 40
@patch
def find_entity_across_graphs(self:LinkedDataKnowledge, 
                             entity_id:str=None, # Entity ID to find
                             term_type:str=None, # Filter by type
                             label:str=None, # Label text to search for
                             graph_id:str=None, # Specific graph to search, or None for all
                             include_main_graph:bool=True, # Whether to include the main graph
                             match_both:bool=False, # Require both ID and label to match
                             case_sensitive:bool=False, # Use case-sensitive matching
                             debug:bool=False # Enable debug output
                            ) -> list:
    "Find entities across all graphs or in a specific graph"
    if debug: print(f"Searching across graphs: ID='{entity_id}', label='{label}', type='{term_type}'")
    results = []
    
    if include_main_graph:
        if debug: print("Searching main graph...")
        # Use the appropriate find method based on what parameters are provided
        if entity_id and not label:
            main_results = self.find_entity_by_id(entity_id, term_type, case_sensitive, debug)
        elif label and not entity_id:
            main_results = self.find_entity_by_label(label, term_type, case_sensitive, False, debug)
        elif entity_id and label:
            main_results = self.find_entity(entity_id, term_type, label, match_both, case_sensitive, debug)
        elif term_type:
            main_results = self.find_entity(term_type=term_type, debug=debug)
        else:
            main_results = []
            
        if debug: print(f"Found {len(main_results)} entities in main graph")
        results.extend(main_results)
    
    if hasattr(self, 'graphs'):
        graphs_to_search = [graph_id] if graph_id else self.graphs.keys()
        
        for gid in graphs_to_search:
            if gid in self.graphs:
                if debug: print(f"Searching graph {gid}...")
                graph_data = self.graphs[gid]['data']
                temp_kb = LinkedDataKnowledge(graph_data)
                
                # Use the appropriate find method based on what parameters are provided
                if entity_id and not label:
                    graph_results = temp_kb.find_entity_by_id(entity_id, term_type, case_sensitive, debug)
                elif label and not entity_id:
                    graph_results = temp_kb.find_entity_by_label(label, term_type, case_sensitive, False, debug)
                elif entity_id and label:
                    graph_results = temp_kb.find_entity(entity_id, term_type, label, match_both, case_sensitive, debug)
                elif term_type:
                    graph_results = temp_kb.find_entity(term_type=term_type, debug=debug)
                else:
                    graph_results = []
                    
                if debug: print(f"Found {len(graph_results)} entities in graph {gid}")
                results.extend(graph_results)
    
    if debug: print(f"Total: Found {len(results)} entities across all searched graphs")
    return results


# %% ../00_core.ipynb 42
@patch
def get_entity_description(self:LinkedDataKnowledge, entity:dict) -> str:
    "Get a formatted description of an entity"
    if not entity:
        return "No entity provided"
    
    lines = []
    
    # Entity ID
    entity_id = entity.get('@id', 'Unknown ID')
    lines.append(f"## Entity: {entity_id}")
    
    # Entity type
    entity_type = entity.get('@type', [])
    if not isinstance(entity_type, list):
        entity_type = [entity_type]
    lines.append(f"**Type**: {', '.join(entity_type)}")
    
    # Labels
    labels = []
    for key, value in entity.items():
        if 'label' in key.lower():
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, dict) and '@value' in item:
                        labels.append(f"{item.get('@value')} ({item.get('@language', 'no language')})")
                    else:
                        labels.append(str(item))
            else:
                labels.append(str(value))
    
    if labels:
        lines.append(f"**Labels**: {', '.join(labels)}")
    
    # Comments/Definitions
    comments = []
    for key, value in entity.items():
        if 'comment' in key.lower() or 'definition' in key.lower():
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, dict) and '@value' in item:
                        comments.append(item.get('@value'))
                    else:
                        comments.append(str(item))
            else:
                comments.append(str(value))
    
    if comments:
        lines.append("\n**Definition**:")
        for comment in comments:
            lines.append(f"- {comment}")
    
    # Relationships
    relationships = []
    for key, value in entity.items():
        if key not in ['@id', '@type'] and not any(x in key.lower() for x in ['label', 'comment', 'definition']):
            relationships.append((key, value))
    
    if relationships:
        lines.append("\n**Relationships**:")
        for rel_name, rel_value in relationships:
            if isinstance(rel_value, list):
                lines.append(f"- {rel_name}:")
                for item in rel_value:
                    if isinstance(item, dict) and '@id' in item:
                        lines.append(f"  - {item['@id']}")
                    elif isinstance(item, dict) and '@value' in item:
                        lines.append(f"  - {item['@value']}")
                    else:
                        lines.append(f"  - {item}")
            else:
                if isinstance(rel_value, dict) and '@id' in rel_value:
                    lines.append(f"- {rel_name}: {rel_value['@id']}")
                elif isinstance(rel_value, dict) and '@value' in rel_value:
                    lines.append(f"- {rel_name}: {rel_value['@value']}")
                else:
                    lines.append(f"- {rel_name}: {rel_value}")
    
    return "\n".join(lines)


# %% ../00_core.ipynb 45
@patch
def describe(self:LinkedDataKnowledge, path:str="") -> str:
    "Describe the structure at the given path in a human-readable format"
    if not path:
        # Describe the overall knowledge base structure
        result = ["# Knowledge Base Structure"]
        
        # Context information
        context = self.data.get('@context', {})
        result.append(f"\n## Context ({len(context)} prefixes)")
        if context:
            result.append("Key prefixes:")
            for prefix, uri in list(context.items())[:5]:
                if prefix.startswith('@'): continue
                result.append(f"- `{prefix}`: {uri}")
            if len(context) > 5:
                result.append(f"- ... and {len(context)-5} more")
        
        # Graph information
        graph = self.data.get('@graph', [])
        result.append(f"\n## Graph ({len(graph)} entities)")
        
        # Entity types
        types = {}
        for entity in graph:
            entity_type = entity.get('@type')
            if isinstance(entity_type, list):
                for t in entity_type:
                    types[t] = types.get(t, 0) + 1
            elif entity_type:
                # Fixed: Use entity_type instead of t
                types[entity_type] = types.get(entity_type, 0) + 1
        
        if types:
            result.append("Entity types:")
            for t, count in sorted(types.items(), key=lambda x: x[1], reverse=True)[:10]:
                result.append(f"- {t}: {count} entities")
            if len(types) > 10:
                result.append(f"- ... and {len(types)-10} more types")
        
        # Named graphs
        if hasattr(self, 'graphs') and self.graphs:
            result.append(f"\n## Named Graphs ({len(self.graphs)} graphs)")
            for graph_id, graph_data in list(self.graphs.items())[:5]:
                metadata = graph_data.get('metadata', {})
                title = metadata.get('title', graph_id.split(':')[-1])
                entity_count = metadata.get('entityCount', '?')
                result.append(f"- {title}: {entity_count} entities")
            if len(self.graphs) > 5:
                result.append(f"- ... and {len(self.graphs)-5} more graphs")
    else:
        # Describe a specific path
        parts = path.split('.')
        current = self.data
        
        for part in parts:
            if part in current:
                current = current[part]
            else:
                return f"Path '{path}' not found"
        
        # Describe the object at the path
        if isinstance(current, dict):
            result = [f"# Object at path '{path}'"]
            result.append(f"Type: dictionary with {len(current)} keys")
            result.append("\nKeys:")
            for key in sorted(current.keys())[:10]:
                val = current[key]
                if isinstance(val, dict):
                    result.append(f"- {key}: dict with {len(val)} items")
                elif isinstance(val, list):
                    result.append(f"- {key}: list with {len(val)} items")
                else:
                    val_str = str(val)
                    if len(val_str) > 50:
                        val_str = val_str[:47] + "..."
                    result.append(f"- {key}: {val_str}")
            if len(current) > 10:
                result.append(f"- ... and {len(current)-10} more keys")
        elif isinstance(current, list):
            result = [f"# List at path '{path}'"]
            result.append(f"Type: list with {len(current)} items")
            result.append("\nItems:")
            for i, item in enumerate(current[:5]):
                if isinstance(item, dict):
                    id_str = item.get('@id', f"item {i}")
                    result.append(f"- {id_str}: dict with {len(item)} keys")
                else:
                    item_str = str(item)
                    if len(item_str) > 50:
                        item_str = item_str[:47] + "..."
                    result.append(f"- {item_str}")
            if len(current) > 5:
                result.append(f"- ... and {len(current)-5} more items")
        else:
            result = [f"# Value at path '{path}'"]
            result.append(f"Type: {type(current).__name__}")
            result.append(f"\nValue: {current}")
    
    return "\n".join(result)


# %% ../00_core.ipynb 48
@patch
def view(self:LinkedDataKnowledge, entity_id:str=None, term_type:str=None, label:str=None) -> None:
    "Find and display entities in a rich format using IPython display when available"
    entities = self.find_entity(entity_id, term_type, label)
    if not entities:
        print(f"No entities found matching the criteria")
        return
    
    try:
        # Try to use IPython's display for rich rendering in notebooks
        from IPython.display import display, Markdown
        for entity in entities:
            display(Markdown(self.get_entity_description(entity)))
    except ImportError:
        # Fall back to print if not in an IPython environment
        for entity in entities:
            print(self.get_entity_description(entity))

