# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_memory.ipynb.

# %% auto 0
__all__ = ['SemanticMemory']

# %% ../03_memory.ipynb 3
import json
from pyld import jsonld
import httpx
from rdflib import Graph, Dataset, URIRef, Namespace
from rdflib import Literal as RDFLiteral
from rdflib.namespace import RDF, RDFS
from datetime import datetime
from fastcore.basics import patch
from claudette import Chat, toolloop, models
import time
from pathlib import Path
from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
import pickle
from .vocabtools import register_vocab_aware_loader, compact_entity_with_vocabulary, VOCABULARY_REGISTRY

# %% ../03_memory.ipynb 11
class SemanticMemory:
    def __init__(self, cache_dir=None, preload_vocabs=None):
        "Enhanced initialization with vocabulary support"
        self.dataset = Dataset()
        self.default_graph = self.dataset.graph(URIRef("urn:x-arq:DefaultGraph"))
        self.original_data = {}
        
        self.indices = {"by_id": {}, "by_type": {}, "by_label": {}, "by_keyword": {}, 
                    "by_graph": {}, "by_vocabulary": {}, "containers": {}}
        
        self.contexts = {}
        self.context_registry = {}
        
        self.client = httpx.Client(follow_redirects=True)
        
        self.cache_dir = cache_dir
        if cache_dir: Path(cache_dir).mkdir(exist_ok=True)
        
        register_vocab_aware_loader()
        
        self.preloaded_vocabs = set()
        if preload_vocabs:
            for vocab in preload_vocabs:
                self.preload_vocabulary(vocab)
        else:
            for vocab in ["schema", "dc", "foaf"]:
                self.preload_vocabulary(vocab)


# %% ../03_memory.ipynb 15
@patch
def preload_vocabulary(self:SemanticMemory, vocab_name):
    "Preload a vocabulary to avoid HTTP requests during processing"
    try:
        context = load_context_for_vocabulary(vocab_name)
        self.contexts[vocab_name] = context
        self.preloaded_vocabs.add(vocab_name)
        return True
    except Exception as e:
        print(f"Error preloading vocabulary {vocab_name}: {e}")
        return False
    vocab_to_use = None
    if preferred_vocabs:
        for v in preferred_vocabs:
            if v in entity_vocabs:
                vocab_to_use = v
                break
    
    if not vocab_to_use: vocab_to_use = entity_vocabs[0]
    
    try:
        return compact_entity_with_vocabulary(entity, vocab_to_use)
    except:
        return entity

# %% ../03_memory.ipynb 16
@patch
def _track_vocabulary_usage(self:SemanticMemory, vocabs, data):
    "Track which vocabularies are used by this entity"
    entity_id = data.get("@id")
    if not entity_id: return
    
    # Ensure we have the vocabulary index
    if "by_vocabulary" not in self.indices:
        self.indices["by_vocabulary"] = {}
    
    # Track each vocabulary
    for vocab in vocabs:
        if vocab not in self.indices["by_vocabulary"]:
            self.indices["by_vocabulary"][vocab] = set()
        self.indices["by_vocabulary"][vocab].add(entity_id)

# %% ../03_memory.ipynb 17
@patch
def query_by_vocabulary(self:SemanticMemory, vocab_name, limit=50):
    "Find entities using a specific vocabulary"
    results = []
    
    if "by_vocabulary" in self.indices and vocab_name in self.indices["by_vocabulary"]:
        entity_ids = list(self.indices["by_vocabulary"][vocab_name])[:limit]
        for eid in entity_ids:
            entity = self.query_by_id(eid)
            if entity: results.append(entity)
    
    return results


# %% ../03_memory.ipynb 18
@patch
def compact_with_preferred_vocab(self:SemanticMemory, entity, preferred_vocabs=None):
    "Compact entity using preferred vocabulary"
    if not isinstance(entity, dict) or "@id" not in entity: return entity
    
    entity_vocabs = []
    if "by_vocabulary" in self.indices:
        for vocab, entities in self.indices["by_vocabulary"].items():
            if entity["@id"] in entities:
                entity_vocabs.append(vocab)
    
    if not entity_vocabs: return entity
    

# %% ../03_memory.ipynb 20
@patch
def compact_with_vocabulary(self:SemanticMemory, entity_id, vocab_name):
    """Retrieve an entity and compact it using a specific vocabulary"""
    entity = self.query_by_id(entity_id)
    if not entity: return None
    return compact_entity_with_vocabulary(entity, vocab_name)

# %% ../03_memory.ipynb 21
@patch
def use_vocabulary(self:SemanticMemory, vocab_name):
    """Load and register a vocabulary for use in this memory instance"""
    # This would call VocabTools functions but not depend on VocabTools internals
    context = load_context_for_vocabulary(vocab_name)
    return self._register_context(context)

# %% ../03_memory.ipynb 23
@patch
def _add_to_named_graph(self:SemanticMemory, entity, graph_id):
    "Add processed entity to a named graph"
    import json
    from rdflib import Graph, URIRef
    
    # Skip if no entity ID
    if not isinstance(entity, dict) or "@id" not in entity: return
    
    # Get target graph
    graph_uri = URIRef(graph_id) if isinstance(graph_id, str) else graph_id
    target_graph = self.dataset.graph(graph_uri)
    
    # Add to RDF graph
    g = Graph()
    g.parse(data=json.dumps(entity), format="json-ld")
    target_graph += g
    
    # Update graph index
    if "by_graph" not in self.indices: self.indices["by_graph"] = {}
    if graph_uri not in self.indices["by_graph"]: self.indices["by_graph"][graph_uri] = set()
    self.indices["by_graph"][graph_uri].add(entity["@id"])


# %% ../03_memory.ipynb 25
@patch
def bulk_load(self:SemanticMemory, data_list, graph_id=None, detect_graph=True):
    "Bulk load multiple entities into memory"
    results = []
    
    # Process each item in the list
    for item in data_list:
        # Auto-detect graph ID if requested
        item_graph = None
        if detect_graph and isinstance(item, dict) and "@id" in item:
            item_graph = item.get("@graph", {}).get("@id", None)
        
        # Use provided graph ID if no auto-detected graph
        if not item_graph: item_graph = graph_id
        
        # Add to memory
        result = self.add(item, graph_id=item_graph)
        if result: results.append(result)
    
    return results


# %% ../03_memory.ipynb 27
@patch
def as_container(self:SemanticMemory, entities, container_type="@id", property_name=None, base_context=None):
    "Create a JSON-LD 1.1 container from entities"
    if not entities: return {}
    
    # Create container structure with proper JSON-LD 1.1 context
    result = {"@context": {"@version": 1.1}}
    if base_context: 
        if isinstance(base_context, dict): result["@context"].update(base_context)
        else: result["@context"]["@vocab"] = base_context
    
    # Set up the container definition
    if property_name:
        result["@context"][property_name] = {"@container": container_type}
        result[property_name] = {}
        container = result[property_name]
    else:
        container = {}
    
    # Process based on container type
    if container_type == "@id":
        for entity in entities:
            if "@id" not in entity: continue
            container[entity["@id"]] = entity
    elif container_type == "@type":
        for entity in entities:
            if "@type" not in entity: continue
            types = entity["@type"] if isinstance(entity["@type"], list) else [entity["@type"]]
            for t in types:
                if t not in container: container[t] = []
                container[t].append(entity)
    elif container_type == "@language":
        # Group content by language
        lang_map = {}
        for entity in entities:
            for prop, values in entity.items():
                if prop.startswith("@"): continue
                if isinstance(values, list):
                    for v in values:
                        if isinstance(v, dict) and "@value" in v and "@language" in v:
                            lang = v["@language"]
                            if lang not in lang_map: lang_map[lang] = []
                            lang_map[lang].append({"@id": entity["@id"], prop: v["@value"]})
                
        container.update(lang_map)
    
    # If we used a property name, make sure it's in the result
    if property_name and container:
        result[property_name] = container
    elif not property_name:
        # If no property name, add container directly to result
        for k, v in container.items(): result[k] = v
    
    return result

# %% ../03_memory.ipynb 28
@patch
def as_language_container(self:SemanticMemory, query, text_properties=None):
    "Create a language map from entities with multilingual text"
    entities = self.search(query) if isinstance(query, str) else query
    return self.as_container(entities, container_type="@language")

# %% ../03_memory.ipynb 29
@patch
def as_type_container(self:SemanticMemory, query=None, type_uri=None):
    "Create a type map grouping entities by type"
    if type_uri:
        entities = self.query_by_type(type_uri)
    else:
        entities = self.search(query) if isinstance(query, str) else query
    return self.as_container(entities, container_type="@type")



# %% ../03_memory.ipynb 30
@patch
def as_id_container(self:SemanticMemory, query=None, id_list=None):
    "Create an ID map for direct entity access"
    if id_list:
        entities = [self.query_by_id(id) for id in id_list if self.query_by_id(id)]
    else:
        entities = self.search(query) if isinstance(query, str) else query
    return self.as_container(entities, container_type="@id")


# %% ../03_memory.ipynb 31
@patch
def as_graph_container(self:SemanticMemory, graph_ids=None):
    "Create a @graph container grouping entities by graph"
    result = {"@context": {"@version": 1.1}, "@graph": {}}
    
    # Get all graphs if none specified
    if not graph_ids:
        graph_ids = [str(g.identifier) for g in self.dataset.graphs() 
                   if str(g.identifier) != "urn:x-arq:DefaultGraph"]
    
    # Process each graph
    for graph_id in graph_ids:
        entity_ids = set()
        if "by_graph" in self.indices and URIRef(graph_id) in self.indices["by_graph"]:
            entity_ids = self.indices["by_graph"][URIRef(graph_id)]
        
        # Get entities and add to container
        if entity_ids:
            graph_entities = []
            for eid in entity_ids:
                entity = self.query_by_id(eid)
                if entity: graph_entities.append(entity)
            
            if graph_entities:
                result["@graph"][graph_id] = graph_entities
    
    return result


# %% ../03_memory.ipynb 32
@patch
def store_container(self:SemanticMemory, container, container_id=None):
    "Store a container structure with container-aware indexing"
    if not container_id: 
        import uuid
        container_id = f"urn:container:{uuid.uuid4()}"
    
    # Ensure container has an ID
    if "@id" not in container: container["@id"] = container_id
    
    # Track as a container
    if "containers" not in self.indices: self.indices["containers"] = {}
    self.indices["containers"][container_id] = container
    
    # Add to memory
    return self.add(container, graph_id=container_id)


# %% ../03_memory.ipynb 33
@patch
def get_container(self:SemanticMemory, container_id):
    "Retrieve a previously stored container"
    if "containers" in self.indices and container_id in self.indices["containers"]:
        return self.indices["containers"][container_id]
    return None

# %% ../03_memory.ipynb 36
@patch
def _process_graph(self:SemanticMemory, data):
    """Process a graph structure with multiple entities"""
    if not isinstance(data, dict) or "@graph" not in data: return None
    
    results = []
    shared_ctx = data.get("@context")
    
    # Process each entity
    for entity in data["@graph"]:
        # Skip bare references
        if isinstance(entity, dict) and len(entity) == 1 and "@id" in entity: continue
        
        # Apply shared context if needed
        if shared_ctx and isinstance(entity, dict) and "@context" not in entity:
            entity = dict(entity, **{"@context": shared_ctx})
        
        # Process entity
        result = self._process_entity(entity)
        if result: results.append(result)
    
    return results

# %% ../03_memory.ipynb 37
@patch
def _process_entity(self:SemanticMemory, data):
    """Process a single entity, adding it to indices and graph"""
    import copy, json, uuid
    from rdflib import Graph
    
    if not isinstance(data, dict): return None
    
    # Normalize the entity
    entity = self._normalize_entity(copy.deepcopy(data))
    
    # Ensure ID
    if "@id" not in entity: entity["@id"] = f"urn:uuid:{uuid.uuid4()}"
    entity_id = entity["@id"]
    
    # Store original data
    self.original_data[entity_id] = entity
    
    # Register context and track associations
    if "@context" in entity:
        ctx_id = self._register_context(entity["@context"])
        if ctx_id:
            ctx_info = self.context_registry.setdefault(ctx_id, {"used_by": set()})
            ctx_info["used_by"].add(entity_id)
    
    # Try expanding and indexing
    try:
        expanded = jsonld.expand(entity)
        
        # Update indices
        self._update_indices(expanded)
        
        # Add to RDF graph
        g = Graph()
        g.parse(data=json.dumps(expanded), format="json-ld")
        self.default_graph += g
        
        return expanded
    except Exception as e:
        # Fallback to direct indexing
        print(f"JSON-LD expansion failed: {e}")
        self.indices["by_id"][entity_id] = entity
        
        if "@type" in entity:
            types = [entity["@type"]] if not isinstance(entity["@type"], list) else entity["@type"]
            for t in types:
                if t not in self.indices["by_type"]: self.indices["by_type"][t] = []
                self.indices["by_type"][t].append(entity)
        
        return entity


# %% ../03_memory.ipynb 38
@patch
def _needs_graph_partition(self:SemanticMemory, data):
    """Determine if data needs graph partitioning"""
    if not isinstance(data, dict): return False
    if "@context" in data and isinstance(data["@context"], list) and len(data["@context"]) > 1: return True
    if "credentialSubject" in data and isinstance(data["credentialSubject"], dict): return True
    return False

# %% ../03_memory.ipynb 39
@patch
def _create_graph_partition(self:SemanticMemory, data):
    """Convert document into graph with separate entities for each context"""
    import copy, uuid
    
    # Initialize graph structure
    graph = {"@graph": []}
    contexts = data.get("@context", [])
    if not isinstance(contexts, list): contexts = [contexts]
    
    # Create normalized root entity
    root = self._normalize_entity(copy.deepcopy(data))
    root_id = root.get("@id") or f"urn:uuid:{uuid.uuid4()}"
    root["@id"] = root_id
    
    # Assign first context to root entity
    if contexts and len(contexts) > 0:
        root["@context"] = contexts[0]
    
    # Keep track of processed entities
    processed_ids = set()
    
    # Process an entity and its nested objects
    def process_entity(entity, ctx_index=0):
        if not isinstance(entity, dict): return entity
        
        # Ensure ID
        entity_id = entity.get("@id")
        if not entity_id:
            entity_id = f"urn:uuid:{uuid.uuid4()}"
            entity["@id"] = entity_id
            
        # Skip if already processed
        if entity_id in processed_ids: return {"@id": entity_id}
        processed_ids.add(entity_id)
        
        # Assign context (alternate contexts for nested entities)
        if len(contexts) > 0:
            entity["@context"] = contexts[ctx_index % len(contexts)]
        
        # Create a copy for the graph
        graph_entity = copy.deepcopy(entity)
        
        # Process nested properties
        for prop, value in list(entity.items()):
            if prop.startswith("@"): continue
            
            # Process dict value
            if isinstance(value, dict) and len(value) > 1:
                nested = process_entity(value, ctx_index + 1)
                graph_entity[prop] = {"@id": nested["@id"]}
            
            # Process list of values
            elif isinstance(value, list):
                for i, item in enumerate(value):
                    if isinstance(item, dict) and len(item) > 1:
                        nested = process_entity(item, ctx_index + 1)
                        if isinstance(graph_entity[prop], list):
                            graph_entity[prop][i] = {"@id": nested["@id"]}
        
        # Add to graph
        graph["@graph"].append(graph_entity)
        return {"@id": entity_id}
    
    # Start processing from root
    process_entity(root)
    
    return graph


# %% ../03_memory.ipynb 41
@patch
def _normalize_entity(self:SemanticMemory, data):
    """Normalize entity properties for consistent processing"""
    if not isinstance(data, dict): return data
    
    result = data.copy()
    
    # Normalize id → @id
    if "id" in result:
        if "@id" not in result: result["@id"] = result["id"]
        del result["id"]
    
    # Normalize type → @type
    if "type" in result:
        if "@type" not in result: result["@type"] = result["type"]
        del result["type"]
    
    # Recursively normalize nested objects
    for k, v in list(result.items()):
        if k.startswith("@"): continue
        if isinstance(v, dict): result[k] = self._normalize_entity(v)
        elif isinstance(v, list): result[k] = [self._normalize_entity(i) if isinstance(i, dict) else i for i in v]
    
    return result

# %% ../03_memory.ipynb 42
@patch
def _register_context(self:SemanticMemory, context):
    """Register context and extract scoped contexts"""
    import json, hashlib
    
    # Generate stable ID for context
    if isinstance(context, str): ctx_id = context
    elif isinstance(context, list): ctx_id = "ctx:" + "_".join(self._register_context(c) for c in context)
    elif isinstance(context, dict):
        ctx_str = json.dumps(context, sort_keys=True)
        ctx_id = "ctx:" + hashlib.md5(ctx_str.encode()).hexdigest()
    else: return None
    
    # Skip if already registered
    if ctx_id in self.context_registry: return ctx_id
    
    # Register new context
    self.context_registry[ctx_id] = {
        "context": context,
        "scoped_contexts": {},
        "used_by": set()
    }
    
    # Extract scoped contexts if present
    if isinstance(context, dict):
        for term, defn in context.items():
            if isinstance(defn, dict) and "@context" in defn:
                # Register the scoped context
                scoped_id = self._register_context(defn["@context"])
                if scoped_id: self.context_registry[ctx_id]["scoped_contexts"][term] = scoped_id
    
    return ctx_id


# %% ../03_memory.ipynb 51
@patch
def query_by_id(self:SemanticMemory, entity_id):
    """Get entity by ID with improved retrieval"""
    # Try direct lookup
    if entity_id in self.indices["by_id"]: return self.indices["by_id"][entity_id]
    
    # Try with/without trailing slash for URLs
    if entity_id.startswith(('http://', 'https://')):
        alt_id = entity_id + '/' if not entity_id.endswith('/') else entity_id[:-1]
        if alt_id in self.indices["by_id"]: return self.indices["by_id"][alt_id]
    
    # Try RDF query as fallback
    entity_uri = URIRef(entity_id)
    results = {}
    
    for s, p, o in self.default_graph.triples((entity_uri, None, None)):
        pred = str(p)
        if pred not in results: results[pred] = []
        
        if isinstance(o, URIRef): results[pred].append({"@id": str(o)})
        elif isinstance(o, Literal): results[pred].append({"@value": str(o)})
    
    return results if results else None

# %% ../03_memory.ipynb 52
@patch
def get_connected_entities(self:SemanticMemory, entity_id, max_depth=1):
    """Get entity and all connected entities up to max_depth"""
    if max_depth < 0: return {}
    
    # Get the starting entity
    entity = self.query_by_id(entity_id)
    if not entity: return {}
    
    result = {entity_id: entity}
    
    # Find all referenced entities
    if max_depth > 0:
        for prop, values in entity.items():
            if prop.startswith("@"): continue
            
            for val in values if isinstance(values, list) else [values]:
                if isinstance(val, dict) and "@id" in val:
                    ref_id = val["@id"]
                    # Recursively get connected entities
                    connected = self.get_connected_entities(ref_id, max_depth-1)
                    result.update(connected)
    
    return result

# %% ../03_memory.ipynb 53
@patch 
def query_by_type(self:SemanticMemory, type_uri):
    """Get all entities of a specific type, including subtypes"""
    results = []
    seen_ids = set()  # Track entities we've already added
    processed_types = set()  # Track types we've already processed
    
    # Normalize URIs to handle schema.org HTTP/HTTPS variations
    uris_to_check = [type_uri]
    if type_uri.startswith("http://schema.org/"):
        uris_to_check.append(type_uri.replace("http://", "https://"))
    elif type_uri.startswith("https://schema.org/"):
        uris_to_check.append(type_uri.replace("https://", "http://"))
    
    # Helper to add entities of a specific type to results
    def add_entities_of_type(t):
        if t in self.indices["by_type"]:
            for entity in self.indices["by_type"][t]:
                entity_id = entity.get("@id")
                if entity_id and entity_id not in seen_ids:
                    results.append(entity)
                    seen_ids.add(entity_id)
    
    # Helper to process a type and its subtypes using iteration instead of recursion
    def process_type_hierarchy(start_type):
        to_process = [start_type]  # Stack of types to process
        
        while to_process:
            current_type = to_process.pop()
            
            # Skip if already processed
            if current_type in processed_types:
                continue
                
            processed_types.add(current_type)
            
            # Add entities of this type
            add_entities_of_type(current_type)
            
            # Add subtypes to processing stack
            if "superclass_of" in self.indices:
                for alt_uri in [current_type]:
                    if alt_uri in self.indices["superclass_of"]:
                        for subtype in self.indices["superclass_of"][alt_uri]:
                            if subtype not in processed_types:
                                to_process.append(subtype)
    
    # Process all URIs we need to check
    for uri in uris_to_check:
        if uri not in processed_types:
            process_type_hierarchy(uri)
    
    # If no results found, try RDF graph query as fallback
    if not results:
        try:
            for uri in uris_to_check:
                type_uri_ref = URIRef(uri)
                for s in self.default_graph.subjects(RDF.type, type_uri_ref):
                    entity_id = str(s)
                    if entity_id not in seen_ids:
                        entity = self.query_by_id(entity_id)
                        if entity:
                            results.append(entity)
                            seen_ids.add(entity_id)
        except Exception as e:
            print(f"RDF query error: {e}")
    
    return results


# %% ../03_memory.ipynb 55
@patch
def _update_indices(self:SemanticMemory, expanded_data):
    """Update indices with expanded JSON-LD data"""
    # Handle both single entity and array cases
    nodes = expanded_data if isinstance(expanded_data, list) else [expanded_data]
    
    for node in nodes:
        if not isinstance(node, dict): continue
        
        # Get node ID
        node_id = node.get('@id')
        if not node_id: continue
        
        # Update by_id index
        self.indices["by_id"][node_id] = node
        
        # Update by_type index - handle expanded types properly
        types = []
        
        # Check for @type property (could be string, list, or in expanded form)
        if '@type' in node:
            type_values = node['@type'] if isinstance(node['@type'], list) else [node['@type']]
            for t in type_values:
                if isinstance(t, str): types.append(t)
        
        # Also check for rdf:type triples in expanded JSON-LD
        rdf_type = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'
        if rdf_type in node:
            type_objects = node[rdf_type] if isinstance(node[rdf_type], list) else [node[rdf_type]]
            for t_obj in type_objects:
                if isinstance(t_obj, dict) and '@id' in t_obj:
                    types.append(t_obj['@id'])
        
        # Index by each type
        for type_uri in types:
            if type_uri not in self.indices["by_type"]: self.indices["by_type"][type_uri] = []
            if node not in self.indices["by_type"][type_uri]: 
                self.indices["by_type"][type_uri].append(node)
        
        # Update label and description indices
        self._index_labels_and_descriptions(node)
        
        # Track subClassOf relationships for type inference
        self._index_subclass_relationships(node)


# %% ../03_memory.ipynb 56
@patch
def _index_labels_and_descriptions(self:SemanticMemory, node):
    """Index entity by labels and textual content for better search"""
    if not isinstance(node, dict): return
    
    # Common label properties
    label_props = [
        "http://www.w3.org/2000/01/rdf-schema#label",
        "http://schema.org/name",
        "http://purl.org/dc/terms/title",
        "http://xmlns.com/foaf/0.1/name",
        "name"  # Handle both expanded and compact forms
    ]
    
    # Common description properties
    desc_props = [
        "http://www.w3.org/2000/01/rdf-schema#comment",
        "http://schema.org/description",
        "http://purl.org/dc/terms/description",
        "http://purl.org/dc/elements/1.1/description",
        "description"  # Handle both expanded and compact forms
    ]
    
    node_id = node.get('@id')
    if not node_id: return
    
    # Ensure index structures exist
    if "by_label" not in self.indices: self.indices["by_label"] = {}
    if "by_keyword" not in self.indices: self.indices["by_keyword"] = {}
    
    # Extract labels for label index
    for prop in label_props:
        if prop in node:
            values = node[prop] if isinstance(node[prop], list) else [node[prop]]
            for value in values:
                label = value.get('@value') if isinstance(value, dict) else value
                if isinstance(label, str):
                    # Add to label index
                    if label not in self.indices["by_label"]: self.indices["by_label"][label] = []
                    if {'@id': node_id} not in self.indices["by_label"][label]:
                        self.indices["by_label"][label].append({'@id': node_id})
                    
                    # Index label as a whole
                    label_lower = label.lower()
                    if label_lower not in self.indices["by_keyword"]: self.indices["by_keyword"][label_lower] = []
                    if {'@id': node_id} not in self.indices["by_keyword"][label_lower]:
                        self.indices["by_keyword"][label_lower].append({'@id': node_id})
                    
                    # Index individual words and partial words
                    for word in label.split():
                        word_lower = word.lower()
                        if len(word_lower) > 2:
                            # Add whole word
                            if word_lower not in self.indices["by_keyword"]: self.indices["by_keyword"][word_lower] = []
                            if {'@id': node_id} not in self.indices["by_keyword"][word_lower]:
                                self.indices["by_keyword"][word_lower].append({'@id': node_id})
                            
                            # Add partial words (prefixes)
                            for i in range(3, len(word_lower)+1):
                                prefix = word_lower[:i]
                                if prefix not in self.indices["by_keyword"]: self.indices["by_keyword"][prefix] = []
                                if {'@id': node_id} not in self.indices["by_keyword"][prefix]:
                                    self.indices["by_keyword"][prefix].append({'@id': node_id})
    
    # Extract text from descriptions for keyword index
    for prop in desc_props:
        if prop in node:
            values = node[prop] if isinstance(node[prop], list) else [node[prop]]
            for value in values:
                text = value.get('@value') if isinstance(value, dict) else value
                if isinstance(text, str):
                    # Simple keyword extraction - split and filter
                    for word in text.split():
                        word_lower = word.lower()
                        if len(word_lower) > 2:
                            if word_lower not in self.indices["by_keyword"]: self.indices["by_keyword"][word_lower] = []
                            if {'@id': node_id} not in self.indices["by_keyword"][word_lower]:
                                self.indices["by_keyword"][word_lower].append({'@id': node_id})


# %% ../03_memory.ipynb 57
@patch
def _index_subclass_relationships(self:SemanticMemory, node):
    """Index subclass relationships for type inference"""
    if not isinstance(node, dict): return
    
    # Initialize subclass index if needed
    if "subclass_of" not in self.indices: self.indices["subclass_of"] = {}
    if "superclass_of" not in self.indices: self.indices["superclass_of"] = {}
    
    # Check for subClassOf relationship
    subclass_of = 'http://www.w3.org/2000/01/rdf-schema#subClassOf'
    if subclass_of in node:
        class_id = node.get('@id')
        if not class_id: return
        
        # Get all superclasses
        super_classes = node[subclass_of] if isinstance(node[subclass_of], list) else [node[subclass_of]]
        
        for super_class in super_classes:
            if isinstance(super_class, dict) and '@id' in super_class:
                super_class_id = super_class['@id']
                
                # Record subclass relationship
                if class_id not in self.indices["subclass_of"]: 
                    self.indices["subclass_of"][class_id] = set()
                self.indices["subclass_of"][class_id].add(super_class_id)
                
                # Record superclass relationship (inverse)
                if super_class_id not in self.indices["superclass_of"]:
                    self.indices["superclass_of"][super_class_id] = set()
                self.indices["superclass_of"][super_class_id].add(class_id)


# %% ../03_memory.ipynb 59
@patch
def retrieve_in_context(self:SemanticMemory, entity_id):
    """Retrieve entity with original context structure preserved"""
    # Check if we have the original data
    if entity_id not in self.original_data: return None
    
    # Get the original data with context
    entity = self.original_data[entity_id]
    
    # Look up context registry entries for this entity
    ctx_ids = []
    for ctx_id, ctx_info in self.context_registry.items():
        if entity_id in ctx_info.get("used_by", set()):
            ctx_ids.append(ctx_id)
    
    # Ensure scoped contexts are properly included
    import copy
    result = copy.deepcopy(entity)
    
    # Process any context with scoped contexts
    for ctx_id in ctx_ids:
        ctx_info = self.context_registry[ctx_id]
        
        # Check if this context has scoped contexts
        if ctx_info["scoped_contexts"] and isinstance(result.get("@context"), dict):
            # Ensure all scoped contexts are included
            for term, scoped_id in ctx_info["scoped_contexts"].items():
                if term in result["@context"] and isinstance(result["@context"][term], dict):
                    # Get the scoped context definition
                    scoped_ctx = self.context_registry.get(scoped_id, {}).get("context")
                    if scoped_ctx:
                        # Add back the scoped context
                        result["@context"][term]["@context"] = scoped_ctx
    
    return result


# %% ../03_memory.ipynb 60
@patch
def search(self:SemanticMemory, query_text, limit=10):
    """Search memory for entities matching the query text"""
    results = []
    query_lower = query_text.lower()
    
    # Track matched entities to avoid duplicates
    matched_ids = set()
    
    # First check exact label matches (highest priority)
    if "by_label" in self.indices:
        for label, entities in self.indices["by_label"].items():
            if isinstance(label, str) and query_lower in label.lower():
                for entity_ref in entities:
                    if "@id" in entity_ref:
                        entity_id = entity_ref["@id"]
                        if entity_id not in matched_ids:
                            entity = self.query_by_id(entity_id)
                            if entity:
                                results.append(entity)
                                matched_ids.add(entity_id)
                                if len(results) >= limit: return results
    
    # Then check keyword matches
    if "by_keyword" in self.indices:
        # Try the exact token first
        if query_lower in self.indices["by_keyword"]:
            for entity_ref in self.indices["by_keyword"][query_lower]:
                if "@id" in entity_ref:
                    entity_id = entity_ref["@id"]
                    if entity_id not in matched_ids:
                        entity = self.query_by_id(entity_id)
                        if entity:
                            results.append(entity)
                            matched_ids.add(entity_id)
                            if len(results) >= limit: return results
        
        # Try as partial match for any keywords
        for keyword, entities in self.indices["by_keyword"].items():
            if isinstance(keyword, str) and query_lower in keyword and query_lower != keyword:
                for entity_ref in entities:
                    if "@id" in entity_ref:
                        entity_id = entity_ref["@id"]
                        if entity_id not in matched_ids:
                            entity = self.query_by_id(entity_id)
                            if entity:
                                results.append(entity)
                                matched_ids.add(entity_id)
                                if len(results) >= limit: return results
    
    # If still not enough results, try content search
    if len(results) < limit:
        for entity_id, entity in self.indices["by_id"].items():
            if entity_id in matched_ids: continue
            
            # Try to find the query in string representation of values
            for prop, values in entity.items():
                if prop.startswith('@'): continue
                
                # Handle different value formats
                if isinstance(values, list):
                    for val in values:
                        # Convert to string safely
                        val_str = ""
                        if isinstance(val, dict) and "@value" in val:
                            val_content = val.get("@value")
                            if isinstance(val_content, str):
                                val_str = val_content.lower()
                        elif isinstance(val, str):
                            val_str = val.lower()
                        
                        if val_str and query_lower in val_str:
                            results.append(entity)
                            matched_ids.add(entity_id)
                            break
                else:
                    # Convert to string safely
                    val_str = ""
                    if isinstance(values, dict) and "@value" in values:
                        val_content = values.get("@value")
                        if isinstance(val_content, str):
                            val_str = val_content.lower()
                    elif isinstance(values, str):
                        val_str = values.lower()
                    
                    if val_str and query_lower in val_str:
                        results.append(entity)
                        matched_ids.add(entity_id)
                
                if entity_id in matched_ids and len(results) >= limit: 
                    break
            
            if len(results) >= limit:
                break
    
    return results


# %% ../03_memory.ipynb 63
@patch 
def query_by_type(self:SemanticMemory, type_uri):
    """Get all entities of a specific type, including subtypes"""
    results = []
    seen_ids = set()
    
    # Handle HTTP/HTTPS variations for any vocabulary
    types_to_check = set([type_uri])
    if type_uri.startswith("http://"):
        types_to_check.add(type_uri.replace("http://", "https://"))
    elif type_uri.startswith("https://"):
        types_to_check.add(type_uri.replace("https://", "http://"))
    
    # Add all subtypes recursively
    if "superclass_of" in self.indices:
        for t in list(types_to_check):  # Use list to avoid modifying during iteration
            if t in self.indices["superclass_of"]:
                types_to_check.update(self.indices["superclass_of"][t])
    
    # Get all entities of these types
    for t in types_to_check:
        if t in self.indices["by_type"]:
            for entity in self.indices["by_type"][t]:
                eid = entity.get("@id")
                if eid and eid not in seen_ids:
                    results.append(entity)
                    seen_ids.add(eid)
    
    return results


# %% ../03_memory.ipynb 64
@patch
def _get_connected_subgraph(self:SemanticMemory, entity_id, max_depth=1, visited=None):
    """Extract a semantically connected subgraph centered on an entity.
    
    This function traverses the knowledge graph starting from a central entity,
    following relationships to connected entities up to max_depth hops away.
    It maintains the graph structure and relationship semantics.
    
    Args:
        entity_id: The ID of the central entity
        max_depth: Maximum number of relationship hops to traverse
        visited: Set of already visited entity IDs (for recursion)
        
    Returns:
        Dictionary mapping entity IDs to their data for the subgraph
    """
    if max_depth < 0: return {}
    if visited is None: visited = set()
    
    # Skip if already visited
    if entity_id in visited: return {}
    
    # Mark as visited
    visited.add(entity_id)
    
    # Get the entity
    entity = self.query_by_id(entity_id)
    if not entity: return {}
    
    result = {entity_id: entity}
    
    # If at max depth, don't explore further
    if max_depth == 0: return result
    
    # Find all referenced entities
    for prop, values in entity.items():
        if prop.startswith("@"): continue
        
        # Handle list values
        if isinstance(values, list):
            for val in values:
                if isinstance(val, dict) and "@id" in val:
                    ref_id = val["@id"]
                    # Recursively get connected entities
                    connected = self._get_connected_subgraph(ref_id, max_depth-1, visited)
                    result.update(connected)
        # Handle dict values
        elif isinstance(values, dict) and "@id" in values:
            ref_id = values["@id"]
            # Recursively get connected entities
            connected = self._get_connected_subgraph(ref_id, max_depth-1, visited)
            result.update(connected)
    
    return result


# %% ../03_memory.ipynb 65
@patch
def prepare_for_llm(self:SemanticMemory, entities, include_vocab_info=True, compact=True):
    """Format entities for optimal LLM understanding and context window usage.
    
    This function processes a set of entities to make them more suitable for
    loading into an LLM's context window. It can:
    1. Detect and include vocabulary information
    2. Compact entities using their appropriate vocabularies
    3. Extract explicit relationship information
    
    Args:
        entities: List of entities to prepare
        include_vocab_info: Whether to include vocabulary metadata
        compact: Whether to compact entities with their vocabularies
        
    Returns:
        Structured dictionary with entities, relationships, and vocabulary info
    """
    if not entities: return {}
    
    # Detect vocabularies used
    vocab_info = {}
    if include_vocab_info:
        for entity in entities:
            if isinstance(entity, dict) and "@context" in entity:
                ctx = entity["@context"]
                # Process string contexts
                if isinstance(ctx, str):
                    for vocab_name, vocab_data in VOCABULARY_REGISTRY.items():
                        if vocab_data["uri"] in ctx:
                            vocab_info[vocab_name] = vocab_data["uri"]
                # Process object contexts
                elif isinstance(ctx, dict) and "@vocab" in ctx:
                    vocab_uri = ctx["@vocab"]
                    for vocab_name, vocab_data in VOCABULARY_REGISTRY.items():
                        if vocab_data["uri"] == vocab_uri:
                            vocab_info[vocab_name] = vocab_data["uri"]
    
    # Compact entities if requested
    processed_entities = []
    for entity in entities:
        if compact and isinstance(entity, dict):
            # Try to detect vocabulary
            detected_vocab = None
            for vocab_name in vocab_info:
                if isinstance(entity.get("@context"), str) and vocab_info[vocab_name] in entity["@context"]:
                    detected_vocab = vocab_name
                    break
            
            # Compact if vocabulary detected
            if detected_vocab:
                try:
                    compacted = compact_entity_with_vocabulary(entity, detected_vocab)
                    processed_entities.append(compacted)
                except:
                    processed_entities.append(entity)
            else:
                processed_entities.append(entity)
        else:
            processed_entities.append(entity)
    
    # Create result structure
    result = {
        "entities": processed_entities,
        "count": len(processed_entities),
        "relationships": self._extract_relationships(processed_entities)
    }
    
    # Add vocabulary information if available
    if vocab_info:
        result["vocabularies"] = vocab_info
    
    return result


# %% ../03_memory.ipynb 66
@patch
def _extract_relationships(self:SemanticMemory, entities):
    """Extract explicit relationships between entities for LLM comprehension.
    
    This function analyzes a set of entities and identifies all the relationships
    between them, making the knowledge graph structure explicit and easier for
    an LLM to understand.
    
    Args:
        entities: List of entities to analyze
        
    Returns:
        List of relationship objects with source, property, and target
    """
    if not entities: return []
    
    relationships = []
    entity_ids = {e.get("@id") for e in entities if isinstance(e, dict) and "@id" in e}
    
    for entity in entities:
        if not isinstance(entity, dict) or "@id" not in entity: continue
        
        source_id = entity["@id"]
        
        # Find all references to other entities in the set
        for prop, values in entity.items():
            if prop.startswith("@"): continue
            
            # Handle list values
            if isinstance(values, list):
                for val in values:
                    if isinstance(val, dict) and "@id" in val:
                        target_id = val["@id"]
                        if target_id in entity_ids:
                            relationships.append({
                                "source": source_id,
                                "property": prop,
                                "target": target_id
                            })
            # Handle dict values
            elif isinstance(values, dict) and "@id" in values:
                target_id = values["@id"]
                if target_id in entity_ids:
                    relationships.append({
                        "source": source_id,
                        "property": prop,
                        "target": target_id
                    })
    
    return relationships


# %% ../03_memory.ipynb 67
@patch
def search_for_llm(self:SemanticMemory, query, limit=10, include_connected=True, max_depth=1, include_vocab_info=True):
    """Search semantic memory and prepare results specifically for LLM consumption.
    
    This convenience function combines semantic search with LLM-optimized formatting
    to make it easy to load relevant knowledge graph subsets into an LLM context window.
    
    Args:
        query: Text to search for (can be an ID, type, label, or keywords)
        limit: Maximum number of entities to return
        include_connected: Whether to include connected entities in results
        max_depth: How many relationship hops to traverse
        include_vocab_info: Whether to include vocabulary metadata
        
    Returns:
        Structured data ready for loading into an LLM context window
    """
    entities = self.semantic_search(query, limit, include_connected, max_depth)
    return self.prepare_for_llm(entities, include_vocab_info)


# %% ../03_memory.ipynb 68
@patch
def prepare_for_llm_context(self:SemanticMemory, query=None, graph_id=None, limit=50, preferred_vocabs=None):
    "Prepare memory contents for LLM context window with vocabulary awareness"
    entities = []
    
    if query:
        search_results = self.search(query, limit=limit)
        entities.extend(search_results)
    elif graph_id:
        if "by_graph" in self.indices and URIRef(graph_id) in self.indices["by_graph"]:
            entity_ids = list(self.indices["by_graph"][URIRef(graph_id)])[:limit]
            for eid in entity_ids:
                entity = self.query_by_id(eid)
                if entity: entities.append(entity)
    else:
        entity_ids = list(self.indices["by_id"].keys())[:limit]
        for eid in entity_ids:
            entity = self.query_by_id(eid)
            if entity: entities.append(entity)
    
    formatted_entities = []
    for entity in entities:
        compacted = self.compact_with_preferred_vocab(entity, preferred_vocabs)
        formatted_entities.appen

