# AUTOGENERATED! DO NOT EDIT! File to edit: ../08_utils.ipynb.

# %% auto 0
__all__ = ['load_module_source', 'load_all_modules', 'display_module_structure']

# %% ../08_utils.ipynb 5
import inspect
import importlib
import sys
import os
from pathlib import Path
from typing import Dict, List, Optional, Union
from IPython.display import display, Markdown

# %% ../08_utils.ipynb 7
def load_module_source(module_name:str, # Name of the module to load (e.g., "core", "vocabulary")
                      full_name:bool=False # Whether the name includes the package prefix
                     ) -> str:
    """Load the source code of a module as a string
    
    Args:
        module_name: Name of the module to load
        full_name: Whether the name includes the package prefix
        
    Returns:
        The source code as a string
    """
    # Handle module name with or without package prefix
    if not full_name:
        full_module_name = f"cogitarelink.{module_name}"
    else:
        full_module_name = module_name
    
    try:
        # Import the module
        module = importlib.import_module(full_module_name)
        
        # Get the file path
        file_path = inspect.getfile(module)
        
        # Read the source code
        with open(file_path, 'r') as f:
            source = f.read()
            
        print(f"Loaded {module_name} from {file_path} ({len(source)} characters)")
        return source
    
    except Exception as e:
        print(f"Error loading {module_name}: {e}")
        return ""

# %% ../08_utils.ipynb 9
def load_all_modules() -> Dict[str, str]:
    """Load the source code of all cogitarelink modules
    
    Returns:
        A dictionary mapping module names to their source code
    """
    core_modules = ["core", "vocabulary", "navigation", "dataset", "tools", "workflows"]
    sources = {}
    
    for module in core_modules:
        source = load_module_source(module)
        if source:
            sources[f"{module}_py"] = source
    
    return sources

# %% ../08_utils.ipynb 11
def display_module_structure(module_name:str=None, # Module to display (or None for all)
                           show_functions:bool=True # Whether to list functions
                          ) -> None:
    """Display the structure of a module or all modules
    
    Args:
        module_name: Module to display, or None for all modules
        show_functions: Whether to list functions in the module
    """
    if module_name:
        modules = [module_name]
    else:
        modules = ["core", "vocabulary", "navigation", "dataset", "tools", "workflows"]
    
    for mod_name in modules:
        try:
            # Import the module
            full_name = f"cogitarelink.{mod_name}"
            module = importlib.import_module(full_name)
            
            # Get file info
            file_path = inspect.getfile(module)
            
            # Get all objects in the module
            objects = inspect.getmembers(module)
            
            # Filter to just functions and classes if requested
            if show_functions:
                functions = [name for name, obj in objects 
                           if inspect.isfunction(obj) and not name.startswith('_')]
                classes = [name for name, obj in objects 
                         if inspect.isclass(obj) and not name.startswith('_')]
            
            # Create markdown
            md = [f"## Module: {mod_name}"]
            md.append(f"File: {file_path}")
            
            if show_functions:
                if classes:
                    md.append("\n### Classes:")
                    for cls in sorted(classes):
                        md.append(f"- `{cls}`")
                
                if functions:
                    md.append("\n### Functions:")
                    for func in sorted(functions):
                        md.append(f"- `{func}`")
            
            display(Markdown("\n".join(md)))
            
        except Exception as e:
            print(f"Error displaying structure for {mod_name}: {e}")
