"""Dialog exploring the extension of Cogitarelink Semantic Memory to be "Verifiable Semantic Memory" using DID, did:key, W3C VC 2.0, W3C PROV and SHACL"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../d_04_vmemory.ipynb.

# %% auto 0
__all__ = ['SignatureManager', 'SignatureStore', 'VerifiableSemanticMemory']

# %% ../d_04_vmemory.ipynb 4
import json
from pyld import jsonld
import httpx
from rdflib import Graph, Dataset, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS, OWL
from enum import Enum
from fastcore.basics import patch
from dataclasses import dataclass, field
from claudette import Chat, toolloop, models
import time
import copy
from typing import List, Dict, Any, Union, Optional, Tuple, Callable
from fastcore.basics import patch
from datetime import datetime
from pathlib import Path
import types
import pickle
from contextlib import contextmanager, nullcontext

# %% ../d_04_vmemory.ipynb 5
# Import for verifiable semantic memory
import base64
import uuid
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization
from multibase import encode, decode

# %% ../d_04_vmemory.ipynb 6
from .utils import *
from .vocabtools import *
from .memory import *

# %% ../d_04_vmemory.ipynb 23
class SignatureManager(DebugMixin):
    """Manages JSON-LD signatures and verifications using EdDSA Cryptosuite 2020
    
    This class implements the W3C EdDSA Cryptosuite 2020 specification
    for signing and verifying JSON-LD documents.
    
    Attributes:
        did_manager: DIDManager for key operations and DID resolution
        contexts: Dictionary of commonly used contexts to avoid fetching
    """
    
    # Security contexts for JSON-LD signatures
    SECURITY_CONTEXT_V2_URL = "https://w3id.org/security/v2"
    ED25519_2020_CONTEXT_URL = "https://w3id.org/security/suites/ed25519-2020/v1"
    
    def __init__(self, did_manager, storage_path=None, 
                 debug=False, debug_level=0, parent=None):
        """Initialize the signature manager
        
        Args:
            did_manager: DIDManager instance for key operations
            storage_path: Optional path for storing signature data
            debug: Whether debugging is enabled
            debug_level: Level of detail for debugging
            parent: Optional parent component
        """
        # Initialize debug mixin
        super().__init__(debug=debug, debug_level=debug_level, 
                         debug_component="SignatureManager", parent=parent)
        
        self.did_manager = did_manager
        self.storage_path = Path(storage_path) if storage_path else None
        
        # Initialize document cache
        self.contexts = {
            self.SECURITY_CONTEXT_V2_URL: {
                # Pre-cached security context v2
                # Would contain the actual context data
            },
            self.ED25519_2020_CONTEXT_URL: {
                # Pre-cached Ed25519 2020 context
                # Would contain the actual context data
            }
        }
        
        # Initialize stats
        self._debug_stats["documents_signed"] = 0
        self._debug_stats["signatures_verified"] = 0
        
        # Check for required libraries
        try:
            import multibase
            self.multibase = multibase
            self._debug("multibase library available", level=2)
        except ImportError:
            self._debug("multibase library not available - install with pip install multibase", level=1)
            self.multibase = None
        
        try:
            from cryptography.hazmat.primitives.asymmetric import ed25519
            self.ed25519 = ed25519
            self._debug("cryptography.ed25519 available", level=2)
        except ImportError:
            self._debug("cryptography library not available - install with pip install cryptography", level=1)
            self.ed25519 = None
            
        self._debug("SignatureManager initialized", level=1)

# %% ../d_04_vmemory.ipynb 24
@patch
def _get_document_loader(self:SignatureManager):
    """Get a document loader that leverages SemanticMemory if available"""
    # If we have a parent SemanticMemory, use its document loading capabilities
    if hasattr(self, 'parent') and self.parent:
        if hasattr(self.parent, 'contexts'):
            return self._create_sm_document_loader()
    
    # Otherwise fall back to a default document loader
    return jsonld.requests_document_loader()

@patch
def _create_sm_document_loader(self:SignatureManager):
    """Create a document loader that uses SemanticMemory's context cache"""
    def sm_document_loader(url):
        """Document loader that checks SemanticMemory first"""
        self._debug(f"Loading document: {url}", level=2)
        
        # Check if this is a context URL
        if "context" in url.lower() or "/contexts/" in url:
            try:
                # Try to get from parent's context cache
                ctx = self.parent.contexts.get_cached_context(url)
                if ctx:
                    self._debug(f"Found context in cache: {url}", level=2)
                    return {
                        'contextUrl': None,
                        'documentUrl': url,
                        'document': ctx
                    }
            except Exception as e:
                self._debug(f"Error accessing context cache: {str(e)}", level=1)
        
        # Try to get the entity from semantic memory
        try:
            entity = self.parent.query_by_id(url)
            if entity:
                self._debug(f"Found entity in memory: {url}", level=2)
                return {
                    'contextUrl': None,
                    'documentUrl': url,
                    'document': entity
                }
        except Exception as e:
            self._debug(f"Error querying memory: {str(e)}", level=1)
        
        # Fall back to network request
        self._debug(f"Fetching from network: {url}", level=2)
        return jsonld.requests_document_loader()(url)
    
    return sm_document_loader

# %% ../d_04_vmemory.ipynb 25
@patch
def canonize(self:SignatureManager, document):
    """Properly canonize a JSON-LD document for signing/verification"""
    try:
        # Make a deep copy to avoid modifying the original
        doc_copy = copy.deepcopy(document)
        
        # Remove any existing proof before canonization
        if isinstance(doc_copy, dict) and "proof" in doc_copy:
            del doc_copy["proof"]
        
        # Ensure proper JSON-LD context if missing
        if isinstance(doc_copy, dict) and "@context" not in doc_copy:
            doc_copy["@context"] = "https://w3id.org/security/v2"
            
        # Convert to expanded form first to ensure complete expansion
        expanded = jsonld.expand(doc_copy)
        
        # Then normalize using URDNA2015 algorithm
        normalized = jsonld.normalize(
            expanded, 
            {
                'algorithm': 'URDNA2015', 
                'format': 'application/n-quads'
            },
            document_loader=self._get_document_loader()
        )
        
        if not normalized:
            self._debug("Warning: Canonization produced empty output", level=1)
        
        return normalized
    except Exception as e:
        self._debug(f"Canonization error: {str(e)}", level=1)
        raise

# %% ../d_04_vmemory.ipynb 26
@patch
def create_verify_data(self:SignatureManager, doc_nquads, proof_opts_nquads):
    """Create the verify data from document and proof option N-Quads
    
    Args:
        doc_nquads: Canonized document N-Quads
        proof_opts_nquads: Canonized proof options N-Quads
        
    Returns:
        64-byte verify data (concatenation of SHA-256 hashes)
    """
    from hashlib import sha256
    
    # Create SHA-256 hash of document N-Quads
    doc_digest = sha256(doc_nquads.encode()).digest()
    
    # Create SHA-256 hash of proof options N-Quads
    proof_digest = sha256(proof_opts_nquads.encode()).digest()
    
    # Concatenate the two 32-byte digests
    return doc_digest + proof_digest

# %% ../d_04_vmemory.ipynb 28
@patch
def sign(self:SignatureManager, document, did, purpose="assertionMethod"):
    """Sign a document with a DID using Ed25519Signature2020"""
    try:
        # Make a deep copy to avoid modifying the original
        doc_copy = copy.deepcopy(document)
        
        # Remove any existing proof
        if "proof" in doc_copy:
            del doc_copy["proof"]
        
        # Create proof options
        created = datetime.now().isoformat() + "Z"
        proof_options = {
            "@context": [
                "https://w3id.org/security/v2",
                "https://w3id.org/security/suites/ed25519-2020/v1"
            ],
            "type": "Ed25519Signature2020",
            "created": created,
            "verificationMethod": f"{did}#keys-1",
            "proofPurpose": purpose
        }
        
        # Get DID document to ensure verification method exists
        did_doc = self.did_manager.resolve_did(did)
        if not did_doc:
            self._debug(f"Could not resolve DID: {did}", level=1)
            return None
        
        # Find the verification method
        verification_method = None
        for method in did_doc.get("verificationMethod", []):
            if method["id"] == f"{did}#keys-1":
                verification_method = method
                break
        
        if not verification_method:
            self._debug(f"Verification method not found for DID: {did}", level=1)
            return None
        
        # Canonize the document
        canonical_doc = self.canonize(doc_copy)
        
        # Canonize the proof options
        proof_options_copy = copy.deepcopy(proof_options)
        if "@context" in proof_options_copy:
            del proof_options_copy["@context"]  # Remove context for canonization
        canonical_proof = self.canonize(proof_options_copy)
        
        # Create the verify data by concatenating the canonized document and proof
        verify_data = canonical_doc + canonical_proof
        
        # Sign the verify data
        signature = self.did_manager.sign_with_did(verify_data.encode('utf-8'), did)
        if not signature:
            self._debug("Signing failed", level=1)
            return None
        
        # Encode the signature as multibase
        multibase_signature = encode("base58btc", signature).decode()
        
        # Add the proof to the document
        proof = copy.deepcopy(proof_options)
        proof["proofValue"] = "z" + multibase_signature
        
        doc_copy["proof"] = proof
        
        self._debug_stats["documents_signed"] += 1
        
        return doc_copy
    except Exception as e:
        self._debug(f"Error signing document: {str(e)}", level=1)
        return None

# %% ../d_04_vmemory.ipynb 29
@patch
def verify(self:SignatureManager, document):
    """Verify a signed document using Ed25519Signature2020"""
    try:
        # Check if document has a proof
        if not isinstance(document, dict) or "proof" not in document:
            self._debug("Document has no proof", level=1)
            return False
        
        # Get the proof
        proof = document.get("proof")
        
        # Ensure it's the right type
        if proof.get("type") != "Ed25519Signature2020":
            self._debug(f"Unsupported signature type: {proof.get('type')}", level=1)
            return False
        
        # Get verification method
        verification_method = proof.get("verificationMethod")
        if not verification_method:
            self._debug("No verification method in proof", level=1)
            return False
        
        # Extract DID from verification method
        did = verification_method.split("#")[0]
        
        # Get proof value
        proof_value = proof.get("proofValue")
        if not proof_value:
            self._debug("No proof value in proof", level=1)
            return False
        
        # Decode the multibase signature
        if not proof_value.startswith("z"):
            self._debug("Invalid proof value format", level=1)
            return False
        
        try:
            signature = decode(proof_value)
        except Exception as e:
            self._debug(f"Error decoding proof value: {str(e)}", level=1)
            return False
        
        # Make a copy of the document without the proof
        doc_copy = copy.deepcopy(document)
        del doc_copy["proof"]
        
        # Canonize the document
        canonical_doc = self.canonize(doc_copy)
        
        # Prepare proof options for canonization
        proof_options = copy.deepcopy(proof)
        # Remove fields that should not be included in canonization
        for field in ["@context", "proofValue"]:
            if field in proof_options:
                del proof_options[field]
        
        # Canonize the proof options
        canonical_proof = self.canonize(proof_options)
        
        # Create the verify data by concatenating the canonized document and proof
        verify_data = canonical_doc + canonical_proof
        
        # Verify the signature
        result = self.did_manager.verify_did_signature(
            verify_data.encode('utf-8'), 
            signature, 
            did
        )
        
        self._debug_stats["signatures_verified"] += 1
        
        return result
    except Exception as e:
        self._debug(f"Error verifying document: {str(e)}", level=1)
        return False

# %% ../d_04_vmemory.ipynb 30
@patch
def _debug_component_summary(self:SignatureManager):
    """Provide a specialized debug summary for SignatureManager"""
    print(f"Documents signed: {self._debug_stats.get('documents_signed', 0)}")
    print(f"Signatures verified: {self._debug_stats.get('signatures_verified', 0)}")
    
    # Show library availability
    print("\nLibrary status:")
    print(f"  multibase: {'Available' if self.multibase else 'Not available'}")
    print(f"  cryptography.ed25519: {'Available' if self.ed25519 else 'Not available'}")
    
    # Show storage information
    if self.storage_path:
        print(f"\nStorage path: {self.storage_path}")

# %% ../d_04_vmemory.ipynb 69
class SignatureStore:
    """Simple store for entity signatures
    
    This class provides a straightforward way to store and retrieve signatures
    separately from the entities themselves, avoiding issues with JSON-LD
    processing modifying the document structure.
    
    Attributes:
        signatures: Dictionary mapping entity IDs to signature data
        storage_path: Path for storing signatures on disk
    """
    
    def __init__(self, storage_path=None):
        """Initialize the signature store
        
        Args:
            storage_path: Optional path for storing signatures
        """
        self.signatures = {}  # Map entity IDs to signatures
        self.storage_path = Path(storage_path) if storage_path else None
        if self.storage_path:
            self._load_signatures()
    
    def add_signature(self, entity_id, did, signature_data, metadata=None):
        """Add a signature for an entity
        
        Args:
            entity_id: ID of the entity
            did: DID that created the signature
            signature_data: Base64-encoded signature
            metadata: Optional additional metadata
            
        Returns:
            Boolean indicating success
        """
        self.signatures[entity_id] = {
            "did": did,
            "signature": signature_data,
            "timestamp": datetime.now().isoformat(),
            "metadata": metadata or {}
        }
        if self.storage_path:
            self._save_signatures()
        return True
    
    def get_signature(self, entity_id):
        """Get the signature for an entity
        
        Args:
            entity_id: ID of the entity
            
        Returns:
            Signature data or None if not found
        """
        return self.signatures.get(entity_id)
    
    def remove_signature(self, entity_id):
        """Remove a signature for an entity
        
        Args:
            entity_id: ID of the entity
            
        Returns:
            Boolean indicating if a signature was removed
        """
        if entity_id in self.signatures:
            del self.signatures[entity_id]
            if self.storage_path:
                self._save_signatures()
            return True
        return False
    
    def _load_signatures(self):
        """Load signatures from storage"""
        path = self.storage_path / "signatures.json"
        if path.exists():
            try:
                with open(path, 'r') as f:
                    self.signatures = json.load(f)
            except Exception as e:
                print(f"Error loading signatures: {e}")
    
    def _save_signatures(self):
        """Save signatures to storage"""
        path = self.storage_path / "signatures.json"
        try:
            with open(path, 'w') as f:
                json.dump(self.signatures, f)
        except Exception as e:
            print(f"Error saving signatures: {e}")

# %% ../d_04_vmemory.ipynb 70
@patch
def debug_summary(self:SignatureStore):
    """Print a summary of the signature store"""
    print(f"Signatures stored: {len(self.signatures)}")
    
    if self.signatures:
        print("\nRecent signatures:")
        # Sort by timestamp if available
        recent = sorted(
            self.signatures.items(), 
            key=lambda x: x[1].get("timestamp", ""), 
            reverse=True
        )[:3]
        
        for i, (entity_id, sig_data) in enumerate(recent):
            print(f"  {i+1}. {entity_id} - Signed by {sig_data['did']} at {sig_data.get('timestamp', 'unknown')}")
    
    if self.storage_path:
        path = self.storage_path / "signatures.json"
        if path.exists():
            size = path.stat().st_size
            print(f"\nSignature storage: {path} ({size} bytes)")

# %% ../d_04_vmemory.ipynb 72
@patch
def remove(self:IndexManager, entity_id):
    """Remove an entity from the index
    
    Args:
        entity_id: ID of entity to remove
        
    Returns:
        Boolean indicating if anything was removed
    """
    self._debug(f"Removing entity {entity_id} from index", level=2)
    
    # Track if anything was removed
    removed = False
    
    # Safely handle different index structures
    
    # Remove from type index
    if hasattr(self, 'type_index'):
        for type_uri, entities in list(self.type_index.items()):
            # Handle both list and set collections
            if isinstance(entities, (list, set)) and entity_id in entities:
                if isinstance(entities, list):
                    entities.remove(entity_id)
                else:  # It's a set
                    entities.discard(entity_id)
                removed = True
                self._debug(f"Removed {entity_id} from type index for {type_uri}", level=3)
                # If this was the last entity of this type, remove the type entry
                if not entities:
                    del self.type_index[type_uri]
    
    # Remove from text index
    if hasattr(self, 'text_index'):
        for term, entities in list(self.text_index.items()):
            if isinstance(entities, (list, set)) and entity_id in entities:
                if isinstance(entities, list):
                    entities.remove(entity_id)
                else:  # It's a set
                    entities.discard(entity_id)
                removed = True
                self._debug(f"Removed {entity_id} from text index for term '{term}'", level=3)
                # If this was the last entity with this term, remove the term entry
                if not entities:
                    del self.text_index[term]
    
    # Remove from predicate index
    if hasattr(self, 'predicate_index'):
        for pred, entities in list(self.predicate_index.items()):
            if isinstance(entities, (list, set)) and entity_id in entities:
                if isinstance(entities, list):
                    entities.remove(entity_id)
                else:  # It's a set
                    entities.discard(entity_id)
                removed = True
                self._debug(f"Removed {entity_id} from predicate index for {pred}", level=3)
                # If this was the last entity with this predicate, remove the predicate entry
                if not entities:
                    del self.predicate_index[pred]
    
    # Remove from ID index if it exists
    if hasattr(self, 'id_index') and entity_id in self.id_index:
        del self.id_index[entity_id]
        removed = True
        self._debug(f"Removed {entity_id} from ID index", level=3)
    
    return removed

# %% ../d_04_vmemory.ipynb 73
@patch
def update(self:IndexManager, entity, graph_id=None):
    """Update an entity in the index
    
    Args:
        entity: Entity to update in the index
        graph_id: Optional graph ID
        
    Returns:
        Boolean indicating success
    """
    if "@id" not in entity:
        self._debug("Cannot update entity without @id", level=1)
        return False
        
    entity_id = entity["@id"]
    self._debug(f"Updating entity {entity_id} in index", level=2)
    
    # First remove the existing entity from the index
    self.remove(entity_id)
    
    # Then index it with the updated information
    # Use the original index method - make sure it exists in the original code
    if hasattr(self, 'index'):
        return self.index(entity, graph_id)
    else:
        # Fallback if 'index' doesn't exist but 'add' does
        return self.add(entity, graph_id) if hasattr(self, 'add') else False

# %% ../d_04_vmemory.ipynb 75
@patch
def update_entity(self:GraphManager, entity, graph_id=None):
    """Update an existing entity in the graph
    
    Args:
        entity: Entity to update
        graph_id: Optional graph ID to update in
        
    Returns:
        Boolean indicating success
    """
    if "@id" not in entity:
        self._debug("Cannot update entity without @id", level=1)
        return False
        
    entity_id = entity["@id"]
    
    # If no graph specified, try to find which graph contains this entity
    if graph_id is None:
        graph_id = self.get_entity_graph(entity_id)
        if not graph_id:
            self._debug(f"Entity {entity_id} not found in any graph", level=1)
            return False
    
    # Get the graph
    graph = self.get_graph(graph_id)
    if not graph:
        self._debug(f"Graph {graph_id} not found", level=1)
        return False
    
    # Remove the existing entity completely
    uri_ref = URIRef(entity_id)
    graph.remove((uri_ref, None, None))
    
    # Also remove cases where this entity is the object of triples
    graph.remove((None, None, uri_ref))
    
    # Add the updated entity
    try:
        g = Graph()
        g.parse(data=json.dumps(entity), format="json-ld")
        graph += g
        self._debug(f"Updated entity {entity_id} in graph {graph_id}", level=2)
        return True
    except Exception as e:
        self._debug(f"Error updating entity {entity_id}: {str(e)}", level=1)
        return False

# %% ../d_04_vmemory.ipynb 76
@patch
def get_entity_graph(self:GraphManager, entity_id):
    """Get the graph ID that contains an entity
    
    Args:
        entity_id: ID of the entity to find
        
    Returns:
        Graph ID or None if not found
    """
    uri_ref = URIRef(entity_id)
    
    # Check if entity exists in the default graph
    default_graph = self.get_graph(None)  # Get default graph using our improved method
    if default_graph and (uri_ref, None, None) in default_graph:
        return "default"  # Use "default" as the identifier
    
    # Check all named graphs
    for graph_id, graph in self.graphs.items():
        # Skip default graph as we already checked it
        if graph_id == "default":
            continue
            
        if (uri_ref, None, None) in graph:
            return graph_id
    
    return None

# %% ../d_04_vmemory.ipynb 77
@patch
def get_graph(self:GraphManager, graph_id):
    """Get a graph by ID, handling default graph properly
    
    Args:
        graph_id: ID of the graph or None/default for default graph
        
    Returns:
        RDFLib Graph or None if not found
    """
    # Handle default graph specially
    if graph_id is None or graph_id == "default":
        # Get default graph from dataset
        if hasattr(self, 'dataset'):
            try:
                return self.dataset.default_context  # Preferred method
            except AttributeError:
                # Fall back to alternative methods
                try:
                    from rdflib.graph import DATASET_DEFAULT_GRAPH_ID
                    return self.dataset.graph(DATASET_DEFAULT_GRAPH_ID)
                except (ImportError, AttributeError):
                    try:
                        # Try calling graph() with no arguments
                        return self.dataset.graph()
                    except:
                        pass
        
        # Fall back to graphs dict if dataset not available
        if "default" in self.graphs:
            return self.graphs["default"]
        else:
            self._debug("Default graph not found", level=1)
            return None
    
    # Get named graph
    if graph_id in self.graphs:
        return self.graphs[graph_id]
    
    self._debug(f"Graph {graph_id} not found", level=1)
    return None

# %% ../d_04_vmemory.ipynb 79
class VerifiableSemanticMemory(SemanticMemory):
    def __init__(self, 
                cache_dir=None, 
                preload_vocabs=None,
                key_storage_path=None,
                debug=False, 
                debug_level=0,
                validation_enabled=True,
                provenance_enabled=True,
                signature_required=False):
        """Initialize verifiable semantic memory with improved signature support"""
        # Call parent constructor first to initialize base functionality
        super().__init__(cache_dir=cache_dir, 
                        preload_vocabs=preload_vocabs,
                        debug=debug, 
                        debug_level=debug_level)
        
        # Set up storage path
        storage_path = Path(cache_dir) if cache_dir else Path(".")
        
        # Add our verification components
        self.key_manager = KeyManager(
            storage_path=key_storage_path,
            debug=debug,
            debug_level=debug_level,
            parent=self
        )
        
        self.did_manager = DIDManager(
            key_manager=self.key_manager,
            storage_path=key_storage_path,
            debug=debug,
            debug_level=debug_level,
            parent=self
        )
        
        # Add the ValidationManager
        self.validator = ValidationManager(
            parent=self,
            storage_path=storage_path,
            debug=debug,
            debug_level=debug_level
        )
        
        # Add the ProvenanceManager
        self.provenance = ProvenanceManager(
            parent=self,
            storage_path=storage_path,
            debug=debug,
            debug_level=debug_level
        )
        
        # Add the SignatureStore
        self.signature_store = SignatureStore(storage_path=storage_path)
        
        # Configuration
        self.validation_enabled = validation_enabled
        self.provenance_enabled = provenance_enabled
        self.signature_required = signature_required
        
        # Add shape graph detection to context processor
        self._add_context_processor_extensions()
        
        # Initialize extra stats
        self._debug_stats["verifications_performed"] = 0
        self._debug_stats["validations_performed"] = 0
        self._debug_stats["signatures_added"] = 0
        
        self._debug("VerifiableSemanticMemory initialized", level=1)

# %% ../d_04_vmemory.ipynb 84
@patch
def query_by_id(self:VerifiableSemanticMemory, entity_id, verify=False):
    """Get entity by ID with optional verification
    
    Args:
        entity_id: ID of the entity to retrieve
        verify: Whether to verify the entity's signature
        
    Returns:
        Entity with optional verification metadata
    """
    # Get the entity using the parent class method directly
    entity = SemanticMemory.query_by_id(self, entity_id)
    
    # If verification is requested, verify it
    if verify and entity:
        self._debug(f"Verifying signature on entity {entity_id}", level=2)
        verification_result = self.verify_entity_signature(entity_id)
        
        # Add verification result to entity
        entity["_verification"] = verification_result
    
    return entity

# %% ../d_04_vmemory.ipynb 86
@patch
def sign_entity(self:VerifiableSemanticMemory, entity, did, debug_level=None):
    """Create a signature for an entity using consistent PyLD normalization
    
    Args:
        entity: Entity to sign
        did: DID to sign with
        debug_level: Optional debugging level (None, "basic", or "full")
        
    Returns:
        Entity with embedded proof
    """
    # Debug output based on level
    if debug_level:
        print(f"\n===== DEBUGGING sign_entity with DID {did} =====")
        print(f"1. Created copy of entity with ID: {entity.get('@id', 'unknown')}")
    else:
        self._debug(f"Creating signature for entity with DID {did}", level=2)
    
    # Make a deep copy to avoid modifying the original
    entity_copy = copy.deepcopy(entity)
    
    # Ensure we have a consistent context
    if "@context" not in entity_copy:
        entity_copy["@context"] = {"schema": "http://schema.org/"}
        if debug_level:
            print("1b. Added missing @context to entity")
    
    # Remove any existing proof if present
    if "proof" in entity_copy:
        had_proof = True
        del entity_copy["proof"]
        if debug_level:
            print("2. Found and removed existing proof")
    elif debug_level:
        print("2. No existing proof found")
    
    try:
        # Ensure we have a valid DID
        did_doc = self.did_manager.resolve_did(did)
        if not did_doc:
            if debug_level:
                print(f"3. ERROR: Could not resolve DID: {did}")
            else:
                self._debug(f"Could not resolve DID: {did}", level=1)
            return None
        
        if debug_level:
            print(f"3. Successfully resolved DID: {did}")
            print("4. Creating PyLD normalized representation")
        
        # First compact the entity to ensure consistent form
        from pyld import jsonld
        
        # Use PyLD normalization for consistent signing
        normalized = jsonld.normalize(
            entity_copy,
            {'algorithm': 'URDNA2015', 'format': 'application/n-quads'}
        )
        
        if debug_level:
            print(f"   PyLD normalized length: {len(normalized)} characters")
            if debug_level == "full":
                print(f"   First 100 chars: {normalized[:100]}...")
        else:
            self._debug(f"Created normalized representation for signing", level=3)
        
        # Sign the normalized representation
        if debug_level:
            print("5. Signing the normalized entity")
        
        signature = self.did_manager.sign_with_did(normalized.encode('utf-8'), did)
        
        if not signature:
            if debug_level:
                print("   ERROR: Signing failed")
            else:
                self._debug("Signing failed", level=1)
            return None
            
        if debug_level:
            print(f"   Created signature of length {len(signature)} bytes")
            
        # Create a proof object
        timestamp = datetime.now().isoformat() + "Z"
        proof = {
            "type": "Ed25519Signature2020",
            "created": timestamp,
            "verificationMethod": f"{did}#keys-1",
            "proofPurpose": "assertionMethod",
            "proofValue": base64.b64encode(signature).decode('ascii')
        }
        
        if debug_level:
            print(f"6. Created proof object with type {proof['type']}")
        
        # Store proof canonicalization info for verification
        proof["canonicalizationAlgorithm"] = "URDNA2015"
        
        # Add the proof to the entity
        result = copy.deepcopy(entity)
        result["proof"] = proof
        
        # Store the signature separately in the signature store
        entity_id = entity.get("@id")
        if entity_id:
            try:
                # Ensure directory exists first
                if self.signature_store.storage_path:
                    ensure_directory_exists(self.signature_store.storage_path)
                    
                self.signature_store.add_signature(
                    entity_id,
                    did,
                    proof["proofValue"],
                    metadata={
                        "type": proof["type"],
                        "created": timestamp,
                        "verificationMethod": proof["verificationMethod"],
                        "normalized": normalized,  # Store the exact normalized form we signed
                        "canonicalizationAlgorithm": "URDNA2015"
                    }
                )
                if debug_level:
                    print(f"7. Stored signature in signature store for entity {entity_id}")
                else:
                    self._debug(f"Stored signature in signature store for entity {entity_id}", level=2)
            except Exception as e:
                if debug_level:
                    print(f"   ERROR storing signature: {str(e)}")
                else:
                    self._debug(f"Error storing signature: {str(e)}", level=1)
        
        # Test verification immediately if in debug mode
        if debug_level:
            print("8. Testing verification immediately after signing")
            verify_result = self.did_manager.verify_did_signature(
                normalized.encode('utf-8'),
                signature,
                did
            )
            print(f"   Immediate verification result: {verify_result}")
        
        if debug_level:
            print(f"9. Successfully signed entity with DID: {did}")
        else:
            self._debug(f"Successfully created signature for entity with DID: {did}", level=2)
            
        self._debug_stats["signatures_added"] = self._debug_stats.get("signatures_added", 0) + 1
        
        return result
        
    except Exception as e:
        if debug_level:
            print(f"ERROR signing entity: {str(e)}")
            traceback.print_exc()
        else:
            self._debug(f"Error signing entity: {str(e)}", level=1)
        return None
